"use client";

import { useTranslation } from "@/app/config/i18n";
import { Button } from "@/components/ui/button";
import { Card, CardBody, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { ArrowLeft, CheckCircle2, Save } from "lucide-react";
import { useState } from "react";

interface ApprovalFormData {
  agentUuid?: string;
  approvalType: string;
  approvalStatus: string;
  requestReason: string;
  requestDetails: string;
  approvalCriteria: string;
}

export default function ApprovalCreatePage() {
  const { t, mounted } = useTranslation();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formData, setFormData] = useState<ApprovalFormData>({
    agentUuid: "",
    approvalType: "DEPLOYMENT",
    approvalStatus: "PENDING",
    requestReason: "",
    requestDetails: "",
    approvalCriteria: "",
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const response = await fetch("/api/governance/agents/approval", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      });

      if (response.ok) {
        const data = await response.json();
        // Redirigir al detalle de la aprobación creada
        if (data.id) {
          window.location.href = `/governance/agents/approval/${data.id}`;
        } else {
          window.location.href = "/governance/agents/approval/overview";
        }
      } else {
        const error = await response.json();
        alert(t("agents.approval.create.error", "Error al crear la aprobación: ") + (error.message || "Error desconocido"));
      }
    } catch (error) {
      console.error("Error al crear aprobación:", error);
      alert(t("agents.approval.create.error", "Error al crear la aprobación"));
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleCancel = () => {
    window.location.href = "/governance/agents/approval/overview";
  };

  if (!mounted) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <CheckCircle2 className="w-8 h-8 animate-spin mx-auto mb-2 text-muted-foreground" />
          <p className="text-muted-foreground">{t("common.loading", "Cargando...")}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="space-y-1">
          <div className="flex items-center gap-3">
            <CheckCircle2 className="w-6 h-6 text-primary" />
            <h1 className="text-2xl font-bold text-foreground">
              {t("agents.approval.create.title", "Crear Nueva Aprobación")}
            </h1>
          </div>
          <p className="text-sm text-muted-foreground ml-9">
            {t("agents.approval.create.subtitle", "Complete el formulario para crear una nueva aprobación")}
          </p>
        </div>
        <Button
          variant="outline"
          size="sm"
          className="flex items-center gap-2"
          onClick={handleCancel}
        >
          <ArrowLeft className="h-4 w-4" />
          {t("common.cancel", "Cancelar")}
        </Button>
      </div>

      {/* Formulario */}
      <form onSubmit={handleSubmit}>
        <Card className="backdrop-blur-md bg-background/60 border-border/50">
          <CardHeader>
            <CardTitle>
              {t("agents.approval.create.formTitle", "Información de la Aprobación")}
            </CardTitle>
          </CardHeader>
          <CardBody className="space-y-4">
            {/* UUID - Solo lectura */}
            <div className="space-y-2">
              <Label htmlFor="uuid">
                {t("agents.approval.create.uuid", "UUID")}
              </Label>
              <div className="flex items-center gap-2">
                <Input
                  id="uuid"
                  value={t("agents.approval.create.uuidAutoGenerated", "Se generará automáticamente")}
                  disabled
                  className="bg-muted text-muted-foreground"
                />
                <span className="text-xs text-muted-foreground">
                  {t("agents.approval.create.uuidInfo", "UUID generado automáticamente")}
                </span>
              </div>
            </div>

            {/* Agent UUID */}
            <div className="space-y-2">
              <Label htmlFor="agentUuid">
                {t("agents.approval.create.agentUuid", "Agent UUID")} *
              </Label>
              <Input
                id="agentUuid"
                value={formData.agentUuid}
                onChange={(e) => setFormData({ ...formData, agentUuid: e.target.value })}
                placeholder={t("agents.approval.create.agentUuidPlaceholder", "Ingrese el UUID del agente")}
                required
              />
            </div>

            {/* Approval Type */}
            <div className="space-y-2">
              <Label htmlFor="approvalType">
                {t("agents.approval.create.approvalType", "Tipo de Aprobación")} *
              </Label>
              <Select
                value={formData.approvalType}
                onValueChange={(value) => setFormData({ ...formData, approvalType: value })}>
                <SelectTrigger>
                  <SelectValue placeholder={t("agents.approval.create.approvalTypePlaceholder", "Seleccione el tipo")} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="DEPLOYMENT">
                    {t("agents.approval.create.typeDeployment", "Despliegue")}
                  </SelectItem>
                  <SelectItem value="VERSION_UPDATE">
                    {t("agents.approval.create.typeVersionUpdate", "Actualización de Versión")}
                  </SelectItem>
                  <SelectItem value="CONFIGURATION_CHANGE">
                    {t("agents.approval.create.typeConfigurationChange", "Cambio de Configuración")}
                  </SelectItem>
                  <SelectItem value="PRODUCTION_ACCESS">
                    {t("agents.approval.create.typeProductionAccess", "Acceso a Producción")}
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Request Reason */}
            <div className="space-y-2">
              <Label htmlFor="requestReason">
                {t("agents.approval.create.requestReason", "Razón de Solicitud")} *
              </Label>
              <Input
                id="requestReason"
                value={formData.requestReason}
                onChange={(e) => setFormData({ ...formData, requestReason: e.target.value })}
                placeholder={t("agents.approval.create.requestReasonPlaceholder", "Ingrese la razón de la solicitud")}
                required
              />
            </div>

            {/* Request Details */}
            <div className="space-y-2">
              <Label htmlFor="requestDetails">
                {t("agents.approval.create.requestDetails", "Detalles de Solicitud")} *
              </Label>
              <Textarea
                id="requestDetails"
                value={formData.requestDetails}
                onChange={(e) => setFormData({ ...formData, requestDetails: e.target.value })}
                placeholder={t("agents.approval.create.requestDetailsPlaceholder", "Ingrese los detalles de la solicitud")}
                rows={4}
                required
              />
            </div>

            {/* Approval Criteria */}
            <div className="space-y-2">
              <Label htmlFor="approvalCriteria">
                {t("agents.approval.create.approvalCriteria", "Criterios de Aprobación")} *
              </Label>
              <Textarea
                id="approvalCriteria"
                value={formData.approvalCriteria}
                onChange={(e) => setFormData({ ...formData, approvalCriteria: e.target.value })}
                placeholder={t("agents.approval.create.approvalCriteriaPlaceholder", "Ingrese los criterios de aprobación")}
                rows={4}
                required
              />
            </div>

            {/* Approval Status */}
            <div className="space-y-2">
              <Label htmlFor="approvalStatus">
                {t("agents.approval.create.approvalStatus", "Estado de Aprobación")} *
              </Label>
              <Select
                value={formData.approvalStatus}
                onValueChange={(value) => setFormData({ ...formData, approvalStatus: value })}>
                <SelectTrigger>
                  <SelectValue placeholder={t("agents.approval.create.approvalStatusPlaceholder", "Seleccione el estado")} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="PENDING">
                    {t("agents.approval.create.statusPending", "Pendiente")}
                  </SelectItem>
                  <SelectItem value="APPROVED">
                    {t("agents.approval.create.statusApproved", "Aprobado")}
                  </SelectItem>
                  <SelectItem value="REJECTED">
                    {t("agents.approval.create.statusRejected", "Rechazado")}
                  </SelectItem>
                  <SelectItem value="ACTIVE">
                    {t("agents.approval.create.statusActive", "Activo")}
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>

            {/* Botones de acción */}
            <div className="flex justify-end gap-2 pt-4">
              <Button
                type="button"
                variant="outline"
                onClick={handleCancel}
                disabled={isSubmitting}
              >
                {t("common.cancel", "Cancelar")}
              </Button>
              <Button
                type="submit"
                className="bg-primary hover:bg-primary/90"
                disabled={isSubmitting}
              >
                <Save className="h-4 w-4 mr-2" />
                {isSubmitting
                  ? t("common.saving", "Guardando...")
                  : t("agents.approval.create.saveButton", "Guardar Aprobación")}
              </Button>
            </div>
          </CardBody>
        </Card>
      </form>
    </div>
  );
}


