<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.7.3</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>

	<packaging>war</packaging>
	<groupId>suinsit.product</groupId>
	<version>1.2.23</version>
	<artifactId>suinsit-nova</artifactId>
	<properties>
		<java.version>17</java.version>
		<spring-ai.version>1.0.0-M2</spring-ai.version>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<zk.version>10.0.2</zk.version>
		<zkspringboot.version>3.2.6.1</zkspringboot.version>
		<zkckeditor.version>4.21.0.0</zkckeditor.version>
		<springboot.version>2.7.18</springboot.version>
		<zats.version>4.0.0</zats.version>
		<zkgmaps.version>4.0.3</zkgmaps.version>
		<zkcharts.version>11.4.7.0</zkcharts.version>
		<zkpivotable.version>3.0.0</zkpivotable.version>
		<zkpoi.version>3.9.17</zkpoi.version>
		<zss.version>3.9.6</zss.version>
		<keikai.oss.version>5.0.0.1</keikai.oss.version>
		<keikai.ex.version>6.0.0</keikai.ex.version>
		<junit.version>4.13.1</junit.version>
		<commons-io>2.7</commons-io>
		<version.jackson>2.13.4</version.jackson>
		<enart.version>3.7.8</enart.version>
		<suinsit.version>3.2.6-RELEASE</suinsit.version>
		<version.jdom>1.1.3</version.jdom>
		<suinsit.nocode.applications>1.0.4</suinsit.nocode.applications>
	</properties>


	<dependencies>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jetty</artifactId>
			<!--			<scope>provided</scope>-->
			<exclusions>
				
				<exclusion>
					<groupId>org.eclipse.jetty.websocket</groupId>
					<artifactId>websocket-server</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.eclipse.jetty.websocket</groupId>
					<artifactId>javax-websocket-server-impl</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jdbc</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.zaxxer</groupId>
					<artifactId>HikariCP</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-amqp</artifactId>

		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-websocket</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework</groupId>
					<artifactId>spring-websocket</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!--
		https://mvnrepository.com/artifact/javax.websocket/javax.websocket-api -->
		<dependency>
			<groupId>org.zkoss.zkspringboot</groupId>
			<artifactId>zkspringboot-starter</artifactId>
			<version>${zkspringboot.version}</version>
			<type>pom</type>
			<!--			excluded (conflicts with ZATS)-->
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-tomcat</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-webflux</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jdbc</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>org.javassist</groupId>
			<artifactId>javassist</artifactId>
			<version>3.29.1-GA</version>
		</dependency>
		<dependency>
			<groupId>commons-fileupload</groupId>
			<artifactId>commons-fileupload</artifactId>
			<version>1.5</version>
			<exclusions>
				<exclusion>
					<groupId>commons-io</groupId>
					<artifactId>commons-io</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>1.2.3</version>
			<scope>provided</scope>
		</dependency>
		<!-- ZK Core -->
		<dependency>
			<groupId>org.zkoss.common</groupId>
			<artifactId>zcommon</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.common</groupId>
			<artifactId>zel</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.common</groupId>
			<artifactId>zweb</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.common</groupId>
			<artifactId>zweb-dsp</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>zhtml</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>zk</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>zkbind</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>zkplus</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>zkwebfragment</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>zul</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<!-- PE/EE -->
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>zkex</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>zkmax</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>zml</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>zuti</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zk</groupId>
			<artifactId>za11y</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<!-- Themes -->
		<dependency>
			<groupId>org.zkoss.themepack</groupId>
			<artifactId>theme-pack</artifactId>
			<version>${zk.version}</version>
		</dependency>
		<!-- Addons -->
		<dependency>
			<groupId>org.zkoss.zkforge</groupId>
			<artifactId>ckez</artifactId>
			<version>${zkckeditor.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.zkforge</groupId>
			<artifactId>gmapsz</artifactId>
			<version>${zkgmaps.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.addons</groupId>
			<artifactId>rxzk</artifactId>
			<version>0.8.0</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.chart</groupId>
			<artifactId>zkcharts</artifactId>
			<version>${zkcharts.version}</version>
		</dependency>
		<!-- ZK Pivottable -->
		<dependency>
			<groupId>org.zkoss.pivot</groupId>
			<artifactId>pivottable</artifactId>
			<version>${zkpivotable.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.poi</groupId>
			<artifactId>zpoi</artifactId>
			<version>${zkpoi.version}</version>
		</dependency>
		<dependency>
			<groupId>org.zkoss.poi</groupId>
			<artifactId>zpoiex</artifactId>
			<version>${zkpoi.version}</version>
		</dependency>
		<!-- Keikai -->
		<!--            <dependency>-->
		<!--                <groupId>io.keikai</groupId>-->
		<!--                <artifactId>keikai-oss</artifactId>-->
		<!--            </dependency>-->
		<!--            <dependency>-->
		<!--                <groupId>io.keikai</groupId>-->
		<!--                <artifactId>keikai-ex</artifactId>-->
		<!--            </dependency>-->
		<!--            <dependency>-->
		<!--                <groupId>io.keikai</groupId>-->
		<!--                <artifactId>keikai-jsp</artifactId>-->
		<!--            </dependency>-->
		<!--dependencias suinsit -->
		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.framework.context</artifactId>
			<version>${suinsit.version}</version>
		</dependency>
		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.codegenerator.web</artifactId>
			<version>${suinsit.version}</version>
		</dependency>
		<dependency>
			<groupId>com.suinsit.discovery.domain</groupId>
			<artifactId>discovery.domain</artifactId>
			<version>1.0.6</version>
		</dependency>

		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.codegenerator.runtime</artifactId>
			<version>${suinsit.version}</version>
			<exclusions>
				<exclusion>
					<groupId>commons-io</groupId>
					<artifactId>commons-io</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.nocode.commons</artifactId>
			<version>${suinsit.version}</version>
		</dependency>
		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.studio.designer.web</artifactId>
			<version>${suinsit.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.logging.log4j</groupId>
					<artifactId>log4j-core</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-io</groupId>
					<artifactId>commons-io</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.studio.designer</artifactId>
			<version>${suinsit.version}</version>
		</dependency>
		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.framework.integration.mail</artifactId>
			<version>${suinsit.version}</version>
		</dependency>
		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.framework.webclient</artifactId>
			<version>${suinsit.version}</version>
		</dependency>

		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.nocode.web</artifactId>
			<version>${suinsit.version}</version>
		</dependency>
		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.mapping.web</artifactId>
			<version>${suinsit.version}</version>
		</dependency>
		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.importer.wsdl</artifactId>
			<version>${suinsit.version}</version>
		</dependency>
		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.importer.openapi</artifactId>
			<version>${suinsit.version}</version>
			<exclusions>
				<exclusion>
					<groupId>commons-io</groupId>
					<artifactId>commons-io</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.nocode.semantic</artifactId>
			<version>${suinsit.version}</version>
			<exclusions>
				<exclusion>
					<groupId>commons-io</groupId>
					<artifactId>commons-io</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>suinsit.framework</groupId>
			<artifactId>suinsit.importer.json</artifactId>
			<version>${suinsit.version}</version>
			<exclusions>
				<exclusion>
					<groupId>com.github.everit-org.json-schema</groupId>
					<artifactId>org.everit.json.schema</artifactId>
				</exclusion>
				<exclusion>
					<groupId>commons-io</groupId>
					<artifactId>commons-io</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!--enart -->
		<dependency>
			<groupId>org.enartframework</groupId>
			<artifactId>enart-context</artifactId>
			<version>${enart.version}</version>
		</dependency>
		<dependency>
			<groupId>org.enartframework</groupId>
			<artifactId>enart-security</artifactId>
			<version>${enart.version}</version>
		</dependency>
		<dependency>
			<groupId>org.enartframework</groupId>
			<artifactId>enart-message</artifactId>
			<version>${enart.version}</version>
		</dependency>
		<dependency>
			<groupId>org.enartframework</groupId>
			<artifactId>enartframework.jvm</artifactId>
			<version>${enart.version}</version>
		</dependency>
		<dependency>
			<groupId>org.burningwave</groupId>
			<artifactId>core</artifactId>
			<version>12.62.7</version>

		</dependency>

		<dependency>
			<groupId>org.enartframework</groupId>
			<artifactId>enart-persistence</artifactId>
			<version>${enart.version}</version>
			<exclusions>
				<exclusion>
					<groupId>com.zaxxer</groupId>
					<artifactId>HikariCP</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.enartframework</groupId>
			<artifactId>enart-mathematic</artifactId>
			<version>${enart.version}</version>

		</dependency>
		<dependency>
			<groupId>org.enartframework</groupId>
			<artifactId>enart-integration-s3</artifactId>
			<version>${enart.version}</version>
		</dependency>
		<dependency>
			<groupId>org.enartframework</groupId>
			<artifactId>enart-ui-zkoss</artifactId>
			<version>${enart.version}</version>
		</dependency>
		<dependency>
			<groupId>com.zaxxer</groupId>
			<artifactId>HikariCP</artifactId>
			<version>5.0.1</version>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
		</dependency>
		<dependency>
			<groupId>org.freemarker</groupId>
			<artifactId>freemarker</artifactId>
		</dependency>
		<dependency>
			<groupId>org.antlr</groupId>
			<artifactId>ST4</artifactId>
			<version>4.0.8</version>
		</dependency>
		<dependency>
			<groupId>org.antlr</groupId>
			<artifactId>stringtemplate</artifactId>
			<version>3.2.1</version>
		</dependency>
		<dependency>
			<groupId>org.modelmapper</groupId>
			<artifactId>modelmapper</artifactId>
			<version>3.1.0</version>
		</dependency>
		<!-- arquitectura -->
		<dependency>
			<groupId>com.suinsit.architecture</groupId>
			<artifactId>suinsit.architecture.nocode</artifactId>
			<version>3.2.3</version>
		</dependency>
		<dependency>
			<groupId>org.enartframework</groupId>
			<artifactId>schema.model</artifactId>
			<version>3.8.0</version>
		</dependency>
		<dependency>
			<groupId>org.enartframework</groupId>
			<artifactId>schema.pgsql</artifactId>
			<version>3.8.0</version>
			<exclusions>
				<exclusion>
					<groupId>org.enartframework</groupId>
					<artifactId>enart-persistence</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.jdom</groupId>
			<artifactId>jdom</artifactId>
			<version>${version.jdom}</version>
		</dependency>
		<dependency>
			<groupId>net.htmlparser.jericho</groupId>
			<artifactId>jericho-html</artifactId>
			<version>3.4</version>

		</dependency>
		<dependency>
			<groupId>us.fatehi</groupId>
			<artifactId>schemacrawler</artifactId>
			<version>16.11.5</version>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>bsh</groupId>
			<artifactId>bsh</artifactId>
			<version>2.0b4</version>
		</dependency>
		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-s3</artifactId>
			<version>1.12.267</version>
		</dependency>
		<dependency>
			<groupId>org.bouncycastle</groupId>
			<artifactId>bcprov-jdk15on</artifactId>
			<version>1.70</version>
		</dependency>

	<!-- https://mvnrepository.com/artifact/org.apache.tika/tika-core -->
		<dependency>
			<groupId>org.apache.tika</groupId>
			<artifactId>tika-core</artifactId>
			<version>3.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-yaml</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-xml</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-databind</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-annotations</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.core</groupId>
			<artifactId>jackson-core</artifactId>

		</dependency>
		<dependency>
			<groupId>org.codehaus.jackson</groupId>
			<artifactId>jackson-jaxrs</artifactId>
			<version>1.9.13</version>
		</dependency>
		<dependency>
			<groupId>com.opencsv</groupId>
			<artifactId>opencsv</artifactId>
			<version>4.2</version>
		</dependency>
		<dependency>
			<groupId>cglib</groupId>
			<artifactId>cglib</artifactId>
			<version>3.3.0</version>
		</dependency>
		<dependency>
			<groupId>org.apache.poi</groupId>
			<artifactId>poi</artifactId>
			<version>4.1.1</version>
		</dependency>
		<dependency>
			<groupId>jexcelapi</groupId>
			<artifactId>jxl</artifactId>
			<version>2.6</version>
		</dependency>
		<!--jasper -->
		<!-- https://mvnrepository.com/artifact/ar.com.fdvs/DynamicJasper -->
		<dependency>
			<groupId>ar.com.fdvs</groupId>
			<artifactId>DynamicJasper</artifactId>
			<version>5.3.6</version>
			<exclusions>
				<exclusion>
					<groupId>commons-io</groupId>
					<artifactId>commons-io</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<!-- Aplicaciones -->
		<dependency>
			<groupId>suinsit.nocode.applications</groupId>
			<artifactId>applicactions.commons</artifactId>
			<version>${suinsit.nocode.applications}</version>
			<exclusions>
				<exclusion>
					<groupId>com.enartsystems.discovery.domain</groupId>
					<artifactId>discovery.domain</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>suinsit.nocode.applications</groupId>
			<artifactId>applications.dms</artifactId>
			<version>${suinsit.nocode.applications}</version>
			<exclusions>
				<exclusion>
					<groupId>com.enartsystems.discovery.domain</groupId>
					<artifactId>discovery.domain</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>suinsit.nocode.applications</groupId>
			<artifactId>applications.bpmn</artifactId>
			<version>${suinsit.nocode.applications}</version>
			<exclusions>
				<exclusion>
					<groupId>com.enartsystems.discovery.domain</groupId>
					<artifactId>discovery.domain</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>suinsit.nocode.applications</groupId>
			<artifactId>applications.contratos</artifactId>
			<version>${suinsit.nocode.applications}</version>
		</dependency>
		<dependency>
			<groupId>suinsit.nocode.applications</groupId>
			<artifactId>applications.erp.rrhh</artifactId>
			<version>${suinsit.nocode.applications}</version>
			<exclusions>
				<exclusion>
					<groupId>com.enartsystems.discovery.domain</groupId>
					<artifactId>discovery.domain</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>suinsit.nocode.applications</groupId>
			<artifactId>applications.fiscal</artifactId>
			<version>${suinsit.nocode.applications}</version>
			<exclusions>
				<exclusion>
					<groupId>com.enartsystems.discovery.domain</groupId>
					<artifactId>discovery.domain</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>suinsit.nocode.applications</groupId>
			<artifactId>applications.marketing</artifactId>
			<version>${suinsit.nocode.applications}</version>
		</dependency>
		<dependency>
			<groupId>suinsit.nocode.applications</groupId>
			<artifactId>applications.sat</artifactId>
			<version>${suinsit.nocode.applications}</version>
		</dependency>
        <!-- micros de gobierno -->
		<dependency>
              <groupId>com.suinsit.leka-compliance</groupId>
              <artifactId>leka-compliance-domain</artifactId>  
                      <version>1.0.0</version>
                      <exclusions>
                      	<exclusion>
                      		<groupId>io.hypersistence</groupId>
                      		<artifactId>
                      			hypersistence-utils-hibernate-62
                      		</artifactId>
                      	</exclusion>
                      </exclusions>
		</dependency>
		<dependency>
			<groupId>suinsit.nocode.applications</groupId>
			<artifactId>applications.erp.facturacion</artifactId>
			<version>1.2.1</version>
		</dependency>
		<!-- suincode -->
		<dependency>
			<groupId>com.suinsit.architecture</groupId>
			<artifactId>suinsit.architecture.nocode</artifactId>
			<version>3.2.2</version>
		</dependency>

		<!--
		https://mvnrepository.com/artifact/com.vladsch.flexmark/flexmark-all -->
		<dependency>
			<groupId>com.vladsch.flexmark</groupId>
			<artifactId>flexmark-all</artifactId>
			<version>0.64.8</version>

		</dependency>

		<!--		</dependency>-->
		<!--		<dependency>-->
		<!--			<groupId>org.springframework.ai</groupId>-->
		<!--			<artifactId>spring-ai-openai-spring-boot-starter</artifactId>-->
		<!--		</dependency>-->
		<!--		<dependency>-->
		<!--			<groupId>org.springframework.ai</groupId>-->
		<!--
		<artifactId>spring-ai-postgresml-spring-boot-starter</artifactId>-->
		<!--		</dependency>-->

		<!--		<dependency>-->
		<!--			<groupId>org.springframework.boot</groupId>-->
		<!--			<artifactId>spring-boot-starter-tomcat</artifactId>-->
		<!--			<scope>provided</scope>-->
		<!--		</dependency>-->
		<!--		<dependency>-->
		<!--			<groupId>org.springframework.boot</groupId>-->
		<!--			<artifactId>spring-boot-starter-test</artifactId>-->
		<!--			<scope>test</scope>-->
		<!--		</dependency>-->
		<!--		<dependency>-->
		<!--			<groupId>org.springframework.security</groupId>-->
		<!--			<artifactId>spring-security-test</artifactId>-->
		<!--			<scope>test</scope>-->
		<!--		</dependency>-->
	</dependencies>
	<!--	<dependencyManagement>-->
	<!--		<dependencies>-->
	<!--			<dependency>-->
	<!--				<groupId>org.springframework.ai</groupId>-->
	<!--				<artifactId>spring-ai-bom</artifactId>-->
	<!--				<version>${spring-ai.version}</version>-->
	<!--				<type>pom</type>-->
	<!--				<scope>import</scope>-->
	<!--			</dependency>-->
	<!--		</dependencies>-->
	<!--	</dependencyManagement>-->

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>ZK CE</id>
			<name>ZK CE Repository</name>
			<url>https://mavensync.zkoss.org/maven2</url>
		</repository>
		<repository>
			<id>zkoss-ee</id>
			<name>zkoss-ee</name>
			<url>https://maven.zkoss.org/repo/zk/ee/</url>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>
</project>