// Datos mock para menús y páginas basados en la configuración actual
// Estos datos simulan lo que vendría de la base de datos

import { Menu, MenuWithPages, Page } from "./menu-types";

export const mockMenus: Menu[] = [
  {
    id: "1",
    name: "Dashboard",
    icon: "BarChart3",
    description: "Panel principal del sistema",
    isActive: true,
    order: 1,
    roles: [
      "admin",
      "developer",
      "viewer",
      "business_analytics",
      "ai_analytics",
      "ai_developer",
      "devops",
      "project_manager",
      "architect",
      "ai_architect",
    ],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "2",
    name: "Code Playground",
    icon: "Zap",
    description: "Desarrollo de código y funcionalidades técnicas",
    isActive: true,
    order: 2,
    roles: ["developer", "devops"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "3",
    name: "AI Playground",
    icon: "Brain",
    description: "Herramientas de inteligencia artificial",
    isActive: true,
    order: 3,
    roles: ["developer", "ai_developer"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "4",
    name: "RAG System",
    icon: "Database",
    description: "Sistema de recuperación y generación aumentada",
    isActive: true,
    order: 4,
    roles: ["developer", "ai_analytics"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "5",
    name: "Model Management",
    icon: "Brain",
    description: "Gestión de modelos de machine learning",
    isActive: true,
    order: 5,
    roles: ["developer", "ai_developer", "ai_analytics"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "6",
    name: "Serving",
    icon: "Server",
    description: "Despliegue y operación de servicios",
    isActive: true,
    order: 6,
    roles: ["devops"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "7",
    name: "Governance",
    icon: "Shield",
    description: "Gobernanza y políticas del sistema",
    isActive: true,
    order: 7,
    roles: ["project_manager"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "8",
    name: "Model Evaluation",
    icon: "Target",
    description: "Evaluación de modelos de IA",
    isActive: true,
    order: 8,
    roles: ["ai_analytics"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "9",
    name: "AI Training",
    icon: "Brain",
    description: "Entrenamiento de modelos de IA",
    isActive: true,
    order: 9,
    roles: ["ai_analytics"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "10",
    name: "Technology Management",
    icon: "Layers",
    description: "Gestión de tecnologías y arquitecturas",
    isActive: true,
    order: 10,
    roles: ["developer", "ai_analytics", "architect"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "11",
    name: "Domain Ingestion",
    icon: "Database",
    description: "Ingesta y gestión de dominios de conocimiento",
    isActive: true,
    order: 11,
    roles: ["developer", "ai_analytics", "project_manager"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "12",
    name: "Training Center",
    icon: "GraduationCap",
    description: "Centro de entrenamiento y capacitación",
    isActive: true,
    order: 12,
    roles: ["admin", "developer", "viewer", "project_manager"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "13",
    name: "Admin",
    icon: "Settings",
    description: "Panel de administración del sistema",
    isActive: true,
    order: 13,
    roles: ["admin"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "14",
    name: "Infrastructure",
    icon: "Server",
    description:
      "Gestión de infraestructura cloud, clusters K8s y GPU instances",
    isActive: true,
    order: 14,
    roles: ["admin", "devops", "architect"],
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
];

export const mockPages: Page[] = [
  // Dashboard
  {
    id: "1",
    menuId: "1",
    name: "Dashboard Principal",
    href: "/dashboard",
    icon: "BarChart3",
    roles: [
      "admin",
      "developer",
      "viewer",
      "business_analytics",
      "ai_analytics",
      "ai_developer",
      "devops",
      "project_manager",
      "architect",
      "ai_architect",
    ],
    isDefault: true,
    order: 1,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },

  // Code Playground
  {
    id: "2",
    menuId: "2",
    name: "Code Editor",
    href: "/code-playground",
    icon: "Zap",
    roles: ["admin", "developer", "devops"],
    isDefault: true,
    order: 1,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "3",
    menuId: "2",
    name: "Snippets",
    href: "/code-playground/snippets",
    icon: "FileText",
    roles: ["admin", "developer", "devops"],
    isDefault: false,
    order: 2,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "4",
    menuId: "2",
    name: "Templates",
    href: "/code-playground/templates",
    icon: "ClipboardList",
    roles: ["admin", "developer", "devops"],
    isDefault: false,
    order: 3,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },

  // AI Playground
  {
    id: "5",
    menuId: "3",
    name: "Chat & Text",
    href: "/playground/chat",
    icon: "MessageCircle",
    roles: ["admin", "developer", "ai_analytics"],
    isDefault: true,
    order: 1,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "6",
    menuId: "3",
    name: "Image Generation",
    href: "/playground/images",
    icon: "Image",
    roles: ["admin", "developer", "ai_analytics"],
    isDefault: false,
    order: 2,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },

  // RAG System
  {
    id: "7",
    menuId: "4",
    name: "RAG Dashboard",
    href: "/rag-training",
    icon: "Database",
    roles: ["developer", "ai_analytics"],
    isDefault: true,
    order: 1,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "8",
    menuId: "4",
    name: "Documents",
    href: "/rag-training/documents",
    icon: "FileText",
    roles: ["developer", "ai_analytics"],
    isDefault: false,
    order: 2,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "9",
    menuId: "4",
    name: "Webscraping",
    href: "/rag-training/webscraping",
    icon: "Globe",
    roles: ["developer", "ai_analytics"],
    isDefault: false,
    order: 3,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "10",
    menuId: "4",
    name: "Chat",
    href: "/rag-training/chat",
    icon: "MessageCircle",
    roles: ["developer", "ai_analytics"],
    isDefault: false,
    order: 4,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },

  // Serving
  {
    id: "11",
    menuId: "6",
    name: "Deployments",
    href: "/serving",
    icon: "Server",
    roles: ["devops"],
    isDefault: true,
    order: 1,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "12",
    menuId: "6",
    name: "Monitoring",
    href: "/serving/monitoring",
    icon: "Activity",
    roles: ["devops"],
    isDefault: false,
    order: 2,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "13",
    menuId: "6",
    name: "Resources",
    href: "/serving/resources",
    icon: "Database",
    roles: ["devops"],
    isDefault: false,
    order: 3,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },

  // Governance
  {
    id: "14",
    menuId: "7",
    name: "Policies",
    href: "/governance",
    icon: "Shield",
    roles: ["project_manager"],
    isDefault: true,
    order: 1,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "15",
    menuId: "7",
    name: "Security",
    href: "/governance/security",
    icon: "Shield",
    roles: ["project_manager"],
    isDefault: false,
    order: 2,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "16",
    menuId: "7",
    name: "Monitoring",
    href: "/governance/monitoring",
    icon: "Activity",
    roles: ["project_manager"],
    isDefault: false,
    order: 3,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "29",
    menuId: "7",
    name: "BPMN Task Inbox",
    href: "/bpmn/task-inbox",
    icon: "Inbox",
    roles: [
      "admin",
      "developer",
      "viewer",
      "business_analytics",
      "ai_analytics",
      "ai_developer",
      "devops",
      "project_manager",
      "architect",
      "ai_architect",
      "agencia",
      "it",
      "oem",
      "business_admin"
    ],
    isDefault: false,
    order: 4,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },

  // Training Center
  {
    id: "17",
    menuId: "12",
    name: "Training Center",
    href: "/training-center",
    icon: "GraduationCap",
    roles: ["admin", "developer", "viewer", "project_manager"],
    isDefault: true,
    order: 1,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },

  // Admin
  {
    id: "18",
    menuId: "13",
    name: "Admin Panel",
    href: "/admin",
    icon: "Settings",
    roles: ["admin"],
    isDefault: true,
    order: 1,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "19",
    menuId: "13",
    name: "Role Configuration",
    href: "/config/roles",
    icon: "Settings",
    roles: ["admin"],
    isDefault: false,
    order: 2,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },

  // Infrastructure
  {
    id: "20",
    menuId: "14",
    name: "Infrastructure Overview",
    href: "/infrastructure",
    icon: "Server",
    roles: ["admin", "devops", "architect"],
    isDefault: true,
    order: 1,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "21",
    menuId: "14",
    name: "Cloud Providers",
    href: "/infrastructure/providers",
    icon: "Cloud",
    roles: ["admin", "devops", "architect"],
    isDefault: false,
    order: 2,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "22",
    menuId: "14",
    name: "Kubernetes Clusters",
    href: "/infrastructure/kubernetes",
    icon: "Server",
    roles: ["admin", "devops", "architect"],
    isDefault: false,
    order: 3,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "23",
    menuId: "14",
    name: "GPU Instances",
    href: "/infrastructure/gpu-instances",
    icon: "Cpu",
    roles: ["admin", "devops", "architect"],
    isDefault: false,
    order: 4,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "24",
    menuId: "14",
    name: "Infrastructure Deployments",
    href: "/infrastructure/deployments",
    icon: "Rocket",
    roles: ["admin", "devops", "architect"],
    isDefault: false,
    order: 5,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "25",
    menuId: "14",
    name: "Cloud Resources",
    href: "/infrastructure/resources",
    icon: "Database",
    roles: ["admin", "devops", "architect"],
    isDefault: false,
    order: 6,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "26",
    menuId: "14",
    name: "Provider Credentials",
    href: "/infrastructure/credentials",
    icon: "Key",
    roles: ["admin", "devops", "architect"],
    isDefault: false,
    order: 7,
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "27",
    name: "Cost Management",
    href: "/infrastructure/cost-management",
    icon: "DollarSign",
    order: 8,
    roles: ["admin", "devops"],
    isDefault: false,
    menuId: "6",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
  {
    id: "28",
    name: "🚀 Prototipo Trekker",
    href: "/trekker-prototype",
    icon: "Rocket",
    order: 9,
    roles: ["admin", "devops", "developer"],
    isDefault: false,
    menuId: "1",
    isActive: true,
    createdAt: "2024-01-01T00:00:00Z",
    updatedAt: "2024-01-15T00:00:00Z",
  },
];

// Función helper para obtener menús con sus páginas
export const getMenusWithPages = (): MenuWithPages[] => {
  return mockMenus.map((menu) => ({
    ...menu,
    pages: mockPages.filter((page) => page.menuId === menu.id),
  }));
};

// Función helper para obtener menús por roles
export const getMenusByRoles = (roles: string[]): Menu[] => {
  return mockMenus.filter(
    (menu) => menu.isActive && menu.roles.some((role) => roles.includes(role))
  );
};

// Función helper para obtener páginas por menú
export const getPagesByMenu = (menuId: string): Page[] => {
  return mockPages
    .filter((page) => page.menuId === menuId && page.isActive)
    .sort((a, b) => a.order - b.order);
};

// Función helper para obtener páginas por roles
export const getPagesByRoles = (roles: string[]): Page[] => {
  return mockPages.filter(
    (page) => page.isActive && page.roles.some((role) => roles.includes(role))
  );
};
