-- =====================================================
-- EU REGISTRATION - CREACIÓN DE TABLA E ÍNDICES BÁSICOS
-- =====================================================
-- Módulo: EU AI Act Compliance
-- Propósito: Registro en Base de Datos UE según Art. 49 y Anexo VIII
-- Fecha: Diciembre 2025
-- =====================================================

-- Drop table if exists
DROP TABLE IF EXISTS REGEUREGISTRATIONS CASCADE;

-- Tabla de EU Registrations
CREATE TABLE REGEUREGISTRATIONS (
    IDXEUREGISTRATION BIGSERIAL PRIMARY KEY,
    iduuid VARCHAR(36) NOT NULL,
    IDXPROJECT BIGINT NOT NULL REFERENCES PRJPROJECTS(IDXPROJECT) ON DELETE CASCADE,
    -- Tipo de registro (3 secciones Anexo VIII)
    REGREGISTRATIONTYPE VARCHAR(20) NOT NULL, -- STANDARD, SENSITIVE, NATIONAL
    REGART49SECTION VARCHAR(10), -- 49.1, 49.2, 49.3
    -- EU Registration ID (asignado por sistema UE)
    REGEUREGISTRATIONID VARCHAR(100),
    -- Submission Data (todos los campos Anexo VIII según sección)
    REGSUBMISSIONDATA TEXT NOT NULL, -- JSON
    -- Status
    REGSTATUS VARCHAR(20), -- DRAFT, PENDING, SUBMITTED, REGISTERED, REJECTED, ERROR
    REGSUBMISSIONDATE TIMESTAMP,
    REGREGISTRATIONDATE TIMESTAMP,
    -- Response from EU API
    REGEUAPIRESPONSE TEXT, -- JSON
    REGERRORMESSAGE TEXT,
    -- Retry tracking
    REGATTEMPTS INTEGER DEFAULT 0,
    REGLASTATTEMPTAT TIMESTAMP,
    -- Sensitive system (Art. 49.4 - registro no público)
    REGISSENSITIVE BOOLEAN DEFAULT FALSE,
    -- National registration (Art. 49.5 - infraestructuras críticas)
    REGISNATIONAL BOOLEAN DEFAULT FALSE,
    REGNATIONALREGISTRATIONID VARCHAR(100),
    -- Vínculo con PMM Plan
    IDXPMMPLAN BIGINT REFERENCES PMMPOSTMARKETMONITORINGPLANS(IDXPMMPLAN) ON DELETE SET NULL,
    -- Audit
    REGCREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    REGUPDATEDAT TIMESTAMP
);

-- Claves únicas
ALTER TABLE REGEUREGISTRATIONS ADD CONSTRAINT uk_reg_uuid UNIQUE (iduuid);
CREATE UNIQUE INDEX uk_reg_euregistrationid ON REGEUREGISTRATIONS(REGEUREGISTRATIONID) 
WHERE REGEUREGISTRATIONID IS NOT NULL;

-- Índices básicos
CREATE INDEX idx_reg_project ON REGEUREGISTRATIONS(IDXPROJECT);
CREATE INDEX idx_reg_type ON REGEUREGISTRATIONS(REGREGISTRATIONTYPE);
CREATE INDEX idx_reg_status ON REGEUREGISTRATIONS(REGSTATUS);
CREATE INDEX idx_reg_euregid ON REGEUREGISTRATIONS(REGEUREGISTRATIONID);
CREATE INDEX idx_reg_sensitive ON REGEUREGISTRATIONS(REGISSENSITIVE);
CREATE INDEX idx_reg_national ON REGEUREGISTRATIONS(REGISNATIONAL);
CREATE INDEX idx_reg_uuid ON REGEUREGISTRATIONS(iduuid);

-- Comentarios
COMMENT ON TABLE REGEUREGISTRATIONS IS 'Registros en Base de Datos UE según EU AI Act Art. 49 y Anexo VIII';
COMMENT ON COLUMN REGEUREGISTRATIONS.REGREGISTRATIONTYPE IS 'Tipo: STANDARD, SENSITIVE, NATIONAL';
COMMENT ON COLUMN REGEUREGISTRATIONS.REGSUBMISSIONDATA IS 'JSON con todos los campos mandatorios según sección del Anexo VIII';
COMMENT ON COLUMN REGEUREGISTRATIONS.REGSTATUS IS 'Estado: DRAFT, PENDING, SUBMITTED, REGISTERED, REJECTED, ERROR';
COMMENT ON COLUMN REGEUREGISTRATIONS.REGISSENSITIVE IS 'Art. 49.4 - TRUE para sistemas sensibles (Anexo III.1, III.6, III.7) - registro no público';
COMMENT ON COLUMN REGEUREGISTRATIONS.REGISNATIONAL IS 'Art. 49.5 - TRUE para infraestructuras críticas - registro nacional en lugar de UE';
COMMENT ON COLUMN REGEUREGISTRATIONS.REGATTEMPTS IS 'Número de intentos de envío para retry logic con exponential backoff';


