apiVersion: v1
kind: Namespace
metadata:
  name: codeflowx-govern-systems
  labels:
    app: codeflowx
    tier: infrastructure
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: codeflowx-govern
  labels:
    app: codeflowx
    tier: applications
    environment: production

