-- ============================================================================
-- EXTENSIONES A MODMODELS PARA GOBIERNO DE ADAPTACIÓN DE MODELOS
-- ============================================================================
-- Proyecto: CodeFlowX Govern
-- Propósito: Soportar adapters, merge, quantización y fine-tuning
-- Versión: 1.0
-- Fecha: 2025-10-26
-- ============================================================================

-- Nuevos campos para MODMODELS
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODISADAPTER BOOLEAN DEFAULT FALSE;
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODISFINETUNED BOOLEAN DEFAULT FALSE;
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODISQUANTIZED BOOLEAN DEFAULT FALSE;
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODISMERGED BOOLEAN DEFAULT FALSE;
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODISBASEMODEL BOOLEAN DEFAULT FALSE;

-- Configuraciones específicas por tipo de adaptación
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODADAPTERCONFIG JSONB;
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODQUANTIZATIONCONFIG JSONB;
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODMERGECONFIG JSONB;
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODFINETUNINGCONFIG JSONB;

-- Referencia al modelo base (single parent - caso más común)
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS IDMODBASEMODEL BIGINT;

-- Metadata de transformación
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODTRANSFORMATIONTYPE TEXT[]; -- ['LORA', 'QLORA', 'GPTQ', 'AWQ', 'DARE_TIES', etc.]
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODCOMPRESSIONRATIO DECIMAL; -- Para quantización
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODPARAMETERCOUNT BIGINT; -- Parámetros del modelo
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODTRAINABLEPARAMETERS BIGINT; -- Solo para adapters

-- Governance específico
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODADAPTATIONAPPROVALSTATUS TEXT[];
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODADAPTATIONAPPROVEDBY VARCHAR(255);
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODADAPTATIONAPPROVEDAT TIMESTAMP;

-- Métricas de calidad de adaptación
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODADAPTATIONQUALITYSCORE DECIMAL;
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODPERFORMANCEDEGRADATION DECIMAL; -- % de pérdida vs base

-- FK al modelo base
ALTER TABLE MODMODELS 
    ADD CONSTRAINT FK_MODMODELS_BASEMODEL 
    FOREIGN KEY (IDMODBASEMODEL) 
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE SET NULL
    ON UPDATE CASCADE;

-- Comentarios
COMMENT ON COLUMN MODMODELS.MODISADAPTER IS 'Indica si es un adapter (LoRA, QLoRA, etc.)';
COMMENT ON COLUMN MODMODELS.MODISFINETUNED IS 'Indica si es un modelo fine-tuneado';
COMMENT ON COLUMN MODMODELS.MODISQUANTIZED IS 'Indica si es un modelo quantizado';
COMMENT ON COLUMN MODMODELS.MODISMERGED IS 'Indica si es resultado de merge de modelos';
COMMENT ON COLUMN MODMODELS.MODISBASEMODEL IS 'Indica si es un modelo base (sin adaptar)';
COMMENT ON COLUMN MODMODELS.IDMODBASEMODEL IS 'FK al modelo base del cual deriva (si aplica)';
COMMENT ON COLUMN MODMODELS.MODADAPTERCONFIG IS 'Configuración del adapter (LoRA: rank, alpha, target_modules, etc.)';
COMMENT ON COLUMN MODMODELS.MODQUANTIZATIONCONFIG IS 'Configuración de quantización (method, bits, group_size, etc.)';
COMMENT ON COLUMN MODMODELS.MODMERGECONFIG IS 'Configuración de merge (method, models, weights, etc.)';
COMMENT ON COLUMN MODMODELS.MODFINETUNINGCONFIG IS 'Configuración de fine-tuning (epochs, lr, etc.)';

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_models_adapter ON MODMODELS(MODISADAPTER) WHERE MODISADAPTER = TRUE;
CREATE INDEX IF NOT EXISTS idx_models_quantized ON MODMODELS(MODISQUANTIZED) WHERE MODISQUANTIZED = TRUE;
CREATE INDEX IF NOT EXISTS idx_models_basemodel ON MODMODELS(IDMODBASEMODEL);
CREATE INDEX IF NOT EXISTS idx_models_transformation ON MODMODELS USING GIN(MODTRANSFORMATIONTYPE);

-- Vista para árbol de lineage de modelos
CREATE OR REPLACE VIEW V_MODEL_LINEAGE_TREE AS
WITH RECURSIVE model_tree AS (
    -- Modelos base (raíz del árbol)
    SELECT 
        m.IDXMODEL,
        m.MODNAME,
        m.MODTYPE,
        m.MODISBASEMODEL,
        m.MODISADAPTER,
        m.MODISFINETUNED,
        m.MODISQUANTIZED,
        m.MODISMERGED,
        m.IDMODBASEMODEL,
        0 AS depth,
        ARRAY[m.IDXMODEL] AS path,
        m.MODNAME AS root_model_name
    FROM MODMODELS m
    WHERE m.MODISBASEMODEL = TRUE OR m.IDMODBASEMODEL IS NULL
    
    UNION ALL
    
    -- Modelos derivados (recursivo)
    SELECT 
        m.IDXMODEL,
        m.MODNAME,
        m.MODTYPE,
        m.MODISBASEMODEL,
        m.MODISADAPTER,
        m.MODISFINETUNED,
        m.MODISQUANTIZED,
        m.MODISMERGED,
        m.IDMODBASEMODEL,
        mt.depth + 1,
        mt.path || m.IDXMODEL,
        mt.root_model_name
    FROM MODMODELS m
    INNER JOIN model_tree mt ON m.IDMODBASEMODEL = mt.IDXMODEL
    WHERE NOT (m.IDXMODEL = ANY(mt.path)) -- Evitar ciclos
)
SELECT * FROM model_tree
ORDER BY root_model_name, depth, MODNAME;

COMMENT ON VIEW V_MODEL_LINEAGE_TREE IS 'Árbol completo de lineage de modelos mostrando adaptaciones, quantizaciones, merges';

