CREATE TABLE IF NOT EXISTS icoiso42001control (
    idxicoiso42001control BIGSERIAL PRIMARY KEY,
    iduuid VARCHAR(36) UNIQUE NOT NULL,
    icocontrolcode VARCHAR(40) UNIQUE NOT NULL,
    icocontrolclause VARCHAR(40),
    icocontroltitle VARCHAR(200) NOT NULL,
    icocontroldescription TEXT NOT NULL,
    icocontrolcategory VARCHAR(60),
    icocontrolstatus VARCHAR(20) NOT NULL,
    icocontrolowner VARCHAR(120),
    icocontrollastreview TIMESTAMP,
    icocontrolnextreview TIMESTAMP,
    icocontrolevidence TEXT,
    icocontrolriskimpact VARCHAR(20),
    icocreatedat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    icoupdatedat TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ico_status ON icoiso42001control (icocontrolstatus);
CREATE INDEX IF NOT EXISTS idx_ico_category ON icoiso42001control (icocontrolcategory);
CREATE INDEX IF NOT EXISTS idx_ico_owner ON icoiso42001control (icocontrolowner);

INSERT INTO icoiso42001control (iduuid, icocontrolcode, icocontrolclause, icocontroltitle, icocontroldescription,
                                icocontrolcategory, icocontrolstatus, icocontrolowner, icocontrolriskimpact)
VALUES
    (gen_random_uuid(), 'ISO42001-C01', '4.1', 'Contexto organizacional', 'Mantener análisis actualizado del contexto interno y externo relevante para la gestión de IA.', 'GOVERNANCE', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C02', '4.2', 'Necesidades de partes interesadas', 'Identificar expectativas de stakeholders y traducirlas en requisitos operativos de IA.', 'GOVERNANCE', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C03', '4.3', 'Ámbito del SGIA', 'Documentar el alcance del sistema de gestión de IA y mantenerlo bajo control de cambios.', 'GOVERNANCE', 'PLANNED', NULL, 'LOW'),
    (gen_random_uuid(), 'ISO42001-C04', '5.1', 'Liderazgo y compromiso', 'Evidenciar el liderazgo ejecutivo para proporcionar dirección estratégica y recursos adecuados.', 'LEADERSHIP', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C05', '5.2', 'Política de IA', 'Establecer una política formal de IA aprobada por la dirección con principios éticos y legales.', 'LEADERSHIP', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C06', '5.3', 'Roles de gobernanza', 'Asignar claramente responsabilidades y autoridades para el SGIA.', 'LEADERSHIP', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C07', '6.1', 'Acciones para riesgos y oportunidades', 'Implementar metodología de evaluación de riesgos y oportunidades para sistemas de IA.', 'RISK', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C08', '6.2', 'Objetivos AIMS', 'Definir y revisar objetivos medibles alineados con la política de IA.', 'PERFORMANCE', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C09', '6.3', 'Planificación de cambios', 'Gestionar cambios de manera controlada garantizando impacto evaluado en riesgos y conformidad.', 'OPERATIONS', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C10', '7.1', 'Recursos', 'Asegurar recursos humanos, tecnológicos y financieros adecuados para el SGIA.', 'RESOURCES', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C11', '7.2', 'Competencia', 'Demostrar competencias del personal en gestión responsable de IA mediante programas formativos.', 'RESOURCES', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C12', '7.3', 'Concienciación', 'Implementar campañas y evidencias de concienciación de riesgos y políticas de IA.', 'RESOURCES', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C13', '7.4', 'Comunicación', 'Establecer matriz de comunicación interna y externa sobre desempeño del SGIA.', 'RESOURCES', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C14', '7.5', 'Información documentada', 'Controlar documentos y registros críticos del SGIA con versionado y trazabilidad.', 'RESOURCES', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C15', '8.1', 'Planificación operativa', 'Planificar procesos y controles para el ciclo de vida de sistemas de IA.', 'OPERATIONS', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C16', '8.2', 'Requisitos legales y éticos', 'Mantener un inventario actualizado de requisitos normativos y éticos aplicables.', 'COMPLIANCE', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C17', '8.3', 'Diseño de sistemas', 'Aplicar criterios de seguridad, explicabilidad y calidad desde etapas tempranas de diseño.', 'OPERATIONS', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C18', '8.4', 'Desarrollo y validación', 'Definir controles de validación, pruebas y aceptación antes del despliegue.', 'OPERATIONS', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C19', '8.5', 'Datos y conjuntos de entrenamiento', 'Asegurar calidad, representatividad y trazabilidad de los datos utilizados.', 'DATA', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C20', '8.6', 'Seguridad y resiliencia', 'Proteger los componentes de IA frente a ciberataques y fallos operativos.', 'SECURITY', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C21', '8.7', 'Gestión de proveedores', 'Controlar proveedores y terceros con acceso o influencia sobre sistemas de IA.', 'SUPPLIER', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C22', '8.8', 'Despliegue y liberación', 'Definir criterios de aprobación y rollback antes de liberar modelos o agentes a producción.', 'OPERATIONS', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C23', '8.9', 'Monitoreo continuo', 'Establecer monitoreo en tiempo real de desempeño, sesgos y fallos.', 'MONITORING', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C24', '8.10', 'Gestión de incidencias', 'Implementar proceso formal para captura y resolución de incidentes de IA.', 'MONITORING', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C25', '8.11', 'Desmantelamiento', 'Planificar retirada controlada de sistemas con preservación de registros.', 'OPERATIONS', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C26', '8.12', 'Interacción humana', 'Diseñar puntos de control humano apropiados para supervisión y override.', 'RESPONSIBILITY', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C27', '8.13', 'Protección de datos personales', 'Aplicar medidas de privacidad y protección de datos en todo el ciclo de vida.', 'COMPLIANCE', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C28', '8.14', 'Gestión de sesgos', 'Implementar evaluaciones y planes de mitigación de sesgos en modelos.', 'RESPONSIBILITY', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C29', '8.15', 'Transparencia', 'Proporcionar documentación clara de decisiones, capacidades y limitaciones.', 'RESPONSIBILITY', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C30', '8.16', 'Trazabilidad', 'Mantener rastreo de versiones de modelos, datos y configuraciones.', 'RESPONSIBILITY', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C31', '8.17', 'Robustez técnica', 'Aplicar pruebas adversariales y análisis de robustez periódicos.', 'SECURITY', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C32', '8.18', 'Alineamiento ético', 'Verificar que los resultados soportan principios éticos definidos por la organización.', 'RESPONSIBILITY', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C33', '9.1', 'Seguimiento y medición', 'Definir indicadores clave para medir desempeño del SGIA.', 'PERFORMANCE', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C34', '9.2', 'Auditoría interna', 'Planificar auditorías internas del SGIA con alcance anual.', 'PERFORMANCE', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C35', '9.3', 'Revisión por la dirección', 'Registrar actas de revisión ejecutiva del SGIA con decisiones y acciones.', 'LEADERSHIP', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C36', '10.1', 'No conformidades', 'Gestionar y documentar no conformidades, acciones correctivas y verificación de eficacia.', 'IMPROVEMENT', 'PLANNED', NULL, 'HIGH'),
    (gen_random_uuid(), 'ISO42001-C37', '10.2', 'Mejora continua', 'Identificar oportunidades de mejora del SGIA y priorizarlas.', 'IMPROVEMENT', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C38', '10.3', 'Innovación responsable', 'Evaluar implicaciones éticas y regulatorias antes de introducir nuevas tecnologías de IA.', 'INNOVATION', 'PLANNED', NULL, 'MEDIUM'),
    (gen_random_uuid(), 'ISO42001-C39', '10.4', 'Cierre de vida útil', 'Garantizar almacenamiento seguro de registros y lecciones aprendidas al retirar sistemas.', 'IMPROVEMENT', 'PLANNED', NULL, 'LOW');
