-- =====================================================
-- DATOS MOCK - MÓDULO 06_TRAINING
-- =====================================================
-- Generado automáticamente desde JSONs EnArt
-- =====================================================

-- TRNEXPERIMENTS (Experiment)
-- Namespace: training
-- Campos requeridos: 5
INSERT INTO TRNEXPERIMENTS (TRNNAME, TRNARTIFACTLOCATION, TRNLIFECYCLESTAGE)
VALUES ('Experiment 1 Name', 's3://bucket/path/experiment 1', 'active');
INSERT INTO TRNEXPERIMENTS (TRNNAME, TRNARTIFACTLOCATION, TRNLIFECYCLESTAGE)
VALUES ('Experiment 2 Name', 's3://bucket/path/experiment 2', 'active');
INSERT INTO TRNEXPERIMENTS (TRNNAME, TRNARTIFACTLOCATION, TRNLIFECYCLESTAGE)
VALUES ('Experiment 3 Name', 's3://bucket/path/experiment 3', 'active');
INSERT INTO TRNEXPERIMENTS (TRNNAME, TRNARTIFACTLOCATION, TRNLIFECYCLESTAGE)
VALUES ('Experiment 4 Name', 's3://bucket/path/experiment 4', 'active');
INSERT INTO TRNEXPERIMENTS (TRNNAME, TRNARTIFACTLOCATION, TRNLIFECYCLESTAGE)
VALUES ('Experiment 5 Name', 's3://bucket/path/experiment 5', 'active');

-- TRNRUNS (Run)
-- Namespace: training
-- Campos requeridos: 6
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 1 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 2 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 3 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 4 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 5 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 6 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 7 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 8 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 9 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 10 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 11 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 12 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 13 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 14 Value', ARRAY['ACTIVE'], NOW(), 'active');
INSERT INTO TRNRUNS (TRNRUNUUID, TRNSTATUS, TRNSTARTTIME, TRNLIFECYCLESTAGE)
VALUES ('Run 15 Value', ARRAY['ACTIVE'], NOW(), 'active');

