-- =====================================================
-- Script de creación de tablas para RAG Knowledge Base
-- Módulo: RAG (Retrieval-Augmented Generation)
-- Prefijo: rag_
-- =====================================================

-- Drop tables (orden inverso de dependencias)
DROP TABLE IF EXISTS RAGROLLBACKS CASCADE;
DROP TABLE IF EXISTS RAGVERSIONS CASCADE;
DROP TABLE IF EXISTS RAGDATASOURCES CASCADE;
DROP TABLE IF EXISTS RAGSYSTEMS CASCADE;

-- Tabla: RAGSYSTEMS
-- Descripción: Sistemas RAG registrados
CREATE TABLE RAGSYSTEMS (
    IDXRAGSYSTEM BIGSERIAL PRIMARY KEY,
    RAGSYSTEMNAME VARCHAR(255) NOT NULL,
    RAGDESCRIPTION TEXT,
    RAGVERSION VARCHAR(50) NOT NULL,
    RAGTYPE VARCHAR(50) NOT NULL,
    RAGSTATUS VARCHAR(50) NOT NULL,
    
    -- Métricas de calidad
    RAGOVERALLSCORE DECIMAL(5,2),
    RAGRELEVANCESCORE DECIMAL(5,2),
    RAGACCURACYSCORE DECIMAL(5,2),
    RAGCOMPLETESCORE DECIMAL(5,2),
    RAGCONSISTENCYSCORE DECIMAL(5,2),
    
    -- Métricas de rendimiento
    RAGRESPONSETIME INT,
    RAGTHROUGHPUT INT,
    RAGERRORRATE DECIMAL(5,4),
    RAGUSERSATISFACTION DECIMAL(3,1),
    
    -- Estadísticas
    RAGDATASOURCES INT,
    RAGDOCUMENTS INT,
    RAGQUERIES BIGINT,
    
    -- Compliance y gobierno
    RAGCOMPLIANCE VARCHAR(50) NOT NULL,
    RAGGOVERNANCESTATUS VARCHAR(50),
    RAGRISKLEVEL VARCHAR(50),
    
    -- Metadata
    RAGCONFIGURATION TEXT,
    RAGMETADATA TEXT,
    RAGTAGS TEXT,
    
    -- Auditoría
    RAGCREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RAGUPDATEDAT TIMESTAMP NULL,
    RAGLASTUSED TIMESTAMP NULL,
    RAGCREATEDBY VARCHAR(255)
);

CREATE INDEX idx_ragsystemname ON RAGSYSTEMS(RAGSYSTEMNAME);
CREATE INDEX idx_ragtype ON RAGSYSTEMS(RAGTYPE);
CREATE INDEX idx_ragstatus ON RAGSYSTEMS(RAGSTATUS);
CREATE INDEX idx_ragcompliance ON RAGSYSTEMS(RAGCOMPLIANCE);
CREATE INDEX idx_ragcreatedat ON RAGSYSTEMS(RAGCREATEDAT);

COMMENT ON TABLE RAGSYSTEMS IS 'Sistemas RAG (Retrieval-Augmented Generation)';

-- Tabla: RAGDATASOURCES
-- Descripción: Fuentes de datos de sistemas RAG
CREATE TABLE RAGDATASOURCES (
    IDXRAGDATASOURCE BIGSERIAL PRIMARY KEY,
    IDXRAGSYSTEM BIGINT NOT NULL,
    RAGDSSOURCENAME VARCHAR(255) NOT NULL,
    RAGDSSOURCETYPE VARCHAR(50) NOT NULL,
    RAGDSSOURCEURL VARCHAR(500),
    RAGDSINDEXSTATUS VARCHAR(50) NOT NULL,
    RAGDSDOCUMENTCOUNT INT,
    RAGDSLASTINDEXED TIMESTAMP NULL,
    RAGDSDATACLASS VARCHAR(50),
    RAGDSQUALITYSCORE DECIMAL(5,2),
    RAGDSBIASSCORE DECIMAL(5,2),
    RAGDSACCESS TEXT,
    
    -- Auditoría
    RAGDSCREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RAGDSUPDATEDAT TIMESTAMP NULL,
    
    FOREIGN KEY (IDXRAGSYSTEM) REFERENCES RAGSYSTEMS(IDXRAGSYSTEM) ON DELETE CASCADE
);

CREATE INDEX idx_ragdssourcename ON RAGDATASOURCES(RAGDSSOURCENAME);
CREATE INDEX idx_ragdssourcetype ON RAGDATASOURCES(RAGDSSOURCETYPE);
CREATE INDEX idx_ragdsindexstatus ON RAGDATASOURCES(RAGDSINDEXSTATUS);
CREATE INDEX idx_ragds_ragsystem ON RAGDATASOURCES(IDXRAGSYSTEM);

COMMENT ON TABLE RAGDATASOURCES IS 'Fuentes de datos de sistemas RAG';

-- Tabla: RAGVERSIONS
-- Descripción: Versionamiento de sistemas RAG
CREATE TABLE RAGVERSIONS (
    IDXRAGVERSION BIGSERIAL PRIMARY KEY,
    IDXRAGSYSTEM BIGINT NOT NULL,
    RAGVVERSIONNUMBER VARCHAR(50) NOT NULL,
    RAGVDESCRIPTION TEXT,
    RAGVSTATUS VARCHAR(50) NOT NULL,
    RAGVCONFIGURATION TEXT,
    RAGVPERFORMANCE DECIMAL(5,2),
    RAGVACCURACY DECIMAL(5,2),
    RAGVCHANGELOG TEXT,
    
    -- Auditoría
    RAGVCREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RAGVCREATEDBY VARCHAR(255),
    
    FOREIGN KEY (IDXRAGSYSTEM) REFERENCES RAGSYSTEMS(IDXRAGSYSTEM) ON DELETE CASCADE,
    UNIQUE (IDXRAGSYSTEM, RAGVVERSIONNUMBER)
);

CREATE INDEX idx_ragvversionnumber ON RAGVERSIONS(RAGVVERSIONNUMBER);
CREATE INDEX idx_ragvstatus ON RAGVERSIONS(RAGVSTATUS);
CREATE INDEX idx_ragv_ragsystem ON RAGVERSIONS(IDXRAGSYSTEM);

COMMENT ON TABLE RAGVERSIONS IS 'Versionamiento de sistemas RAG';

-- Tabla: RAGROLLBACKS
-- Descripción: Historial de rollbacks de sistemas RAG
CREATE TABLE RAGROLLBACKS (
    IDXRAGROLLBACK BIGSERIAL PRIMARY KEY,
    IDXRAGSYSTEM BIGINT NOT NULL,
    RAGRFROMVERSION VARCHAR(50) NOT NULL,
    RAGRTOVERSION VARCHAR(50) NOT NULL,
    RAGRSTATUS VARCHAR(50) NOT NULL,
    RAGRREASON TEXT,
    RAGRDURATION INT,
    RAGRIMPACT VARCHAR(50),
    RAGRERROR TEXT,
    
    -- Auditoría
    RAGRINITIATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    RAGRCOMPLETEDAT TIMESTAMP NULL,
    RAGRINITIATEDBY VARCHAR(255),
    
    FOREIGN KEY (IDXRAGSYSTEM) REFERENCES RAGSYSTEMS(IDXRAGSYSTEM) ON DELETE CASCADE
);

CREATE INDEX idx_ragrstatus ON RAGROLLBACKS(RAGRSTATUS);
CREATE INDEX idx_ragrinitiatedat ON RAGROLLBACKS(RAGRINITIATEDAT);
CREATE INDEX idx_ragr_ragsystem ON RAGROLLBACKS(IDXRAGSYSTEM);

COMMENT ON TABLE RAGROLLBACKS IS 'Historial de rollbacks de sistemas RAG';

-- Datos de ejemplo para desarrollo
INSERT INTO RAGSYSTEMS (
    RAGSYSTEMNAME, RAGDESCRIPTION, RAGVERSION, RAGTYPE, RAGSTATUS,
    RAGOVERALLSCORE, RAGRELEVANCESCORE, RAGACCURACYSCORE, RAGCOMPLETESCORE, RAGCONSISTENCYSCORE,
    RAGRESPONSETIME, RAGTHROUGHPUT, RAGERRORRATE, RAGUSERSATISFACTION,
    RAGDATASOURCES, RAGDOCUMENTS, RAGQUERIES,
    RAGCOMPLIANCE, RAGGOVERNANCESTATUS, RAGRISKLEVEL,
    RAGTAGS, RAGCREATEDBY
) VALUES (
    'Knowledge Base RAG',
    'Sistema RAG para consultas sobre documentación técnica',
    '2.1.0',
    'KNOWLEDGE_BASE',
    'ACTIVE',
    92.5, 94.2, 91.8, 89.5, 93.1,
    245, 150, 0.02, 4.7,
    12, 2500, 12500,
    'COMPLIANT', 'APPROVED', 'LOW',
    'knowledge-base,documentation,technical',
    'System'
);


