-- =====================================================================
-- SCRIPT DE POBLACIÓN SSO - PERMISOS DE ROLES PARA MENU ITEMS (AGENTS)
-- =====================================================================
-- Fecha: Octubre 29, 2025
-- Versión: 1.0
-- Descripción: Asignación de permisos de roles a menu items del módulo AGENTS
-- 
-- Estructura SSOROLESMENU:
--   - IDXSSOROLESMENU: PK autonumérico (no se incluye en INSERT)
--   - IDSSOMENUITEM0: FK al menu item (mediante subconsulta por ITEM)
--   - IDSSOROL0: FK al rol (mediante subconsulta por ROL)
-- 
-- Roles simplificados (mapeo directo):
--   Admin → Administracion
--   Manager → Governance Manager
--   Developer → AI Developer
--   Viewer → End User
-- 
-- Total AGENTS: 52 menu items con permisos asignados
-- =====================================================================

-- =====================================================================
-- MENU 1: GESTIÓN DE AGENTES
-- =====================================================================

-- 1.1 Listado de Agentes - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Agentes' AND PAGE = 'platform/agents/overview/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Agentes' AND PAGE = 'platform/agents/overview/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Agentes' AND PAGE = 'platform/agents/overview/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Agentes' AND PAGE = 'platform/agents/overview/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 1.2 Crear Agente - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear Agente' AND PAGE = 'platform/agents/create/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear Agente' AND PAGE = 'platform/agents/create/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear Agente' AND PAGE = 'platform/agents/create/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 1.3 Listado de Dominios - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Dominios' AND PAGE = 'platform/agents/registry/domain-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Dominios' AND PAGE = 'platform/agents/registry/domain-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Dominios' AND PAGE = 'platform/agents/registry/domain-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Dominios' AND PAGE = 'platform/agents/registry/domain-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 1.4 Gestionar Dominio - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Dominio' AND PAGE = 'platform/agents/registry/domain.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Dominio' AND PAGE = 'platform/agents/registry/domain.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Dominio' AND PAGE = 'platform/agents/registry/domain.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- MENU 2: OPERACIONES
-- =====================================================================

-- 2.1 Listado de Despliegues - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues' AND PAGE = 'platform/agents/deployment/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues' AND PAGE = 'platform/agents/deployment/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues' AND PAGE = 'platform/agents/deployment/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues' AND PAGE = 'platform/agents/deployment/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 2.2 Estado de Despliegues - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues' AND PAGE = 'platform/agents/deployment/status.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues' AND PAGE = 'platform/agents/deployment/status.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues' AND PAGE = 'platform/agents/deployment/status.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues' AND PAGE = 'platform/agents/deployment/status.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 2.3 Nuevo Despliegue - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nuevo Despliegue' AND PAGE = 'platform/agents/deployment/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nuevo Despliegue' AND PAGE = 'platform/agents/deployment/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nuevo Despliegue' AND PAGE = 'platform/agents/deployment/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 2.4 Listado de Versiones - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/agents/versioning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/agents/versioning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/agents/versioning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/agents/versioning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 2.5 Gestionar Versión - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Versión' AND PAGE = 'platform/agents/versioning/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Versión' AND PAGE = 'platform/agents/versioning/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Versión' AND PAGE = 'platform/agents/versioning/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 2.6 Listado de Rollbacks - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Rollbacks' AND PAGE = 'platform/agents/rollback/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Rollbacks' AND PAGE = 'platform/agents/rollback/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Rollbacks' AND PAGE = 'platform/agents/rollback/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Rollbacks' AND PAGE = 'platform/agents/rollback/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 2.7 Ejecutar Rollback - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Ejecutar Rollback' AND PAGE = 'platform/agents/rollback/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Ejecutar Rollback' AND PAGE = 'platform/agents/rollback/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- MENU 3: MONITOREO Y PERFORMANCE
-- =====================================================================

-- 3.1 Dashboard Principal - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Principal' AND PAGE = 'platform/agents/monitoring/dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Principal' AND PAGE = 'platform/agents/monitoring/dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Principal' AND PAGE = 'platform/agents/monitoring/dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Principal' AND PAGE = 'platform/agents/monitoring/dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 3.2 Overview General - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview General' AND PAGE = 'platform/agents/monitoring/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview General' AND PAGE = 'platform/agents/monitoring/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview General' AND PAGE = 'platform/agents/monitoring/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview General' AND PAGE = 'platform/agents/monitoring/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 3.3 Listado de Salud - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Salud' AND PAGE = 'platform/agents/monitoring/health-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Salud' AND PAGE = 'platform/agents/monitoring/health-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Salud' AND PAGE = 'platform/agents/monitoring/health-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Salud' AND PAGE = 'platform/agents/monitoring/health-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 3.4 Detalle de Salud - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Salud' AND PAGE = 'platform/agents/monitoring/health.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Salud' AND PAGE = 'platform/agents/monitoring/health.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Salud' AND PAGE = 'platform/agents/monitoring/health.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Salud' AND PAGE = 'platform/agents/monitoring/health.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 3.5 Consumo de Recursos - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Consumo de Recursos' AND PAGE = 'platform/agents/monitoring/resources.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Consumo de Recursos' AND PAGE = 'platform/agents/monitoring/resources.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Consumo de Recursos' AND PAGE = 'platform/agents/monitoring/resources.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Consumo de Recursos' AND PAGE = 'platform/agents/monitoring/resources.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 3.6 Análisis de Errores - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores' AND PAGE = 'platform/agents/monitoring/errors.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores' AND PAGE = 'platform/agents/monitoring/errors.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores' AND PAGE = 'platform/agents/monitoring/errors.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores' AND PAGE = 'platform/agents/monitoring/errors.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 3.7 Configurar Monitoreo - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Monitoreo' AND PAGE = 'platform/agents/monitoring/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Monitoreo' AND PAGE = 'platform/agents/monitoring/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- MENU 4: ALERTAS
-- =====================================================================

-- 4.1 Listado de Alertas - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Alertas' AND PAGE = 'platform/agents/alerts/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Alertas' AND PAGE = 'platform/agents/alerts/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Alertas' AND PAGE = 'platform/agents/alerts/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Alertas' AND PAGE = 'platform/agents/alerts/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 4.2 Configurar Alerta - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Alerta' AND PAGE = 'platform/agents/alerts/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Alerta' AND PAGE = 'platform/agents/alerts/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- MENU 5: INTERACCIONES
-- =====================================================================

-- 5.1 Listado de Interacciones - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Interacciones' AND PAGE = 'platform/agents/interactions/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Interacciones' AND PAGE = 'platform/agents/interactions/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Interacciones' AND PAGE = 'platform/agents/interactions/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Interacciones' AND PAGE = 'platform/agents/interactions/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 5.2 Patrones de Interacción - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Patrones de Interacción' AND PAGE = 'platform/agents/interactions/patterns.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Patrones de Interacción' AND PAGE = 'platform/agents/interactions/patterns.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Patrones de Interacción' AND PAGE = 'platform/agents/interactions/patterns.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Patrones de Interacción' AND PAGE = 'platform/agents/interactions/patterns.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 5.3 Detalle de Interacción - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Interacción' AND PAGE = 'platform/agents/interactions/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Interacción' AND PAGE = 'platform/agents/interactions/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Interacción' AND PAGE = 'platform/agents/interactions/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 5.4 Listado de Comunicación - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Comunicación' AND PAGE = 'platform/agents/interactions/communication-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Comunicación' AND PAGE = 'platform/agents/interactions/communication-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Comunicación' AND PAGE = 'platform/agents/interactions/communication-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Comunicación' AND PAGE = 'platform/agents/interactions/communication-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 5.5 Configurar Comunicación - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Comunicación' AND PAGE = 'platform/agents/interactions/communication.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Comunicación' AND PAGE = 'platform/agents/interactions/communication.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Comunicación' AND PAGE = 'platform/agents/interactions/communication.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 5.6 Listado de Colaboración - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Colaboración' AND PAGE = 'platform/agents/interactions/collaboration-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Colaboración' AND PAGE = 'platform/agents/interactions/collaboration-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Colaboración' AND PAGE = 'platform/agents/interactions/collaboration-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Colaboración' AND PAGE = 'platform/agents/interactions/collaboration-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 5.7 Configurar Colaboración - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Colaboración' AND PAGE = 'platform/agents/interactions/collaboration.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Colaboración' AND PAGE = 'platform/agents/interactions/collaboration.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Colaboración' AND PAGE = 'platform/agents/interactions/collaboration.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 5.8 Red de Colaboración - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Red de Colaboración' AND PAGE = 'platform/agents/interactions/network.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Red de Colaboración' AND PAGE = 'platform/agents/interactions/network.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Red de Colaboración' AND PAGE = 'platform/agents/interactions/network.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Red de Colaboración' AND PAGE = 'platform/agents/interactions/network.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- MENU 6: APRENDIZAJE Y EXPERTISE
-- =====================================================================

-- 6.1 Listado de Expertise - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Expertise' AND PAGE = 'platform/agents/learning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Expertise' AND PAGE = 'platform/agents/learning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Expertise' AND PAGE = 'platform/agents/learning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Expertise' AND PAGE = 'platform/agents/learning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 6.2 Gestionar Expertise - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Expertise' AND PAGE = 'platform/agents/learning/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Expertise' AND PAGE = 'platform/agents/learning/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Expertise' AND PAGE = 'platform/agents/learning/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- MENU 7: WORKFLOWS
-- =====================================================================

-- 7.1 Listado de Workflows - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Workflows' AND PAGE = 'platform/agents/workflow/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Workflows' AND PAGE = 'platform/agents/workflow/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Workflows' AND PAGE = 'platform/agents/workflow/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Workflows' AND PAGE = 'platform/agents/workflow/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 7.2 Crear/Editar Workflow - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear/Editar Workflow' AND PAGE = 'platform/agents/workflow/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear/Editar Workflow' AND PAGE = 'platform/agents/workflow/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear/Editar Workflow' AND PAGE = 'platform/agents/workflow/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 7.3 Listado de Ejecuciones - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Ejecuciones' AND PAGE = 'platform/agents/workflow/execution-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Ejecuciones' AND PAGE = 'platform/agents/workflow/execution-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Ejecuciones' AND PAGE = 'platform/agents/workflow/execution-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Ejecuciones' AND PAGE = 'platform/agents/workflow/execution-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 7.4 Detalle de Ejecución - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Ejecución' AND PAGE = 'platform/agents/workflow/execution.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Ejecución' AND PAGE = 'platform/agents/workflow/execution.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Ejecución' AND PAGE = 'platform/agents/workflow/execution.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Ejecución' AND PAGE = 'platform/agents/workflow/execution.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- MENU 8: ÉTICA Y GOBERNANZA
-- =====================================================================

-- 8.1 Listado de Evaluaciones Éticas - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Evaluaciones Éticas' AND PAGE = 'platform/agents/ethics/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Evaluaciones Éticas' AND PAGE = 'platform/agents/ethics/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Evaluaciones Éticas' AND PAGE = 'platform/agents/ethics/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 8.2 Nueva Evaluación Ética - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva Evaluación Ética' AND PAGE = 'platform/agents/ethics/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva Evaluación Ética' AND PAGE = 'platform/agents/ethics/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 8.3 Listado Detección de Sesgo - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado Detección de Sesgo' AND PAGE = 'platform/agents/bias-detection/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado Detección de Sesgo' AND PAGE = 'platform/agents/bias-detection/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado Detección de Sesgo' AND PAGE = 'platform/agents/bias-detection/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 8.4 Analizar Sesgo - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Analizar Sesgo' AND PAGE = 'platform/agents/bias-detection/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Analizar Sesgo' AND PAGE = 'platform/agents/bias-detection/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 8.5 Listado de Transparencia - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Transparencia' AND PAGE = 'platform/agents/transparency/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Transparencia' AND PAGE = 'platform/agents/transparency/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Transparencia' AND PAGE = 'platform/agents/transparency/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 8.6 Configurar Transparencia - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Transparencia' AND PAGE = 'platform/agents/transparency/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Transparencia' AND PAGE = 'platform/agents/transparency/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 8.7 Listado de Gobernanza - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Gobernanza' AND PAGE = 'platform/agents/governance/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Gobernanza' AND PAGE = 'platform/agents/governance/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Gobernanza' AND PAGE = 'platform/agents/governance/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 8.8 Configurar Gobernanza - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Gobernanza' AND PAGE = 'platform/agents/governance/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Gobernanza' AND PAGE = 'platform/agents/governance/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- MENU 9: APROBACIONES Y DECISIONES
-- =====================================================================

-- 9.1 Listado de Aprobaciones - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Aprobaciones' AND PAGE = 'platform/agents/approval/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Aprobaciones' AND PAGE = 'platform/agents/approval/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Aprobaciones' AND PAGE = 'platform/agents/approval/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 9.2 Procesar Aprobación - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Procesar Aprobación' AND PAGE = 'platform/agents/approval/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Procesar Aprobación' AND PAGE = 'platform/agents/approval/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 9.3 Listado de Decisiones - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Decisiones' AND PAGE = 'platform/agents/decisions/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Decisiones' AND PAGE = 'platform/agents/decisions/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Decisiones' AND PAGE = 'platform/agents/decisions/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 9.4 Nueva/Editar Decisión - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva/Editar Decisión' AND PAGE = 'platform/agents/decisions/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva/Editar Decisión' AND PAGE = 'platform/agents/decisions/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 9.5 Auditoría de Decisiones - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Auditoría de Decisiones' AND PAGE = 'platform/agents/decisions/audit.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Auditoría de Decisiones' AND PAGE = 'platform/agents/decisions/audit.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Auditoría de Decisiones' AND PAGE = 'platform/agents/decisions/audit.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- MENU 10: COMPLIANCE
-- =====================================================================

-- 10.1 Estado de Compliance - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Compliance' AND PAGE = 'platform/agents/compliance/status.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Compliance' AND PAGE = 'platform/agents/compliance/status.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Compliance' AND PAGE = 'platform/agents/compliance/status.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 10.2 Listado de Compliance - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Compliance' AND PAGE = 'platform/agents/compliance/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Compliance' AND PAGE = 'platform/agents/compliance/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Compliance' AND PAGE = 'platform/agents/compliance/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 10.3 Configurar Compliance - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Compliance' AND PAGE = 'platform/agents/compliance/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Compliance' AND PAGE = 'platform/agents/compliance/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- MENU 11: HERRAMIENTAS
-- =====================================================================

-- 11.1 Listado de Tools - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Tools' AND PAGE = 'platform/agents/tools/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Tools' AND PAGE = 'platform/agents/tools/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Tools' AND PAGE = 'platform/agents/tools/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Tools' AND PAGE = 'platform/agents/tools/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- 11.2 Nueva Tool - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva Tool' AND PAGE = 'platform/agents/tools/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva Tool' AND PAGE = 'platform/agents/tools/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva Tool' AND PAGE = 'platform/agents/tools/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

COMMIT;

-- =====================================================================
-- FIN DEL SCRIPT - PERMISOS DE ROLES PARA AGENTS
-- =====================================================================
-- Total: 52 menu items con permisos asignados según documentación
-- =====================================================================

