-- =====================================================================
-- SCRIPT DE POBLACIÓN SSO - PERMISOS DE ROLES PARA MENU ITEMS (AGENTS)
-- =====================================================================
-- Fecha: Octubre 29, 2025
-- Versión: 1.0
-- Descripción: Asignación de permisos de roles a menu items del módulo AGENTS
-- 
-- Estructura SSOROLESMENU:
--   - IDXSSOROLESMENU: PK autonumérico (no se incluye en INSERT)
--   - IDSSOMENUITEM0: FK al menu item (mediante subconsulta por ITEM)
--   - IDSSOROL0: FK al rol (mediante subconsulta por ROL)
-- 
-- Roles disponibles según mapeo:
--   Admin: Administracion, Gobernance Admin, Security Admin
--   Manager: Governance Manager, Compliance Manager, Security Manager, Service Manager, Operations Analyst
--   Developer: AI Developer, No-Code Developer, Devops Engineer, data-engineers, ml-engineers, mlops-engineers, ml-leads, senior-ml-engineers
--   Viewer: End User, Auditor, Business Analyst, AI Business Analyst
-- 
-- Total AGENTS: 52 menu items con permisos asignados
-- =====================================================================

-- =====================================================================
-- MENU 1: GESTIÓN DE AGENTES
-- =====================================================================

-- 1.1 Listado de Agentes - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Agentes'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Agentes'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Agentes'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Agentes'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 1.2 Crear Agente - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear Agente'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear Agente'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear Agente'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

-- 1.3 Listado de Dominios - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Dominios'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Dominios'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Dominios'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Dominios'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 1.4 Gestionar Dominio - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Dominio'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Dominio'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Dominio'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

-- =====================================================================
-- MENU 2: OPERACIONES
-- =====================================================================

-- 2.1 Listado de Despliegues - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 2.2 Estado de Despliegues - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 2.3 Nuevo Despliegue - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nuevo Despliegue'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nuevo Despliegue'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nuevo Despliegue'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

-- 2.4 Listado de Versiones - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 2.5 Gestionar Versión - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Versión'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Versión'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Versión'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

-- 2.6 Listado de Rollbacks - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Rollbacks'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Rollbacks'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Rollbacks'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Rollbacks'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 2.7 Ejecutar Rollback - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Ejecutar Rollback'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Ejecutar Rollback'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

-- =====================================================================
-- MENU 3: MONITOREO Y PERFORMANCE
-- =====================================================================

-- 3.1 Dashboard Principal - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSS CulturalOL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Principal'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Principal'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Principal'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Principal'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 3.2 Overview General - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview General'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview General'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview General'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview General'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 3.3 Listado de Salud - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Salud'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Salud'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Salud'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Salud'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 3.4 Detalle de Salud - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Salud'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Salud'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Salud'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Salud'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 3.5 Consumo de Recursos - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Consumo de Recursos'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Consumo de Recursos'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Consumo de Recursos'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Consumo de Recursos'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 3.6 Análisis de Errores - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 3.7 Configurar Monitoreo - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Monitoreo'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Monitoreo'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

-- =====================================================================
-- MENU 4: ALERTAS
-- =====================================================================

-- 4.1 Listado de Alertas - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Alertas'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Alertas'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Alertas'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Alertas'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 4.2 Configurar Alerta - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Alerta'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Alerta'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

-- =====================================================================
-- MENU 5: INTERACCIONES
-- =====================================================================

-- 5.1 Listado de Interacciones - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Interacciones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Interacciones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Interacciones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Interacciones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 5.2 Patrones de Interacción - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Patrones de Interacción'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Patrones de Interacción'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Patrones de Interacción'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Patrones de Interacción'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 5.3 Detalle de Interacción - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Interacción'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Interacción'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Interacción'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

-- 5.4 Listado de Comunicación - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Comunicación'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Comunicación'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Comunicación'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Comunicación'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 5.5 Configurar Comunicación - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Comunicación'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Comunicación'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Comunicación'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

-- 5.6 Listado de Colaboración - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Colaboración'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Colaboración'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Colaboración'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Colaboración'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 5.7 Configurar Colaboración - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Colaboración'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Colaboración'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Colaboración'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

-- 5.8 Red de Colaboración - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Red de Colaboración'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Red de Colaboración'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Red de Colaboración'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Red de Colaboración'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- =====================================================================
-- MENU 6: APRENDIZAJE Y EXPERTISE
-- =====================================================================

-- 6.1 Listado de Expertise - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Expertise'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Expertise'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Expertise'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Expertise'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 6.2 Gestionar Expertise - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Expertise'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Expertise'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Expertise'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

-- =====================================================================
-- MENU 7: WORKFLOWS
-- =====================================================================

-- 7.1 Listado de Workflows - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Workflows'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Workflows'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Workflows'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Workflows'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 7.2 Crear/Editar Workflow - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear/Editar Workflow'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear/Editar Workflow'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Crear/Editar Workflow'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

-- 7.3 Listado de Ejecuciones - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Ejecuciones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Ejecuciones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Ejecuciones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Ejecuciones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 7.4 Detalle de Ejecución - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Ejecución'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Ejecución'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Ejecución'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Ejecución'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- =====================================================================
-- MENU 8: ÉTICA Y GOBERNANZA
-- =====================================================================

-- 8.1 Listado de Evaluaciones Éticas - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Evaluaciones Éticas'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Evaluaciones Éticas'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Evaluaciones Éticas'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 8.2 Nueva Evaluación Ética - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva Evaluación Ética'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva Evaluación Ética'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

-- 8.3 Listado Detección de Sesgo - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado Detección de Sesgo'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado Detección de Sesgo'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado Detección de Sesgo'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 8.4 Analizar Sesgo - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Analizar Sesgo'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Analizar Sesgo'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

-- 8.5 Listado de Transparencia - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Transparencia'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Transparencia'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Transparencia'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 8.6 Configurar Transparencia - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Transparencia'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Transparencia'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

-- 8.7 Listado de Gobernanza - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Gobernanza'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Gobernanza'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Gobernanza'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 8.8 Configurar Gobernanza - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Gobernanza'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Gobernanza'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

-- =====================================================================
-- MENU 9: APROBACIONES Y DECISIONES
-- =====================================================================

-- 9.1 Listado de Aprobaciones - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Aprobaciones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Aprobaciones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Aprobaciones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 9.2 Procesar Aprobación - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Procesar Aprobación'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Procesar Aprobación'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

-- 9.3 Listado de Decisiones - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Decisiones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Decisiones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Decisiones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 9.4 Nueva/Editar Decisión - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva/Editar Decisión'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva/Editar Decisión'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

-- 9.5 Auditoría de Decisiones - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Auditoría de Decisiones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Auditoría de Decisiones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Auditoría de Decisiones'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- =====================================================================
-- MENU 10: COMPLIANCE
-- =====================================================================

-- 10.1 Estado de Compliance - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Compliance'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Compliance'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Compliance'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 10.2 Listado de Compliance - Admin, Manager, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Compliance'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Compliance'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Compliance'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 10.3 Configurar Compliance - Admin, Manager
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Compliance'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Compliance'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

-- =====================================================================
-- MENU 11: HERRAMIENTAS
-- =====================================================================

-- 11.1 Listado de Tools - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Tools'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Tools'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Tools'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Tools'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Viewer')
);

-- 11.2 Nueva Tool - Admin, Manager, Developer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva Tool'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva Tool'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Manager')
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Nueva Tool'),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Developer')
);

COMMIT;

-- =====================================================================
-- FIN DEL SCRIPT - PERMISOS DE ROLES PARA AGENTS
-- =====================================================================
-- Total: 52 menu items con permisos asignados según documentación
-- =====================================================================

