-- =====================================================================
-- SCRIPT DE POBLACIÓN SSO - PERMISOS DE ROLES PARA MENU ITEMS (RAG)
-- =====================================================================
-- Fecha: Octubre 29, 2025
-- Versión: 1.0
-- Descripción: Asignación de permisos de roles a menu items del módulo RAG
-- 
-- Estructura SSOROLESMENU:
--   - IDXSSOROLESMENU: PK autonumérico (no se incluye en INSERT)
--   - IDSSOMENUITEM0: FK al menu item (mediante subconsulta por ITEM + PAGE)
--   - IDSSOROL0: FK al rol (mediante subconsulta por ROL)
-- 
-- Roles simplificados (mapeo directo):
--   Admin → Administracion
--   Manager → Governance Manager
--   Developer → AI Developer
--   Viewer → End User
-- 
-- Total RAG: 17 menu items con permisos asignados
-- =====================================================================

-- 1. Dashboard de RAG - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard de RAG' AND PAGE = 'platform/rag/overview/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard de RAG' AND PAGE = 'platform/rag/overview/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard de RAG' AND PAGE = 'platform/rag/overview/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard de RAG' AND PAGE = 'platform/rag/overview/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 2. Resumen de RAG - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de RAG' AND PAGE = 'platform/rag/overview/summary.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de RAG' AND PAGE = 'platform/rag/overview/summary.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de RAG' AND PAGE = 'platform/rag/overview/summary.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de RAG' AND PAGE = 'platform/rag/overview/summary.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 3. Listado de Data Sources - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Data Sources' AND PAGE = 'platform/rag/data-sources/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Data Sources' AND PAGE = 'platform/rag/data-sources/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Data Sources' AND PAGE = 'platform/rag/data-sources/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Data Sources' AND PAGE = 'platform/rag/data-sources/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 4. Gestionar Data Source - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Data Source' AND PAGE = 'platform/rag/data-sources/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Data Source' AND PAGE = 'platform/rag/data-sources/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Data Source' AND PAGE = 'platform/rag/data-sources/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Data Source' AND PAGE = 'platform/rag/data-sources/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 5. Progreso de Embeddings - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Progreso de Embeddings' AND PAGE = 'platform/rag/data-sources/embedding-progress.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Progreso de Embeddings' AND PAGE = 'platform/rag/data-sources/embedding-progress.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Progreso de Embeddings' AND PAGE = 'platform/rag/data-sources/embedding-progress.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Progreso de Embeddings' AND PAGE = 'platform/rag/data-sources/embedding-progress.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 6. Análisis de Cobertura - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Cobertura' AND PAGE = 'platform/rag/data-sources/coverage-analysis.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Cobertura' AND PAGE = 'platform/rag/data-sources/coverage-analysis.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Cobertura' AND PAGE = 'platform/rag/data-sources/coverage-analysis.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Cobertura' AND PAGE = 'platform/rag/data-sources/coverage-analysis.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 7. Estadísticas - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estadísticas' AND PAGE = 'platform/rag/data-sources/statistics.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estadísticas' AND PAGE = 'platform/rag/data-sources/statistics.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estadísticas' AND PAGE = 'platform/rag/data-sources/statistics.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estadísticas' AND PAGE = 'platform/rag/data-sources/statistics.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 8. Gestionar Registry - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Registry' AND PAGE = 'platform/rag/registry/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Registry' AND PAGE = 'platform/rag/registry/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Registry' AND PAGE = 'platform/rag/registry/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Registry' AND PAGE = 'platform/rag/registry/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 9. Calidad de Retrieval - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Calidad de Retrieval' AND PAGE = 'platform/rag/quality-control/retrieval-quality.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Calidad de Retrieval' AND PAGE = 'platform/rag/quality-control/retrieval-quality.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Calidad de Retrieval' AND PAGE = 'platform/rag/quality-control/retrieval-quality.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Calidad de Retrieval' AND PAGE = 'platform/rag/quality-control/retrieval-quality.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 10. Distribución de Chunks - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Distribución de Chunks' AND PAGE = 'platform/rag/quality-control/chunk-distribution.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Distribución de Chunks' AND PAGE = 'platform/rag/quality-control/chunk-distribution.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Distribución de Chunks' AND PAGE = 'platform/rag/quality-control/chunk-distribution.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Distribución de Chunks' AND PAGE = 'platform/rag/quality-control/chunk-distribution.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 11. Dashboard de Salud - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard de Salud' AND PAGE = 'platform/rag/monitoring/health-dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard de Salud' AND PAGE = 'platform/rag/monitoring/health-dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard de Salud' AND PAGE = 'platform/rag/monitoring/health-dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard de Salud' AND PAGE = 'platform/rag/monitoring/health-dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 12. Resumen de Métricas - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Métricas' AND PAGE = 'platform/rag/monitoring/metrics-summary.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Métricas' AND PAGE = 'platform/rag/monitoring/metrics-summary.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Métricas' AND PAGE = 'platform/rag/monitoring/metrics-summary.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Métricas' AND PAGE = 'platform/rag/monitoring/metrics-summary.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 13. Uso por Agente - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Uso por Agente' AND PAGE = 'platform/rag/monitoring/usage-by-agent.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Uso por Agente' AND PAGE = 'platform/rag/monitoring/usage-by-agent.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Uso por Agente' AND PAGE = 'platform/rag/monitoring/usage-by-agent.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Uso por Agente' AND PAGE = 'platform/rag/monitoring/usage-by-agent.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 14. Listado de Versiones - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/rag/versioning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/rag/versioning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/rag/versioning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/rag/versioning/overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 15. Gestionar Versión - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Versión' AND PAGE = 'platform/rag/versioning/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Versión' AND PAGE = 'platform/rag/versioning/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Versión' AND PAGE = 'platform/rag/versioning/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Versión' AND PAGE = 'platform/rag/versioning/page.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 16. Overview de Gobierno - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview de Gobierno' AND PAGE = 'gobierno/rag/rag-systems-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview de Gobierno' AND PAGE = 'gobierno/rag/rag-systems-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview de Gobierno' AND PAGE = 'gobierno/rag/rag-systems-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview de Gobierno' AND PAGE = 'gobierno/rag/rag-systems-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 17. Detalle de Gobierno - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Gobierno' AND PAGE = 'gobierno/rag/rag-systems-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Gobierno' AND PAGE = 'gobierno/rag/rag-systems-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Gobierno' AND PAGE = 'gobierno/rag/rag-systems-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Gobierno' AND PAGE = 'gobierno/rag/rag-systems-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- FIN DEL SCRIPT - PERMISOS DE ROLES PARA MENU ITEMS (RAG)
-- =====================================================================
