-- =====================================================================
-- SCRIPT DE POBLACIÓN SSO - PERMISOS DE ROLES PARA MENU ITEMS (SERVING)
-- =====================================================================
-- Fecha: Octubre 29, 2025
-- Versión: 1.0
-- Descripción: Asignación de permisos de roles a menu items del módulo SERVING
-- 
-- Estructura SSOROLESMENU:
--   - IDXSSOROLESMENU: PK autonumérico (no se incluye en INSERT)
--   - IDSSOMENUITEM0: FK al menu item (mediante subconsulta por ITEM + PAGE)
--   - IDSSOROL0: FK al rol (mediante subconsulta por ROL)
-- 
-- Roles simplificados (mapeo directo):
--   Admin → Administracion
--   Manager → Governance Manager
--   Developer → AI Developer
--   Viewer → End User
-- 
-- Total SERVING: 26 menu items con permisos asignados
-- =====================================================================

-- 1. Listado de Despliegues - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues' AND PAGE = 'platform/serving/model-deployment-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues' AND PAGE = 'platform/serving/model-deployment-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues' AND PAGE = 'platform/serving/model-deployment-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Despliegues' AND PAGE = 'platform/serving/model-deployment-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 2. Gestionar Despliegue - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Despliegue' AND PAGE = 'platform/serving/model-deployment-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Despliegue' AND PAGE = 'platform/serving/model-deployment-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Despliegue' AND PAGE = 'platform/serving/model-deployment-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestionar Despliegue' AND PAGE = 'platform/serving/model-deployment-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 3. Estado de Despliegues - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues' AND PAGE = 'platform/serving/deployment-status-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues' AND PAGE = 'platform/serving/deployment-status-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues' AND PAGE = 'platform/serving/deployment-status-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Estado de Despliegues' AND PAGE = 'platform/serving/deployment-status-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 4. Listado de Instancias - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Instancias' AND PAGE = 'platform/serving/deployment-instance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Instancias' AND PAGE = 'platform/serving/deployment-instance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Instancias' AND PAGE = 'platform/serving/deployment-instance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Instancias' AND PAGE = 'platform/serving/deployment-instance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 5. Detalle de Instancia - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Instancia' AND PAGE = 'platform/serving/deployment-instance-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Instancia' AND PAGE = 'platform/serving/deployment-instance-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Instancia' AND PAGE = 'platform/serving/deployment-instance-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Instancia' AND PAGE = 'platform/serving/deployment-instance-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 6. Listado de Modelos - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Modelos' AND PAGE = 'platform/serving/model-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Modelos' AND PAGE = 'platform/serving/model-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Modelos' AND PAGE = 'platform/serving/model-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Modelos' AND PAGE = 'platform/serving/model-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 7. Detalle de Modelo - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Modelo' AND PAGE = 'platform/serving/model-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Modelo' AND PAGE = 'platform/serving/model-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Modelo' AND PAGE = 'platform/serving/model-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Modelo' AND PAGE = 'platform/serving/model-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 8. Listado de Versiones - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/serving/model-version-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/serving/model-version-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/serving/model-version-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Versiones' AND PAGE = 'platform/serving/model-version-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 9. Detalle de Versión - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Versión' AND PAGE = 'platform/serving/model-version-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Versión' AND PAGE = 'platform/serving/model-version-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Versión' AND PAGE = 'platform/serving/model-version-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Versión' AND PAGE = 'platform/serving/model-version-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 10. Listado de Endpoints - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Endpoints' AND PAGE = 'platform/serving/serving-endpoint-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Endpoints' AND PAGE = 'platform/serving/serving-endpoint-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Endpoints' AND PAGE = 'platform/serving/serving-endpoint-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Endpoints' AND PAGE = 'platform/serving/serving-endpoint-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 11. Configurar Endpoint - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Endpoint' AND PAGE = 'platform/serving/serving-endpoint-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Endpoint' AND PAGE = 'platform/serving/serving-endpoint-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Endpoint' AND PAGE = 'platform/serving/serving-endpoint-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Configurar Endpoint' AND PAGE = 'platform/serving/serving-endpoint-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 12. Listado de Métricas - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Métricas' AND PAGE = 'platform/serving/model-metrics-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Métricas' AND PAGE = 'platform/serving/model-metrics-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Métricas' AND PAGE = 'platform/serving/model-metrics-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Métricas' AND PAGE = 'platform/serving/model-metrics-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 13. Detalle de Métricas - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Métricas' AND PAGE = 'platform/serving/model-metrics-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Métricas' AND PAGE = 'platform/serving/model-metrics-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Métricas' AND PAGE = 'platform/serving/model-metrics-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Métricas' AND PAGE = 'platform/serving/model-metrics-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 14. Listado de Métricas Despliegue - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Métricas Despliegue' AND PAGE = 'platform/serving/deployment-metric-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Métricas Despliegue' AND PAGE = 'platform/serving/deployment-metric-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Métricas Despliegue' AND PAGE = 'platform/serving/deployment-metric-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Métricas Despliegue' AND PAGE = 'platform/serving/deployment-metric-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 15. Detalle Métrica Despliegue - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle Métrica Despliegue' AND PAGE = 'platform/serving/deployment-metric-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle Métrica Despliegue' AND PAGE = 'platform/serving/deployment-metric-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle Métrica Despliegue' AND PAGE = 'platform/serving/deployment-metric-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle Métrica Despliegue' AND PAGE = 'platform/serving/deployment-metric-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 16. Listado de Predicciones - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Predicciones' AND PAGE = 'platform/serving/model-prediction-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Predicciones' AND PAGE = 'platform/serving/model-prediction-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Predicciones' AND PAGE = 'platform/serving/model-prediction-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Predicciones' AND PAGE = 'platform/serving/model-prediction-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 17. Detalle de Predicción - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Predicción' AND PAGE = 'platform/serving/model-prediction-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Predicción' AND PAGE = 'platform/serving/model-prediction-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Predicción' AND PAGE = 'platform/serving/model-prediction-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Predicción' AND PAGE = 'platform/serving/model-prediction-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 18. Listado de Requests - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Requests' AND PAGE = 'platform/serving/serving-request-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Requests' AND PAGE = 'platform/serving/serving-request-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Requests' AND PAGE = 'platform/serving/serving-request-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Requests' AND PAGE = 'platform/serving/serving-request-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 19. Detalle de Request - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Request' AND PAGE = 'platform/serving/serving-request-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Request' AND PAGE = 'platform/serving/serving-request-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Request' AND PAGE = 'platform/serving/serving-request-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Request' AND PAGE = 'platform/serving/serving-request-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 20. Listado de Logs - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Logs' AND PAGE = 'platform/serving/deployment-log-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Logs' AND PAGE = 'platform/serving/deployment-log-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Logs' AND PAGE = 'platform/serving/deployment-log-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Logs' AND PAGE = 'platform/serving/deployment-log-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 21. Detalle de Log - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Log' AND PAGE = 'platform/serving/deployment-log-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Log' AND PAGE = 'platform/serving/deployment-log-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Log' AND PAGE = 'platform/serving/deployment-log-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Log' AND PAGE = 'platform/serving/deployment-log-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 22. Análisis de Errores - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores' AND PAGE = 'platform/serving/error-analysis-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores' AND PAGE = 'platform/serving/error-analysis-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores' AND PAGE = 'platform/serving/error-analysis-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis de Errores' AND PAGE = 'platform/serving/error-analysis-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 23. Análisis Detallado Errores - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis Detallado Errores' AND PAGE = 'platform/serving/serving-error-analysis-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis Detallado Errores' AND PAGE = 'platform/serving/serving-error-analysis-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis Detallado Errores' AND PAGE = 'platform/serving/serving-error-analysis-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Análisis Detallado Errores' AND PAGE = 'platform/serving/serving-error-analysis-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 24. SLA Compliance - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'SLA Compliance' AND PAGE = 'platform/serving/sla-compliance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'SLA Compliance' AND PAGE = 'platform/serving/sla-compliance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'SLA Compliance' AND PAGE = 'platform/serving/sla-compliance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'SLA Compliance' AND PAGE = 'platform/serving/sla-compliance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 25. SLA Compliance Detallado - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'SLA Compliance Detallado' AND PAGE = 'platform/serving/serving-sla-compliance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'SLA Compliance Detallado' AND PAGE = 'platform/serving/serving-sla-compliance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'SLA Compliance Detallado' AND PAGE = 'platform/serving/serving-sla-compliance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'SLA Compliance Detallado' AND PAGE = 'platform/serving/serving-sla-compliance-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 26. Desglose de Costos - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Desglose de Costos' AND PAGE = 'platform/serving/serving-cost-breakdown-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Desglose de Costos' AND PAGE = 'platform/serving/serving-cost-breakdown-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Desglose de Costos' AND PAGE = 'platform/serving/serving-cost-breakdown-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Desglose de Costos' AND PAGE = 'platform/serving/serving-cost-breakdown-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- FIN DEL SCRIPT - PERMISOS DE ROLES PARA MENU ITEMS (SERVING)
-- =====================================================================
