-- =====================================================================
-- SCRIPT DE POBLACIÓN SSO - PERMISOS DE ROLES PARA MENU ITEMS (CORE)
-- =====================================================================
-- Fecha: Octubre 29, 2025
-- Versión: 1.0
-- Descripción: Asignación de permisos de roles a menu items del módulo CORE
-- 
-- Estructura SSOROLESMENU:
--   - IDXSSOROLESMENU: PK autonumérico (no se incluye en INSERT)
--   - IDSSOMENUITEM0: FK al menu item (mediante subconsulta por ITEM + PAGE)
--   - IDSSOROL0: FK al rol (mediante subconsulta por ROL)
-- 
-- Roles simplificados (mapeo directo):
--   Admin → Administracion
--   Manager → Governance Manager
--   Developer → AI Developer
--   Viewer → End User
-- 
-- Total CORE: 29 menu items con permisos asignados
-- =====================================================================

-- 1. Dashboard Admin - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Admin' AND PAGE = 'gobierno/core/admin-dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Admin' AND PAGE = 'gobierno/core/admin-dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Admin' AND PAGE = 'gobierno/core/admin-dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Dashboard Admin' AND PAGE = 'gobierno/core/admin-dashboard.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 2. Resumen Dashboard - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen Dashboard' AND PAGE = 'platform/core/admin-dashboard-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen Dashboard' AND PAGE = 'platform/core/admin-dashboard-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen Dashboard' AND PAGE = 'platform/core/admin-dashboard-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen Dashboard' AND PAGE = 'platform/core/admin-dashboard-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 3. Listado de Usuarios (Gobierno) - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Usuarios (Gobierno)' AND PAGE = 'gobierno/core/users.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Usuarios (Gobierno)' AND PAGE = 'gobierno/core/users.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Usuarios (Gobierno)' AND PAGE = 'gobierno/core/users.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Usuarios (Gobierno)' AND PAGE = 'gobierno/core/users.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 4. Listado de Usuarios - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Usuarios' AND PAGE = 'platform/core/user-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Usuarios' AND PAGE = 'platform/core/user-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Usuarios' AND PAGE = 'platform/core/user-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Usuarios' AND PAGE = 'platform/core/user-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 5. Detalle de Usuario - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Usuario' AND PAGE = 'platform/core/user-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Usuario' AND PAGE = 'platform/core/user-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Usuario' AND PAGE = 'platform/core/user-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Usuario' AND PAGE = 'platform/core/user-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 6. Gestión de Roles (Gobierno) - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Roles (Gobierno)' AND PAGE = 'gobierno/core/roles.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Roles (Gobierno)' AND PAGE = 'gobierno/core/roles.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Roles (Gobierno)' AND PAGE = 'gobierno/core/roles.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Roles (Gobierno)' AND PAGE = 'gobierno/core/roles.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 7. Listado de Roles - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Roles' AND PAGE = 'platform/core/role-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Roles' AND PAGE = 'platform/core/role-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Roles' AND PAGE = 'platform/core/role-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Roles' AND PAGE = 'platform/core/role-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 8. Detalle de Rol - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Rol' AND PAGE = 'platform/core/role-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Rol' AND PAGE = 'platform/core/role-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Rol' AND PAGE = 'platform/core/role-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Rol' AND PAGE = 'platform/core/role-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 9. Gestión de Permisos (Gobierno) - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Permisos (Gobierno)' AND PAGE = 'gobierno/core/permissions.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Permisos (Gobierno)' AND PAGE = 'gobierno/core/permissions.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Permisos (Gobierno)' AND PAGE = 'gobierno/core/permissions.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Permisos (Gobierno)' AND PAGE = 'gobierno/core/permissions.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 10. Listado de Permisos - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Permisos' AND PAGE = 'platform/core/permission-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Permisos' AND PAGE = 'platform/core/permission-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Permisos' AND PAGE = 'platform/core/permission-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Permisos' AND PAGE = 'platform/core/permission-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 11. Detalle de Permiso - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Permiso' AND PAGE = 'platform/core/permission-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Permiso' AND PAGE = 'platform/core/permission-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Permiso' AND PAGE = 'platform/core/permission-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Permiso' AND PAGE = 'platform/core/permission-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 12. Gestión de Departamentos (Gobierno) - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Departamentos (Gobierno)' AND PAGE = 'gobierno/core/departments.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Departamentos (Gobierno)' AND PAGE = 'gobierno/core/departments.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Departamentos (Gobierno)' AND PAGE = 'gobierno/core/departments.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Departamentos (Gobierno)' AND PAGE = 'gobierno/core/departments.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 13. Listado de Departamentos - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Departamentos' AND PAGE = 'platform/core/department-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Departamentos' AND PAGE = 'platform/core/department-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Departamentos' AND PAGE = 'platform/core/department-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Departamentos' AND PAGE = 'platform/core/department-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 14. Detalle de Departamento - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Departamento' AND PAGE = 'platform/core/department-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Departamento' AND PAGE = 'platform/core/department-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Departamento' AND PAGE = 'platform/core/department-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Departamento' AND PAGE = 'platform/core/department-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 15. Gestión de Menús (Gobierno) - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Menús (Gobierno)' AND PAGE = 'gobierno/core/menus.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Menús (Gobierno)' AND PAGE = 'gobierno/core/menus.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Menús (Gobierno)' AND PAGE = 'gobierno/core/menus.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Gestión de Menús (Gobierno)' AND PAGE = 'gobierno/core/menus.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 16. Listado de Menús - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Menús' AND PAGE = 'platform/core/menu-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Menús' AND PAGE = 'platform/core/menu-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Menús' AND PAGE = 'platform/core/menu-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Menús' AND PAGE = 'platform/core/menu-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 17. Detalle de Menú - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Menú' AND PAGE = 'platform/core/menu-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Menú' AND PAGE = 'platform/core/menu-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Menú' AND PAGE = 'platform/core/menu-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Menú' AND PAGE = 'platform/core/menu-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 18. Auditoría de Seguridad (Gobierno) - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Auditoría de Seguridad (Gobierno)' AND PAGE = 'gobierno/core/security-audit.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Auditoría de Seguridad (Gobierno)' AND PAGE = 'gobierno/core/security-audit.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Auditoría de Seguridad (Gobierno)' AND PAGE = 'gobierno/core/security-audit.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Auditoría de Seguridad (Gobierno)' AND PAGE = 'gobierno/core/security-audit.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 19. Resumen de Auditoría - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Auditoría' AND PAGE = 'platform/core/security-audit-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Auditoría' AND PAGE = 'platform/core/security-audit-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Auditoría' AND PAGE = 'platform/core/security-audit-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Auditoría' AND PAGE = 'platform/core/security-audit-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 20. Intentos de Login (Gobierno) - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Intentos de Login (Gobierno)' AND PAGE = 'gobierno/core/login-attempts.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Intentos de Login (Gobierno)' AND PAGE = 'gobierno/core/login-attempts.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Intentos de Login (Gobierno)' AND PAGE = 'gobierno/core/login-attempts.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Intentos de Login (Gobierno)' AND PAGE = 'gobierno/core/login-attempts.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 21. Listado de Intentos - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Intentos' AND PAGE = 'platform/core/login-attempt-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Intentos' AND PAGE = 'platform/core/login-attempt-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Intentos' AND PAGE = 'platform/core/login-attempt-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Intentos' AND PAGE = 'platform/core/login-attempt-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 22. Detalle de Intento - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Intento' AND PAGE = 'platform/core/login-attempt-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Intento' AND PAGE = 'platform/core/login-attempt-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Intento' AND PAGE = 'platform/core/login-attempt-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Intento' AND PAGE = 'platform/core/login-attempt-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 23. Sesiones de Usuario (Gobierno) - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Sesiones de Usuario (Gobierno)' AND PAGE = 'gobierno/core/user-sessions.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Sesiones de Usuario (Gobierno)' AND PAGE = 'gobierno/core/user-sessions.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Sesiones de Usuario (Gobierno)' AND PAGE = 'gobierno/core/user-sessions.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Sesiones de Usuario (Gobierno)' AND PAGE = 'gobierno/core/user-sessions.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 24. Listado de Sesiones - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Sesiones' AND PAGE = 'platform/core/user-session-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Sesiones' AND PAGE = 'platform/core/user-session-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Sesiones' AND PAGE = 'platform/core/user-session-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Listado de Sesiones' AND PAGE = 'platform/core/user-session-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 25. Detalle de Sesión - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Sesión' AND PAGE = 'platform/core/user-session-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Sesión' AND PAGE = 'platform/core/user-session-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Sesión' AND PAGE = 'platform/core/user-session-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Detalle de Sesión' AND PAGE = 'platform/core/user-session-detail.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 26. Actividad de Usuario (Gobierno) - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Actividad de Usuario (Gobierno)' AND PAGE = 'gobierno/core/user-activity.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Actividad de Usuario (Gobierno)' AND PAGE = 'gobierno/core/user-activity.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Actividad de Usuario (Gobierno)' AND PAGE = 'gobierno/core/user-activity.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Actividad de Usuario (Gobierno)' AND PAGE = 'gobierno/core/user-activity.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 27. Resumen de Actividad - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Actividad' AND PAGE = 'platform/core/user-activity-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Actividad' AND PAGE = 'platform/core/user-activity-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Actividad' AND PAGE = 'platform/core/user-activity-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Resumen de Actividad' AND PAGE = 'platform/core/user-activity-summary-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 28. Salud del Sistema (Gobierno) - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Salud del Sistema (Gobierno)' AND PAGE = 'gobierno/core/system-health.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Salud del Sistema (Gobierno)' AND PAGE = 'gobierno/core/system-health.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Salud del Sistema (Gobierno)' AND PAGE = 'gobierno/core/system-health.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Salud del Sistema (Gobierno)' AND PAGE = 'gobierno/core/system-health.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);


-- 29. Overview de Salud - Admin, Manager, Developer, Viewer
INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview de Salud' AND PAGE = 'platform/core/system-health-overview-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Administracion' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview de Salud' AND PAGE = 'platform/core/system-health-overview-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'Governance Manager' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview de Salud' AND PAGE = 'platform/core/system-health-overview-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'AI Developer' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

INSERT INTO SSOROLESMENU (IDSSOMENUITEM0, IDSSOROL0)
VALUES (
  (SELECT IDXSSOMENUITEM FROM SSOMENUITEM WHERE ITEM = 'Overview de Salud' AND PAGE = 'platform/core/system-health-overview-overview.zul' LIMIT 1),
  (SELECT IDXSSOROL FROM SSOROL WHERE ROL = 'End User' AND (BAJA IS NULL OR BAJA > CURRENT_DATE) LIMIT 1)
);

-- =====================================================================
-- FIN DEL SCRIPT - PERMISOS DE ROLES PARA MENU ITEMS (CORE)
-- =====================================================================
