-- ============================================================================
-- CodeFlowX Govern Platform - SQL Scripts
-- Generado automáticamente desde JSONs EnArt
-- Fecha: 2025-10-14 12:27:14
-- Total tablas: 161
-- ============================================================================

-- IMPORTANTE: Este script elimina TODAS las tablas
-- Usar con precaución en producción

-- ============================================================================
-- MÓDULO: AGENTS
-- ============================================================================

DROP TABLE IF EXISTS AGTAGENTALERTS CASCADE;
DROP TABLE IF EXISTS AGTAGENTAPPROVALS CASCADE;
DROP TABLE IF EXISTS AGTAGENTBIASDETECTIONS CASCADE;
DROP TABLE IF EXISTS AGTAGENTCOLLABORATIONS CASCADE;
DROP TABLE IF EXISTS AGTAGENTCOMMUNICATIONS CASCADE;
DROP TABLE IF EXISTS AGTAGENTCOMPLIANCE CASCADE;
DROP TABLE IF EXISTS AGTAGENTDECISIONS CASCADE;
DROP TABLE IF EXISTS AGTAGENTDEPLOYMENTS CASCADE;
DROP TABLE IF EXISTS AGTAGENTDOMAINS CASCADE;
DROP TABLE IF EXISTS AGTAGENTETHICSASSESSMENTS CASCADE;
DROP TABLE IF EXISTS AGTAGENTEXPERTISE CASCADE;
DROP TABLE IF EXISTS AGTAGENTGOVERNANCE CASCADE;
DROP TABLE IF EXISTS AGTAGENTHEALTH CASCADE;
DROP TABLE IF EXISTS AGTAGENTINTERACTIONS CASCADE;
DROP TABLE IF EXISTS AGTAGENTMONITORING CASCADE;
DROP TABLE IF EXISTS AGTAGENTROLLBACKS CASCADE;
DROP TABLE IF EXISTS AGTAGENTS CASCADE;
DROP TABLE IF EXISTS AGTAGENTTOOLS CASCADE;
DROP TABLE IF EXISTS AGTAGENTTRANSPARENCY CASCADE;
DROP TABLE IF EXISTS AGTAGENTVERSIONS CASCADE;
DROP TABLE IF EXISTS AGTAGENTWORKFLOWS CASCADE;
DROP TABLE IF EXISTS AGTWORKFLOWEXECUTIONS CASCADE;

-- ============================================================================
-- MÓDULO: ANALYTICS
-- ============================================================================

DROP TABLE IF EXISTS ANLANALYTICSMETRICS CASCADE;
DROP TABLE IF EXISTS ANLANALYTICSREPORTS CASCADE;

-- ============================================================================
-- MÓDULO: ARTEFACTO
-- ============================================================================

DROP TABLE IF EXISTS CATARTIFACTDEPENDENCIES CASCADE;
DROP TABLE IF EXISTS CATARTIFACTVERSIONS CASCADE;
DROP TABLE IF EXISTS CATBASEARTIFACTS CASCADE;

-- ============================================================================
-- MÓDULO: CORE
-- ============================================================================

DROP TABLE IF EXISTS CORDEPARTMENTS CASCADE;
DROP TABLE IF EXISTS CORLOGINATTEMPTS CASCADE;
DROP TABLE IF EXISTS CORMENUS CASCADE;
DROP TABLE IF EXISTS CORPERMISSIONS CASCADE;
DROP TABLE IF EXISTS CORROLES CASCADE;
DROP TABLE IF EXISTS CORUSERS CASCADE;
DROP TABLE IF EXISTS CORUSERSESSIONS CASCADE;

-- ============================================================================
-- MÓDULO: DASHBOARD
-- ============================================================================

DROP TABLE IF EXISTS DSHCOSTMETRICS CASCADE;
DROP TABLE IF EXISTS DSHDISTRIBUTIONS CASCADE;
DROP TABLE IF EXISTS DSHMODULEACTIVITY CASCADE;
DROP TABLE IF EXISTS DSHMODULESTATS CASCADE;
DROP TABLE IF EXISTS DSHQUICKACTIONS CASCADE;
DROP TABLE IF EXISTS DSHTIMESERIES CASCADE;
DROP TABLE IF EXISTS DSHTOKENMETRICS CASCADE;

-- ============================================================================
-- MÓDULO: EVALUATION
-- ============================================================================

DROP TABLE IF EXISTS GOVBIASANALYSIS CASCADE;
DROP TABLE IF EXISTS GOVBIASDETECTIONS CASCADE;
DROP TABLE IF EXISTS GOVBIASRECOMMENDATIONS CASCADE;
DROP TABLE IF EXISTS GOVEVALUATIONMETRICS CASCADE;
DROP TABLE IF EXISTS GOVFAIRNESSMETRICS CASCADE;
DROP TABLE IF EXISTS GOVMODELEVALUATIONS CASCADE;
DROP TABLE IF EXISTS MODMODELBIASANALYSES CASCADE;
DROP TABLE IF EXISTS MODMODELPERFORMANCES CASCADE;

-- ============================================================================
-- MÓDULO: GOVERNANCE
-- ============================================================================

DROP TABLE IF EXISTS GOVCOMPLIANCEASSESSMENTS CASCADE;
DROP TABLE IF EXISTS GOVCOMPLIANCEFINDINGS CASCADE;
DROP TABLE IF EXISTS GOVCOMPLIANCEREQUIREMENTS CASCADE;
DROP TABLE IF EXISTS GOVGOVERNANCEMETRICS CASCADE;
DROP TABLE IF EXISTS GOVPOLICIES CASCADE;
DROP TABLE IF EXISTS GOVPOLICYAUDITLOGS CASCADE;
DROP TABLE IF EXISTS GOVPOLICYCHECKLISTITEMS CASCADE;
DROP TABLE IF EXISTS GOVPOLICYEVALUATIONS CASCADE;
DROP TABLE IF EXISTS GOVPOLICYRULES CASCADE;
DROP TABLE IF EXISTS GOVPOLICYVALIDATIONCONFIGS CASCADE;
DROP TABLE IF EXISTS GOVPOLICYVIOLATIONS CASCADE;
DROP TABLE IF EXISTS GOVSECURITYMETRICS CASCADE;
DROP TABLE IF EXISTS GOVSECURITYPOLICIES CASCADE;
DROP TABLE IF EXISTS GOVSECURITYTHREATS CASCADE;

-- ============================================================================
-- MÓDULO: INFRASTRUCTURE
-- ============================================================================

DROP TABLE IF EXISTS INFAUDITS CASCADE;
DROP TABLE IF EXISTS INFCLOUDPROVIDERS CASCADE;
DROP TABLE IF EXISTS INFCLOUDREGIONS CASCADE;
DROP TABLE IF EXISTS INFCLOUDRESOURCES CASCADE;
DROP TABLE IF EXISTS INFCOSTS CASCADE;
DROP TABLE IF EXISTS INFCREDENTIALS CASCADE;
DROP TABLE IF EXISTS INFGPUINSTANCES CASCADE;
DROP TABLE IF EXISTS INFK8SNODES CASCADE;
DROP TABLE IF EXISTS INFKUBERNETESCLUSTERS CASCADE;
DROP TABLE IF EXISTS INFMETRICS CASCADE;
DROP TABLE IF EXISTS INFRESOURCEQUOTAS CASCADE;
DROP TABLE IF EXISTS INFTEMPLATES CASCADE;

-- ============================================================================
-- MÓDULO: MODELS
-- ============================================================================

DROP TABLE IF EXISTS MODCAPABILITIES CASCADE;
DROP TABLE IF EXISTS MODCATALOG CASCADE;
DROP TABLE IF EXISTS MODENDPOINTS CASCADE;
DROP TABLE IF EXISTS MODMODELARTIFACTS CASCADE;
DROP TABLE IF EXISTS MODMODELCOMPARISONS CASCADE;
DROP TABLE IF EXISTS MODMODELDEPENDENCIES CASCADE;
DROP TABLE IF EXISTS MODMODELS CASCADE;
DROP TABLE IF EXISTS MODMODELSTAGETRANSITIONS CASCADE;
DROP TABLE IF EXISTS MODMODELVALIDATIONS CASCADE;
DROP TABLE IF EXISTS MODMODELVERSIONS CASCADE;
DROP TABLE IF EXISTS MODPROVIDERCREDENTIALS CASCADE;
DROP TABLE IF EXISTS MODPROVIDERS CASCADE;
DROP TABLE IF EXISTS MODRECOMMENDATIONS CASCADE;
DROP TABLE IF EXISTS MODUSAGE CASCADE;

-- ============================================================================
-- MÓDULO: MONITORING
-- ============================================================================

DROP TABLE IF EXISTS AUDITLOGS CASCADE;
DROP TABLE IF EXISTS GOVSYSTEMALERTS CASCADE;
DROP TABLE IF EXISTS GOVSYSTEMHEALTH CASCADE;
DROP TABLE IF EXISTS GOVSYSTEMMETRICS CASCADE;
DROP TABLE IF EXISTS MONMONITORINGALERTS CASCADE;
DROP TABLE IF EXISTS MONMONITORINGMETRICS CASCADE;

-- ============================================================================
-- MÓDULO: NOTIFICATIONS
-- ============================================================================

DROP TABLE IF EXISTS NTFCHANNELS CASCADE;
DROP TABLE IF EXISTS NTFLOGS CASCADE;
DROP TABLE IF EXISTS NTFNOTIFICATIONS CASCADE;
DROP TABLE IF EXISTS NTFPREFERENCES CASCADE;
DROP TABLE IF EXISTS NTFTEMPLATES CASCADE;

-- ============================================================================
-- MÓDULO: PLATFORM
-- ============================================================================

DROP TABLE IF EXISTS GOVRISKINDICATORS CASCADE;
DROP TABLE IF EXISTS PLATFORMLICENSES CASCADE;
DROP TABLE IF EXISTS PLATFORMNODES CASCADE;
DROP TABLE IF EXISTS PLATFORMUPDATES CASCADE;
DROP TABLE IF EXISTS UPDATEINSTALLATIONS CASCADE;
DROP TABLE IF EXISTS UPDATESCHEDULES CASCADE;

-- ============================================================================
-- MÓDULO: PROJECTS
-- ============================================================================

DROP TABLE IF EXISTS GOVPROJECTARTIFACTS CASCADE;
DROP TABLE IF EXISTS GOVPROJECTMEMBERS CASCADE;
DROP TABLE IF EXISTS PRJBILLINGDETAILS CASCADE;
DROP TABLE IF EXISTS PRJCOSTESTIMATORS CASCADE;
DROP TABLE IF EXISTS PRJINVOICES CASCADE;
DROP TABLE IF EXISTS PRJPROJECTDOCUMENTS CASCADE;
DROP TABLE IF EXISTS PRJPROJECTDOMAINS CASCADE;
DROP TABLE IF EXISTS PRJPROJECTLICENSES CASCADE;
DROP TABLE IF EXISTS PRJPROJECTREQUIREMENTS CASCADE;
DROP TABLE IF EXISTS PRJPROJECTS CASCADE;
DROP TABLE IF EXISTS PRJPROJECTSTACKS CASCADE;
DROP TABLE IF EXISTS PRJPROJECTTASKS CASCADE;
DROP TABLE IF EXISTS PRJPROJECTTECHNOLOGIES CASCADE;
DROP TABLE IF EXISTS PRJPROJECTTIMETRACKING CASCADE;
DROP TABLE IF EXISTS PRJPROJECTTOKENS CASCADE;
DROP TABLE IF EXISTS PRJPROJECTVERSIONS CASCADE;
DROP TABLE IF EXISTS PRJRESOURCECONSUMPTION CASCADE;
DROP TABLE IF EXISTS PRJROIANALYSIS CASCADE;

-- ============================================================================
-- MÓDULO: PROMPTS
-- ============================================================================

DROP TABLE IF EXISTS PRMPROMPTS CASCADE;
DROP TABLE IF EXISTS PRMPROMPTVALIDATIONS CASCADE;
DROP TABLE IF EXISTS PRMPROMPTVERSIONS CASCADE;

-- ============================================================================
-- MÓDULO: RAG
-- ============================================================================

DROP TABLE IF EXISTS RAGRAGDATASOURCES CASCADE;
DROP TABLE IF EXISTS RAGRAGSYSTEMS CASCADE;
DROP TABLE IF EXISTS RAGRAGVERSIONS CASCADE;

-- ============================================================================
-- MÓDULO: SERVING
-- ============================================================================

DROP TABLE IF EXISTS SRVDEPLOYMENTINSTANCES CASCADE;
DROP TABLE IF EXISTS SRVDEPLOYMENTLOGS CASCADE;
DROP TABLE IF EXISTS SRVDEPLOYMENTMETRICS CASCADE;
DROP TABLE IF EXISTS SRVDEPLOYMENTS CASCADE;
DROP TABLE IF EXISTS SRVMODELMETRICS CASCADE;
DROP TABLE IF EXISTS SRVMODELS CASCADE;
DROP TABLE IF EXISTS SRVMODELVERSIONS CASCADE;
DROP TABLE IF EXISTS SRVPREDICTIONS CASCADE;
DROP TABLE IF EXISTS SRVSERVINGENDPOINTS CASCADE;
DROP TABLE IF EXISTS SRVSERVINGREQUESTS CASCADE;

-- ============================================================================
-- MÓDULO: TRAINING
-- ============================================================================

DROP TABLE IF EXISTS TRNCHECKPOINTS CASCADE;
DROP TABLE IF EXISTS TRNDATASETSOURCES CASCADE;
DROP TABLE IF EXISTS TRNENVIRONMENTS CASCADE;
DROP TABLE IF EXISTS TRNEXPERIMENTLINEAGE CASCADE;
DROP TABLE IF EXISTS TRNEXPERIMENTS CASCADE;
DROP TABLE IF EXISTS TRNEXPERIMENTTEMPLATES CASCADE;
DROP TABLE IF EXISTS TRNHPOEXPERIMENTS CASCADE;
DROP TABLE IF EXISTS TRNHPOTRIALS CASCADE;
DROP TABLE IF EXISTS TRNMETRICSERIES CASCADE;
DROP TABLE IF EXISTS TRNMETRICSTREAMS CASCADE;
DROP TABLE IF EXISTS TRNPARAMS CASCADE;
DROP TABLE IF EXISTS TRNRUNCOMPARISONS CASCADE;
DROP TABLE IF EXISTS TRNRUNS CASCADE;
DROP TABLE IF EXISTS TRNTAGS CASCADE;
DROP TABLE IF EXISTS TRNTRAININGALERTS CASCADE;
DROP TABLE IF EXISTS TRNTRAININGARTIFACTS CASCADE;
DROP TABLE IF EXISTS TRNTRAININGEXECUTIONS CASCADE;
DROP TABLE IF EXISTS TRNTRAININGGOVERNANCE CASCADE;
DROP TABLE IF EXISTS TRNTRAININGINFRASTRUCTURE CASCADE;
DROP TABLE IF EXISTS TRNTRAININGLOGS CASCADE;
DROP TABLE IF EXISTS TRNTRAININGMETRICS CASCADE;

