-- ============================================================================
-- CodeFlowX Govern Platform - SQL Scripts
-- Generado automáticamente desde JSONs EnArt
-- Fecha: 2025-10-14 12:27:14
-- Total tablas: 161
-- ============================================================================

-- Foreign Keys para integridad referencial
-- IMPORTANTE: Ejecutar después de crear todas las tablas

-- FK: AGTAGENTALERTS → AGTAGENTS
ALTER TABLE AGTAGENTALERTS
    ADD CONSTRAINT SYS_9ec0df29b8_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTAPPROVALS → AGTAGENTS
ALTER TABLE AGTAGENTAPPROVALS
    ADD CONSTRAINT SYS_1e70065daa_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTBIASDETECTIONS → AGTAGENTS
ALTER TABLE AGTAGENTBIASDETECTIONS
    ADD CONSTRAINT SYS_22cf8358ea_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTCOLLABORATIONS → AGTAGENTS
ALTER TABLE AGTAGENTCOLLABORATIONS
    ADD CONSTRAINT SYS_874b678180_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTCOLLABORATIONS → AGTAGENTS
ALTER TABLE AGTAGENTCOLLABORATIONS
    ADD CONSTRAINT SYS_874b678180_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTCOMMUNICATIONS → AGTAGENTS
ALTER TABLE AGTAGENTCOMMUNICATIONS
    ADD CONSTRAINT SYS_e19c20c88d_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTCOMMUNICATIONS → AGTAGENTS
ALTER TABLE AGTAGENTCOMMUNICATIONS
    ADD CONSTRAINT SYS_e19c20c88d_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTCOMPLIANCE → AGTAGENTS
ALTER TABLE AGTAGENTCOMPLIANCE
    ADD CONSTRAINT SYS_d1f4b2f775_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTDECISIONS → AGTAGENTS
ALTER TABLE AGTAGENTDECISIONS
    ADD CONSTRAINT SYS_0fa6e57fa5_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTDEPLOYMENTS → AGTAGENTS
ALTER TABLE AGTAGENTDEPLOYMENTS
    ADD CONSTRAINT SYS_ce54023c26_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTETHICSASSESSMENTS → AGTAGENTS
ALTER TABLE AGTAGENTETHICSASSESSMENTS
    ADD CONSTRAINT SYS_9b0928fc02_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTEXPERTISE → AGTAGENTS
ALTER TABLE AGTAGENTEXPERTISE
    ADD CONSTRAINT SYS_8eada6f016_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTEXPERTISE → AGTAGENTDOMAINS
ALTER TABLE AGTAGENTEXPERTISE
    ADD CONSTRAINT SYS_9236e12b13_FK
    FOREIGN KEY (IDAGTAGENTDOMAINS0)
    REFERENCES AGTAGENTDOMAINS(IDXAGENTDOMAIN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTGOVERNANCE → AGTAGENTS
ALTER TABLE AGTAGENTGOVERNANCE
    ADD CONSTRAINT SYS_3bcffdac91_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTHEALTH → AGTAGENTS
ALTER TABLE AGTAGENTHEALTH
    ADD CONSTRAINT SYS_624ec17255_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTINTERACTIONS → AGTAGENTS
ALTER TABLE AGTAGENTINTERACTIONS
    ADD CONSTRAINT SYS_d79dc9c9be_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTMONITORING → AGTAGENTS
ALTER TABLE AGTAGENTMONITORING
    ADD CONSTRAINT SYS_9ba8fae507_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTROLLBACKS → AGTAGENTS
ALTER TABLE AGTAGENTROLLBACKS
    ADD CONSTRAINT SYS_42de1a28f0_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTROLLBACKS → AGTAGENTDEPLOYMENTS
ALTER TABLE AGTAGENTROLLBACKS
    ADD CONSTRAINT SYS_33b6e607fc_FK
    FOREIGN KEY (IDAGTAGENTDEPLOYMENTS0)
    REFERENCES AGTAGENTDEPLOYMENTS(IDXAGENTDEPLOYMENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTTOOLS → AGTAGENTS
ALTER TABLE AGTAGENTTOOLS
    ADD CONSTRAINT SYS_3e421ec7f9_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTTRANSPARENCY → AGTAGENTS
ALTER TABLE AGTAGENTTRANSPARENCY
    ADD CONSTRAINT SYS_2005326659_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTAGENTVERSIONS → AGTAGENTS
ALTER TABLE AGTAGENTVERSIONS
    ADD CONSTRAINT SYS_e7b4930b0d_FK
    FOREIGN KEY (IDAGTAGENTS0)
    REFERENCES AGTAGENTS(IDXAGENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AGTWORKFLOWEXECUTIONS → AGTAGENTWORKFLOWS
ALTER TABLE AGTWORKFLOWEXECUTIONS
    ADD CONSTRAINT SYS_7480fac3e4_FK
    FOREIGN KEY (IDAGTAGENTWORKFLOWS0)
    REFERENCES AGTAGENTWORKFLOWS(IDXAGENTWORKFLOW)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: AUDITLOGS → CORUSERS
ALTER TABLE AUDITLOGS
    ADD CONSTRAINT SYS_5a6c006a44_FK
    FOREIGN KEY (IDCORUSERS0)
    REFERENCES CORUSERS(IDXUSER)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: CATARTIFACTDEPENDENCIES → CATBASEARTIFACTS
ALTER TABLE CATARTIFACTDEPENDENCIES
    ADD CONSTRAINT SYS_1f52728c8e_FK
    FOREIGN KEY (IDCATBASEARTIFACTS0)
    REFERENCES CATBASEARTIFACTS(IDXBASEARTIFACT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: CATARTIFACTDEPENDENCIES → CATBASEARTIFACTS
ALTER TABLE CATARTIFACTDEPENDENCIES
    ADD CONSTRAINT SYS_1f52728c8e_FK
    FOREIGN KEY (IDCATBASEARTIFACTS0)
    REFERENCES CATBASEARTIFACTS(IDXBASEARTIFACT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: CATARTIFACTVERSIONS → CATBASEARTIFACTS
ALTER TABLE CATARTIFACTVERSIONS
    ADD CONSTRAINT SYS_1660b36dfb_FK
    FOREIGN KEY (IDCATBASEARTIFACTS0)
    REFERENCES CATBASEARTIFACTS(IDXBASEARTIFACT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: CORUSERS → CORDEPARTMENTS
ALTER TABLE CORUSERS
    ADD CONSTRAINT SYS_83af1db353_FK
    FOREIGN KEY (IDCORDEPARTMENTS0)
    REFERENCES CORDEPARTMENTS(IDXDEPARTMENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: CORUSERSESSIONS → CORUSERS
ALTER TABLE CORUSERSESSIONS
    ADD CONSTRAINT SYS_96a0d2a6d6_FK
    FOREIGN KEY (IDCORUSERS0)
    REFERENCES CORUSERS(IDXUSER)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVBIASDETECTIONS → GOVBIASANALYSIS
ALTER TABLE GOVBIASDETECTIONS
    ADD CONSTRAINT SYS_d05d22adad_FK
    FOREIGN KEY (IDGOVBIASANALYSIS0)
    REFERENCES GOVBIASANALYSIS(IDXBIASANALYSIS)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVBIASRECOMMENDATIONS → GOVBIASANALYSIS
ALTER TABLE GOVBIASRECOMMENDATIONS
    ADD CONSTRAINT SYS_281259737b_FK
    FOREIGN KEY (IDGOVBIASANALYSIS0)
    REFERENCES GOVBIASANALYSIS(IDXBIASANALYSIS)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVCOMPLIANCEFINDINGS → GOVCOMPLIANCEASSESSMENTS
ALTER TABLE GOVCOMPLIANCEFINDINGS
    ADD CONSTRAINT SYS_41abe568bf_FK
    FOREIGN KEY (IDGOVCOMPLIANCEASSESSMENTS0)
    REFERENCES GOVCOMPLIANCEASSESSMENTS(IDXCOMPLIANCEASSESSMENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVCOMPLIANCEREQUIREMENTS → GOVCOMPLIANCEASSESSMENTS
ALTER TABLE GOVCOMPLIANCEREQUIREMENTS
    ADD CONSTRAINT SYS_a3aa4d0c8f_FK
    FOREIGN KEY (IDGOVCOMPLIANCEASSESSMENTS0)
    REFERENCES GOVCOMPLIANCEASSESSMENTS(IDXCOMPLIANCEASSESSMENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVEVALUATIONMETRICS → GOVMODELEVALUATIONS
ALTER TABLE GOVEVALUATIONMETRICS
    ADD CONSTRAINT SYS_c4ea46695d_FK
    FOREIGN KEY (IDGOVMODELEVALUATIONS0)
    REFERENCES GOVMODELEVALUATIONS(IDXMODELEVALUATION)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVFAIRNESSMETRICS → GOVBIASANALYSIS
ALTER TABLE GOVFAIRNESSMETRICS
    ADD CONSTRAINT SYS_ec1734e8ae_FK
    FOREIGN KEY (IDGOVBIASANALYSIS0)
    REFERENCES GOVBIASANALYSIS(IDXBIASANALYSIS)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVPOLICYAUDITLOGS → GOVPOLICIES
ALTER TABLE GOVPOLICYAUDITLOGS
    ADD CONSTRAINT SYS_a8f2935918_FK
    FOREIGN KEY (IDGOVPOLICIES0)
    REFERENCES GOVPOLICIES(IDXPOLICY)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVPOLICYCHECKLISTITEMS → GOVPOLICIES
ALTER TABLE GOVPOLICYCHECKLISTITEMS
    ADD CONSTRAINT SYS_167f3e0b02_FK
    FOREIGN KEY (IDGOVPOLICIES0)
    REFERENCES GOVPOLICIES(IDXPOLICY)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVPOLICYEVALUATIONS → GOVPOLICIES
ALTER TABLE GOVPOLICYEVALUATIONS
    ADD CONSTRAINT SYS_80c7432f2b_FK
    FOREIGN KEY (IDGOVPOLICIES0)
    REFERENCES GOVPOLICIES(IDXPOLICY)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVPOLICYRULES → GOVPOLICIES
ALTER TABLE GOVPOLICYRULES
    ADD CONSTRAINT SYS_172a2c89d3_FK
    FOREIGN KEY (IDGOVPOLICIES0)
    REFERENCES GOVPOLICIES(IDXPOLICY)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVPROJECTARTIFACTS → PRJPROJECTS
ALTER TABLE GOVPROJECTARTIFACTS
    ADD CONSTRAINT SYS_74d646e34f_FK
    FOREIGN KEY (IDPRJPROJECTS0)
    REFERENCES PRJPROJECTS(IDXPROJECT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: GOVPROJECTMEMBERS → PRJPROJECTS
ALTER TABLE GOVPROJECTMEMBERS
    ADD CONSTRAINT SYS_c39dccf2d8_FK
    FOREIGN KEY (IDPRJPROJECTS0)
    REFERENCES PRJPROJECTS(IDXPROJECT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODCAPABILITIES → MODCATALOG
ALTER TABLE MODCAPABILITIES
    ADD CONSTRAINT SYS_df087b3e3e_FK
    FOREIGN KEY (IDMODCATALOG0)
    REFERENCES MODCATALOG(IDXMODELCATALOG)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODCATALOG → MODPROVIDERS
ALTER TABLE MODCATALOG
    ADD CONSTRAINT SYS_cdf293fbae_FK
    FOREIGN KEY (IDMODPROVIDERS0)
    REFERENCES MODPROVIDERS(IDXMODELPROVIDER)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODENDPOINTS → MODCATALOG
ALTER TABLE MODENDPOINTS
    ADD CONSTRAINT SYS_bd1cf556a7_FK
    FOREIGN KEY (IDMODCATALOG0)
    REFERENCES MODCATALOG(IDXMODELCATALOG)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODMODELARTIFACTS → MODMODELS
ALTER TABLE MODMODELARTIFACTS
    ADD CONSTRAINT SYS_5b4c83ccfe_FK
    FOREIGN KEY (IDMODMODELS0)
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODMODELARTIFACTS → MODMODELVERSIONS
ALTER TABLE MODMODELARTIFACTS
    ADD CONSTRAINT SYS_464b9f6964_FK
    FOREIGN KEY (IDMODMODELVERSIONS0)
    REFERENCES MODMODELVERSIONS(IDXMODELVERSION)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODMODELBIASANALYSES → MODMODELS
ALTER TABLE MODMODELBIASANALYSES
    ADD CONSTRAINT SYS_8ed0ee3cf4_FK
    FOREIGN KEY (IDMODMODELS0)
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODMODELDEPENDENCIES → MODMODELS
ALTER TABLE MODMODELDEPENDENCIES
    ADD CONSTRAINT SYS_d01c6a41ee_FK
    FOREIGN KEY (IDMODMODELS0)
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODMODELDEPENDENCIES → MODMODELS
ALTER TABLE MODMODELDEPENDENCIES
    ADD CONSTRAINT SYS_d01c6a41ee_FK
    FOREIGN KEY (IDMODMODELS0)
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODMODELPERFORMANCES → MODMODELS
ALTER TABLE MODMODELPERFORMANCES
    ADD CONSTRAINT SYS_4e1144d266_FK
    FOREIGN KEY (IDMODMODELS0)
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODMODELSTAGETRANSITIONS → MODMODELS
ALTER TABLE MODMODELSTAGETRANSITIONS
    ADD CONSTRAINT SYS_c1af024cc5_FK
    FOREIGN KEY (IDMODMODELS0)
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODMODELSTAGETRANSITIONS → MODMODELVERSIONS
ALTER TABLE MODMODELSTAGETRANSITIONS
    ADD CONSTRAINT SYS_f256b8824c_FK
    FOREIGN KEY (IDMODMODELVERSIONS0)
    REFERENCES MODMODELVERSIONS(IDXMODELVERSION)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODMODELVALIDATIONS → MODMODELS
ALTER TABLE MODMODELVALIDATIONS
    ADD CONSTRAINT SYS_b914c797ad_FK
    FOREIGN KEY (IDMODMODELS0)
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODMODELVALIDATIONS → MODMODELVERSIONS
ALTER TABLE MODMODELVALIDATIONS
    ADD CONSTRAINT SYS_c33e370421_FK
    FOREIGN KEY (IDMODMODELVERSIONS0)
    REFERENCES MODMODELVERSIONS(IDXMODELVERSION)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODMODELVERSIONS → MODMODELS
ALTER TABLE MODMODELVERSIONS
    ADD CONSTRAINT SYS_c38a4619b5_FK
    FOREIGN KEY (IDMODMODELS0)
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODPROVIDERCREDENTIALS → MODPROVIDERS
ALTER TABLE MODPROVIDERCREDENTIALS
    ADD CONSTRAINT SYS_0a34bf2e31_FK
    FOREIGN KEY (IDMODPROVIDERS0)
    REFERENCES MODPROVIDERS(IDXMODELPROVIDER)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: MODUSAGE → MODCATALOG
ALTER TABLE MODUSAGE
    ADD CONSTRAINT SYS_48b110ebca_FK
    FOREIGN KEY (IDMODCATALOG0)
    REFERENCES MODCATALOG(IDXMODELCATALOG)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: NTFLOGS → NTFNOTIFICATIONS
ALTER TABLE NTFLOGS
    ADD CONSTRAINT SYS_04e8b5ea74_FK
    FOREIGN KEY (IDNTFNOTIFICATIONS0)
    REFERENCES NTFNOTIFICATIONS(IDXNOTIFICATION)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: NTFLOGS → NTFCHANNELS
ALTER TABLE NTFLOGS
    ADD CONSTRAINT SYS_8b85a453a6_FK
    FOREIGN KEY (IDNTFCHANNELS0)
    REFERENCES NTFCHANNELS(IDXNOTIFICATIONCHANNEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: NTFNOTIFICATIONS → NTFCHANNELS
ALTER TABLE NTFNOTIFICATIONS
    ADD CONSTRAINT SYS_9401385d0d_FK
    FOREIGN KEY (IDNTFCHANNELS0)
    REFERENCES NTFCHANNELS(IDXNOTIFICATIONCHANNEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: NTFNOTIFICATIONS → NTFTEMPLATES
ALTER TABLE NTFNOTIFICATIONS
    ADD CONSTRAINT SYS_f3a71d9ba9_FK
    FOREIGN KEY (IDNTFTEMPLATES0)
    REFERENCES NTFTEMPLATES(IDXNOTIFICATIONTEMPLATE)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: PRJBILLINGDETAILS → PRJCOSTESTIMATORS
ALTER TABLE PRJBILLINGDETAILS
    ADD CONSTRAINT SYS_61103b94e0_FK
    FOREIGN KEY (IDPRJCOSTESTIMATORS0)
    REFERENCES PRJCOSTESTIMATORS(IDXPROJECTCOSTESTIMATOR)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: PRJINVOICES → PRJCOSTESTIMATORS
ALTER TABLE PRJINVOICES
    ADD CONSTRAINT SYS_63a680d2fb_FK
    FOREIGN KEY (IDPRJCOSTESTIMATORS0)
    REFERENCES PRJCOSTESTIMATORS(IDXPROJECTCOSTESTIMATOR)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: PRJPROJECTTECHNOLOGIES → PRJPROJECTS
ALTER TABLE PRJPROJECTTECHNOLOGIES
    ADD CONSTRAINT SYS_88af644fbc_FK
    FOREIGN KEY (IDPRJPROJECTS0)
    REFERENCES PRJPROJECTS(IDXPROJECT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: PRMPROMPTVALIDATIONS → PRMPROMPTS
ALTER TABLE PRMPROMPTVALIDATIONS
    ADD CONSTRAINT SYS_5911860c90_FK
    FOREIGN KEY (IDPRMPROMPTS0)
    REFERENCES PRMPROMPTS(IDXPROMPT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: PRMPROMPTVERSIONS → PRMPROMPTS
ALTER TABLE PRMPROMPTVERSIONS
    ADD CONSTRAINT SYS_92bbd7d5ef_FK
    FOREIGN KEY (IDPRMPROMPTS0)
    REFERENCES PRMPROMPTS(IDXPROMPT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: RAGRAGDATASOURCES → RAGRAGSYSTEMS
ALTER TABLE RAGRAGDATASOURCES
    ADD CONSTRAINT SYS_a9ffa95208_FK
    FOREIGN KEY (IDRAGRAGSYSTEMS0)
    REFERENCES RAGRAGSYSTEMS(IDXRAGSYSTEM)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: RAGRAGVERSIONS → RAGRAGSYSTEMS
ALTER TABLE RAGRAGVERSIONS
    ADD CONSTRAINT SYS_816085321d_FK
    FOREIGN KEY (IDRAGRAGSYSTEMS0)
    REFERENCES RAGRAGSYSTEMS(IDXRAGSYSTEM)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: SRVDEPLOYMENTS → MODMODELS
ALTER TABLE SRVDEPLOYMENTS
    ADD CONSTRAINT SYS_601c9b6234_FK
    FOREIGN KEY (IDMODMODELS0)
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: SRVMODELMETRICS → MODMODELS
ALTER TABLE SRVMODELMETRICS
    ADD CONSTRAINT SYS_0d6ab79cab_FK
    FOREIGN KEY (IDMODMODELS0)
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: SRVMODELMETRICS → SRVDEPLOYMENTS
ALTER TABLE SRVMODELMETRICS
    ADD CONSTRAINT SYS_ca73c90326_FK
    FOREIGN KEY (IDSRVDEPLOYMENTS0)
    REFERENCES SRVDEPLOYMENTS(IDXDEPLOYMENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: SRVMODELVERSIONS → MODMODELS
ALTER TABLE SRVMODELVERSIONS
    ADD CONSTRAINT SYS_b30ef47de3_FK
    FOREIGN KEY (IDMODMODELS0)
    REFERENCES MODMODELS(IDXMODEL)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: SRVPREDICTIONS → SRVDEPLOYMENTS
ALTER TABLE SRVPREDICTIONS
    ADD CONSTRAINT SYS_479edaeeca_FK
    FOREIGN KEY (IDSRVDEPLOYMENTS0)
    REFERENCES SRVDEPLOYMENTS(IDXDEPLOYMENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNCHECKPOINTS → TRNRUNS
ALTER TABLE TRNCHECKPOINTS
    ADD CONSTRAINT SYS_2b82c76c92_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNENVIRONMENTS → TRNRUNS
ALTER TABLE TRNENVIRONMENTS
    ADD CONSTRAINT SYS_8e0676153d_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNEXPERIMENTLINEAGE → TRNEXPERIMENTS
ALTER TABLE TRNEXPERIMENTLINEAGE
    ADD CONSTRAINT SYS_721e12345e_FK
    FOREIGN KEY (IDTRNEXPERIMENTS0)
    REFERENCES TRNEXPERIMENTS(IDXEXPERIMENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNHPOEXPERIMENTS → TRNEXPERIMENTS
ALTER TABLE TRNHPOEXPERIMENTS
    ADD CONSTRAINT SYS_ddf4cdb3c4_FK
    FOREIGN KEY (IDTRNEXPERIMENTS0)
    REFERENCES TRNEXPERIMENTS(IDXEXPERIMENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNHPOTRIALS → TRNHPOEXPERIMENTS
ALTER TABLE TRNHPOTRIALS
    ADD CONSTRAINT SYS_7d7f9d8452_FK
    FOREIGN KEY (IDTRNHPOEXPERIMENTS0)
    REFERENCES TRNHPOEXPERIMENTS(IDXHPOEXPERIMENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNHPOTRIALS → TRNRUNS
ALTER TABLE TRNHPOTRIALS
    ADD CONSTRAINT SYS_0819d5be8d_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNMETRICSERIES → TRNRUNS
ALTER TABLE TRNMETRICSERIES
    ADD CONSTRAINT SYS_48772cf70e_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNMETRICSTREAMS → TRNRUNS
ALTER TABLE TRNMETRICSTREAMS
    ADD CONSTRAINT SYS_d033aeceee_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNPARAMS → TRNRUNS
ALTER TABLE TRNPARAMS
    ADD CONSTRAINT SYS_044bef3f6b_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNRUNS → TRNEXPERIMENTS
ALTER TABLE TRNRUNS
    ADD CONSTRAINT SYS_5c654bceb3_FK
    FOREIGN KEY (IDTRNEXPERIMENTS0)
    REFERENCES TRNEXPERIMENTS(IDXEXPERIMENT)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNRUNS → TRNRUNS
ALTER TABLE TRNRUNS
    ADD CONSTRAINT SYS_f28b8e264d_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNTAGS → TRNRUNS
ALTER TABLE TRNTAGS
    ADD CONSTRAINT SYS_72732d241c_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNTRAININGALERTS → TRNRUNS
ALTER TABLE TRNTRAININGALERTS
    ADD CONSTRAINT SYS_6e2dbdee86_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNTRAININGARTIFACTS → TRNRUNS
ALTER TABLE TRNTRAININGARTIFACTS
    ADD CONSTRAINT SYS_02569e5ddf_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNTRAININGLOGS → TRNRUNS
ALTER TABLE TRNTRAININGLOGS
    ADD CONSTRAINT SYS_334594814c_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: TRNTRAININGMETRICS → TRNRUNS
ALTER TABLE TRNTRAININGMETRICS
    ADD CONSTRAINT SYS_9916178e86_FK
    FOREIGN KEY (IDTRNRUNS0)
    REFERENCES TRNRUNS(IDXRUN)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: UPDATEINSTALLATIONS → PLATFORMNODES
ALTER TABLE UPDATEINSTALLATIONS
    ADD CONSTRAINT SYS_90ab17e92f_FK
    FOREIGN KEY (IDPLATFORMNODES0)
    REFERENCES PLATFORMNODES(IDXPLATFORMNODE)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: UPDATEINSTALLATIONS → PLATFORMUPDATES
ALTER TABLE UPDATEINSTALLATIONS
    ADD CONSTRAINT SYS_ba79b2955a_FK
    FOREIGN KEY (IDPLATFORMUPDATES0)
    REFERENCES PLATFORMUPDATES(IDXPLATFORMUPDATE)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: UPDATESCHEDULES → PLATFORMUPDATES
ALTER TABLE UPDATESCHEDULES
    ADD CONSTRAINT SYS_dee4cdcc5d_FK
    FOREIGN KEY (IDPLATFORMUPDATES0)
    REFERENCES PLATFORMUPDATES(IDXPLATFORMUPDATE)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

-- FK: UPDATESCHEDULES → CORUSERS
ALTER TABLE UPDATESCHEDULES
    ADD CONSTRAINT SYS_5159cd655c_FK
    FOREIGN KEY (IDCORUSERS0)
    REFERENCES CORUSERS(IDXUSER)
    ON DELETE CASCADE
    ON UPDATE CASCADE;

