-- ============================================================================
-- CodeFlowX Govern Platform - SQL Scripts
-- Generado automáticamente desde JSONs EnArt
-- Fecha: 2025-10-14 12:27:14
-- Total tablas: 161
-- ============================================================================

-- Documentación de tablas y columnas

COMMENT ON TABLE AGTAGENTALERTS IS 'Entidad para gestionar alertas específicas de agentes.';
COMMENT ON TABLE AGTAGENTAPPROVALS IS 'Entidad para gestionar el proceso de aprobación de agentes.';
COMMENT ON TABLE AGTAGENTBIASDETECTIONS IS 'Entidad para gestionar la detección de sesgos en agentes.';
COMMENT ON TABLE AGTAGENTCOLLABORATIONS IS 'Entidad para gestionar colaboraciones entre agentes.';
COMMENT ON TABLE AGTAGENTCOMMUNICATIONS IS 'Entidad para gestionar comunicaciones entre agentes.';
COMMENT ON TABLE AGTAGENTCOMPLIANCE IS 'Entidad para gestionar el cumplimiento de agentes con políticas y regulaciones.';
COMMENT ON TABLE AGTAGENTDECISIONS IS 'Entidad para gestionar decisiones tomadas por agentes de IA.';
COMMENT ON TABLE AGTAGENTDEPLOYMENTS IS 'Entidad para gestionar despliegues de agentes.';
COMMENT ON TABLE AGTAGENTDOMAINS IS 'Entidad para gestionar dominios de especialización de agentes.';
COMMENT ON TABLE AGTAGENTETHICSASSESSMENTS IS 'Entidad para gestionar evaluaciones éticas de agentes.';
COMMENT ON TABLE AGTAGENTEXPERTISE IS 'Entidad para gestionar el nivel de expertise de agentes en dominios específicos.';
COMMENT ON TABLE AGTAGENTGOVERNANCE IS 'Entidad para gestionar políticas de gobierno específicas para agentes.';
COMMENT ON TABLE AGTAGENTHEALTH IS 'Entidad para gestionar el estado de salud de agentes.';
COMMENT ON TABLE AGTAGENTINTERACTIONS IS 'Entidad para registrar interacciones con agentes de IA.';
COMMENT ON TABLE AGTAGENTMONITORING IS 'Entidad para gestionar el monitoreo continuo de agentes.';
COMMENT ON TABLE AGTAGENTROLLBACKS IS 'Entidad para gestionar rollbacks de agentes.';
COMMENT ON TABLE AGTAGENTS IS 'Entidad para gestionar agentes de IA.';
COMMENT ON TABLE AGTAGENTTOOLS IS 'Entidad para gestionar herramientas especializadas de agentes.';
COMMENT ON TABLE AGTAGENTTRANSPARENCY IS 'Entidad para gestionar métricas de transparencia de agentes.';
COMMENT ON TABLE AGTAGENTVERSIONS IS 'Entidad para gestionar versiones de agentes de IA.';
COMMENT ON TABLE AGTAGENTWORKFLOWS IS 'Entidad para gestionar workflows multi-agente.';
COMMENT ON TABLE AGTWORKFLOWEXECUTIONS IS 'Entidad para gestionar ejecuciones de workflows multi-agente.';
COMMENT ON TABLE ANLANALYTICSMETRICS IS 'Entidad para gestionar métricas de análisis de IA.';
COMMENT ON TABLE ANLANALYTICSREPORTS IS 'Entidad para gestionar reportes de análisis de IA.';
COMMENT ON TABLE AUDITLOGS IS 'Entidad AuditLog';
COMMENT ON TABLE CATARTIFACTDEPENDENCIES IS 'Entidad para dependencias entre artefactos del catálogo.';
COMMENT ON TABLE CATARTIFACTVERSIONS IS 'Entidad para versiones de artefactos del catálogo.';
COMMENT ON TABLE CATBASEARTIFACTS IS 'Entidad base para artefactos del catálogo.';
COMMENT ON TABLE CORDEPARTMENTS IS 'Entidad Department';
COMMENT ON TABLE CORLOGINATTEMPTS IS 'Entidad LoginAttempt';
COMMENT ON TABLE CORMENUS IS 'Entidad Menu';
COMMENT ON TABLE CORPERMISSIONS IS 'Entidad Permission';
COMMENT ON TABLE CORROLES IS 'Entidad Role';
COMMENT ON TABLE CORUSERS IS 'Entidad User';
COMMENT ON TABLE CORUSERSESSIONS IS 'Entidad UserSession';
COMMENT ON TABLE DSHCOSTMETRICS IS 'Entidad para métricas de costes operacionales.';
COMMENT ON TABLE DSHDISTRIBUTIONS IS 'Entidad para distribuciones de datos.';
COMMENT ON TABLE DSHMODULEACTIVITY IS 'Entidad para actividad reciente por módulo.';
COMMENT ON TABLE DSHMODULESTATS IS 'Entidad para estadísticas generales por módulo.';
COMMENT ON TABLE DSHQUICKACTIONS IS 'Entidad para acciones rápidas del dashboard.';
COMMENT ON TABLE DSHTIMESERIES IS 'Entidad para series temporales del dashboard.';
COMMENT ON TABLE DSHTOKENMETRICS IS 'Entidad para métricas de tokens LLM.';
COMMENT ON TABLE GOVBIASANALYSIS IS 'JPA Entity for Bias Analysis.';
COMMENT ON TABLE GOVBIASDETECTIONS IS 'JPA Entity for Bias Detection.';
COMMENT ON TABLE GOVBIASRECOMMENDATIONS IS 'JPA Entity for Bias Recommendation.';
COMMENT ON TABLE GOVCOMPLIANCEASSESSMENTS IS 'JPA Entity for Compliance Assessment.';
COMMENT ON TABLE GOVCOMPLIANCEFINDINGS IS 'JPA Entity for Compliance Finding.';
COMMENT ON TABLE GOVCOMPLIANCEREQUIREMENTS IS 'JPA Entity for Compliance Requirement.';
COMMENT ON TABLE GOVEVALUATIONMETRICS IS 'JPA Entity for Evaluation Metric.';
COMMENT ON TABLE GOVFAIRNESSMETRICS IS 'JPA Entity for Fairness Metric.';
COMMENT ON TABLE GOVGOVERNANCEMETRICS IS 'JPA Entity for Governance Metric.';
COMMENT ON TABLE GOVMODELEVALUATIONS IS 'JPA Entity for Model Evaluation.';
COMMENT ON TABLE GOVPOLICIES IS 'JPA Entity for Policy management.';
COMMENT ON TABLE GOVPOLICYAUDITLOGS IS 'JPA Entity for Policy Audit Logs.';
COMMENT ON TABLE GOVPOLICYCHECKLISTITEMS IS 'JPA Entity for Policy Checklist Items.';
COMMENT ON TABLE GOVPOLICYEVALUATIONS IS 'JPA Entity for Policy Evaluations.';
COMMENT ON TABLE GOVPOLICYRULES IS 'JPA Entity for Policy Rules.';
COMMENT ON TABLE GOVPOLICYVALIDATIONCONFIGS IS 'JPA Entity for Policy Validation Configuration.';
COMMENT ON TABLE GOVPOLICYVIOLATIONS IS 'JPA Entity for Policy Violation.';
COMMENT ON TABLE GOVPROJECTARTIFACTS IS 'JPA Entity for Project Artifact.';
COMMENT ON TABLE GOVPROJECTMEMBERS IS 'JPA Entity for Project Member.';
COMMENT ON TABLE GOVRISKINDICATORS IS 'JPA Entity for Risk Indicator.';
COMMENT ON TABLE GOVSECURITYMETRICS IS 'JPA Entity for Security Metric.';
COMMENT ON TABLE GOVSECURITYPOLICIES IS 'JPA Entity for Security Policy.';
COMMENT ON TABLE GOVSECURITYTHREATS IS 'JPA Entity for Security Threat.';
COMMENT ON TABLE GOVSYSTEMALERTS IS 'JPA Entity for System Alert.';
COMMENT ON TABLE GOVSYSTEMHEALTH IS 'JPA Entity for System Health.';
COMMENT ON TABLE GOVSYSTEMMETRICS IS 'JPA Entity for System Metric.';
COMMENT ON TABLE INFAUDITS IS 'Entidad para auditoría de despliegues y operaciones de infraestructura.';
COMMENT ON TABLE INFCLOUDPROVIDERS IS 'Entidad para gestionar proveedores cloud (AWS, GCP, Azure, OVH, RunPod, Vast.ai).';
COMMENT ON TABLE INFCLOUDREGIONS IS 'Entidad para regiones cloud disponibles.';
COMMENT ON TABLE INFCLOUDRESOURCES IS 'Entidad para gestionar recursos cloud generales (balanceadores, storage, etc.).';
COMMENT ON TABLE INFCOSTS IS 'Entidad para sistema de costes y facturación de infraestructura.';
COMMENT ON TABLE INFCREDENTIALS IS 'Entidad para credenciales cloud (tokens, API keys, secrets).';
COMMENT ON TABLE INFGPUINSTANCES IS 'Entidad para gestionar instancias GPU dedicadas.';
COMMENT ON TABLE INFK8SNODES IS 'Entidad para nodos de clusters Kubernetes.';
COMMENT ON TABLE INFKUBERNETESCLUSTERS IS 'Entidad para gestionar clusters Kubernetes (propios o de proveedores).';
COMMENT ON TABLE INFMETRICS IS 'Entidad para métricas de infraestructura.';
COMMENT ON TABLE INFRESOURCEQUOTAS IS 'Entidad para cuotas de recursos en infraestructura.';
COMMENT ON TABLE INFTEMPLATES IS 'Entidad para plantillas de infraestructura como código (IaC).';
COMMENT ON TABLE MODCAPABILITIES IS 'Entidad para capacidades detalladas de modelos.';
COMMENT ON TABLE MODCATALOG IS 'Entidad para catálogo de modelos disponibles de todos los proveedores.';
COMMENT ON TABLE MODENDPOINTS IS 'Entidad para endpoints de serving de modelos.';
COMMENT ON TABLE MODMODELARTIFACTS IS 'Entidad para gestionar artefactos de modelos.';
COMMENT ON TABLE MODMODELBIASANALYSES IS 'Entidad para gestionar análisis de sesgos en modelos de IA.';
COMMENT ON TABLE MODMODELCOMPARISONS IS 'Entidad para gestionar comparaciones entre modelos.';
COMMENT ON TABLE MODMODELDEPENDENCIES IS 'Entidad para gestionar dependencias entre modelos.';
COMMENT ON TABLE MODMODELPERFORMANCES IS 'Entidad para gestionar métricas de rendimiento de modelos de IA.';
COMMENT ON TABLE MODMODELS IS 'Entidad para gestionar modelos de IA.';
COMMENT ON TABLE MODMODELSTAGETRANSITIONS IS 'Entidad para gestionar transiciones de stage de modelos.';
COMMENT ON TABLE MODMODELVALIDATIONS IS 'Entidad para gestionar validaciones de modelos.';
COMMENT ON TABLE MODMODELVERSIONS IS 'Entidad para gestionar versiones de modelos de IA.';
COMMENT ON TABLE MODPROVIDERCREDENTIALS IS 'Entidad para credenciales y tokens de acceso a proveedores.';
COMMENT ON TABLE MODPROVIDERS IS 'Entidad para proveedores de modelos de IA.';
COMMENT ON TABLE MODRECOMMENDATIONS IS 'Entidad para recomendaciones inteligentes de modelos.';
COMMENT ON TABLE MODUSAGE IS 'Entidad para tracking de uso y costes de modelos.';
COMMENT ON TABLE MONMONITORINGALERTS IS 'Entidad para gestionar alertas de monitoreo de IA.';
COMMENT ON TABLE MONMONITORINGMETRICS IS 'Entidad para gestionar métricas de monitoreo en tiempo real.';
COMMENT ON TABLE NTFCHANNELS IS 'Entidad para gestión de canales de notificación';
COMMENT ON TABLE NTFLOGS IS 'Entidad para gestión de logs de notificaciones';
COMMENT ON TABLE NTFNOTIFICATIONS IS 'Entidad para gestión de notificaciones generales';
COMMENT ON TABLE NTFPREFERENCES IS 'Entidad para gestión de preferencias de notificación de usuarios';
COMMENT ON TABLE NTFTEMPLATES IS 'Entidad para gestión de plantillas de notificación';
COMMENT ON TABLE PLATFORMLICENSES IS 'Entidad PlatformLicense';
COMMENT ON TABLE PLATFORMNODES IS 'Entidad PlatformNode';
COMMENT ON TABLE PLATFORMUPDATES IS 'Entidad PlatformUpdate';
COMMENT ON TABLE PRJBILLINGDETAILS IS 'Entidad para desglose detallado de facturación por proyecto.';
COMMENT ON TABLE PRJCOSTESTIMATORS IS 'Entidad para estimación de costes y facturación por proyecto.';
COMMENT ON TABLE PRJINVOICES IS 'Entidad para facturas generadas por proyecto.';
COMMENT ON TABLE PRJPROJECTDOCUMENTS IS 'JPA Entity for ProjectDocument.';
COMMENT ON TABLE PRJPROJECTDOMAINS IS 'JPA Entity for ProjectDomain.';
COMMENT ON TABLE PRJPROJECTLICENSES IS 'JPA Entity for ProjectLicense.';
COMMENT ON TABLE PRJPROJECTREQUIREMENTS IS 'JPA Entity for ProjectRequirement.';
COMMENT ON TABLE PRJPROJECTS IS 'JPA Entity for Project.';
COMMENT ON TABLE PRJPROJECTSTACKS IS 'JPA Entity for ProjectStack.';
COMMENT ON TABLE PRJPROJECTTASKS IS 'JPA Entity for ProjectTask.';
COMMENT ON TABLE PRJPROJECTTECHNOLOGIES IS 'JPA Entity for Project Technology.';
COMMENT ON TABLE PRJPROJECTTIMETRACKING IS 'JPA Entity for ProjectTimeTracking.';
COMMENT ON TABLE PRJPROJECTTOKENS IS 'JPA Entity for ProjectToken.';
COMMENT ON TABLE PRJPROJECTVERSIONS IS 'JPA Entity for ProjectVersion.';
COMMENT ON TABLE PRJRESOURCECONSUMPTION IS 'Entidad para tracking detallado de recursos consumidos por proyecto.';
COMMENT ON TABLE PRJROIANALYSIS IS 'Entidad para análisis de ROI (Return on Investment) por proyecto.';
COMMENT ON TABLE PRMPROMPTS IS 'Entidad para gestionar prompts de IA.';
COMMENT ON TABLE PRMPROMPTVALIDATIONS IS 'Entidad para gestionar validaciones de prompts.';
COMMENT ON TABLE PRMPROMPTVERSIONS IS 'Entidad para gestionar versiones de prompts.';
COMMENT ON TABLE RAGRAGDATASOURCES IS 'Entidad para gestionar fuentes de datos de sistemas RAG.';
COMMENT ON TABLE RAGRAGSYSTEMS IS 'Entidad para gestionar sistemas RAG (Retrieval Augmented Generation).';
COMMENT ON TABLE RAGRAGVERSIONS IS 'Entidad para gestionar versiones de sistemas RAG.';
COMMENT ON TABLE SRVDEPLOYMENTINSTANCES IS 'JPA Entity for DeploymentInstance.';
COMMENT ON TABLE SRVDEPLOYMENTLOGS IS 'JPA Entity for DeploymentLog.';
COMMENT ON TABLE SRVDEPLOYMENTMETRICS IS 'JPA Entity for DeploymentMetric.';
COMMENT ON TABLE SRVDEPLOYMENTS IS 'Entidad para gestión de despliegues de modelos';
COMMENT ON TABLE SRVMODELMETRICS IS 'Entidad para gestión de métricas de modelos';
COMMENT ON TABLE SRVMODELS IS 'Entidad para gestión de modelos de ML/AI';
COMMENT ON TABLE SRVMODELVERSIONS IS 'Entidad para gestión de versiones de modelos';
COMMENT ON TABLE SRVPREDICTIONS IS 'Entidad para gestión de predicciones de modelos';
COMMENT ON TABLE SRVSERVINGENDPOINTS IS 'JPA Entity for ServingEndpoint.';
COMMENT ON TABLE SRVSERVINGREQUESTS IS 'JPA Entity for ServingRequest.';
COMMENT ON TABLE TRNCHECKPOINTS IS 'Entidad para gestión inteligente de checkpoints.';
COMMENT ON TABLE TRNDATASETSOURCES IS 'JPA Entity for DatasetSource.';
COMMENT ON TABLE TRNENVIRONMENTS IS 'Entidad para tracking completo del environment de entrenamiento.';
COMMENT ON TABLE TRNEXPERIMENTLINEAGE IS 'Entidad para linaje y provenance de experimentos.';
COMMENT ON TABLE TRNEXPERIMENTS IS 'Entidad para experimentos de training.';
COMMENT ON TABLE TRNEXPERIMENTTEMPLATES IS 'Entidad para templates de experimentos y best practices.';
COMMENT ON TABLE TRNHPOEXPERIMENTS IS 'Entidad para experimentos de Hyperparameter Optimization (HPO).';
COMMENT ON TABLE TRNHPOTRIALS IS 'Entidad para trials individuales de HPO.';
COMMENT ON TABLE TRNMETRICSERIES IS 'Entidad para series temporales de métricas.';
COMMENT ON TABLE TRNMETRICSTREAMS IS 'Entidad para streaming en tiempo real de métricas.';
COMMENT ON TABLE TRNPARAMS IS 'Entidad para parámetros e hyperparameters de training.';
COMMENT ON TABLE TRNRUNCOMPARISONS IS 'Entidad para comparación avanzada de múltiples runs.';
COMMENT ON TABLE TRNRUNS IS 'Entidad para runs de training.';
COMMENT ON TABLE TRNTAGS IS 'Entidad para tags de runs.';
COMMENT ON TABLE TRNTRAININGALERTS IS 'Entidad para alertas inteligentes durante el entrenamiento.';
COMMENT ON TABLE TRNTRAININGARTIFACTS IS 'JPA Entity for TrainingArtifact.';
COMMENT ON TABLE TRNTRAININGEXECUTIONS IS 'JPA Entity for TrainingExecution.';
COMMENT ON TABLE TRNTRAININGGOVERNANCE IS 'JPA Entity for TrainingGovernance.';
COMMENT ON TABLE TRNTRAININGINFRASTRUCTURE IS 'JPA Entity for TrainingInfrastructure.';
COMMENT ON TABLE TRNTRAININGLOGS IS 'JPA Entity for TrainingLog.';
COMMENT ON TABLE TRNTRAININGMETRICS IS 'JPA Entity for TrainingMetric.';
COMMENT ON TABLE UPDATEINSTALLATIONS IS 'Entidad UpdateInstallation';
COMMENT ON TABLE UPDATESCHEDULES IS 'Entidad UpdateSchedule';
