-- ============================================================================
-- CodeFlowX Govern Platform - BPMN Workflow Tables
-- Metodología: EnArt (sin guiones bajos, TODO MAYÚSCULAS)
-- Fecha: 2025-10-20
-- Total tablas: 4
-- ============================================================================

-- ============================================================================
-- Tabla: DRFDRIFTDETECTIONS
-- Proceso BPMN: Drift Detection Process (#9)
-- ============================================================================
CREATE TABLE IF NOT EXISTS DRFDRIFTDETECTIONS (
    iduuid UUID UNIQUE,
    IDXDRIFTDETECTION BIGSERIAL PRIMARY KEY,
    IDXMODEL BIGINT NOT NULL,
    IDXMODELVERSION BIGINT,
    DRFTYPE VARCHAR(50) NOT NULL,
    DRFSCORE DOUBLE PRECISION NOT NULL,
    DRFTHRESHOLD DOUBLE PRECISION NOT NULL,
    DRFDETECTED BOOLEAN NOT NULL DEFAULT false,
    DRFSEVERITY VARCHAR(20),
    DRFACTION VARCHAR(50),
    DRFBASELINEMETRICS JSONB,
    DRFCURRENTMETRICS JSONB,
    DRFACCURACYDEGRADATION DOUBLE PRECISION,
    DRFLATENCYINCREASE DOUBLE PRECISION,
    DRFTHROUGHPUTDECREASE DOUBLE PRECISION,
    DRFREQUIRESHUMANANALYSIS BOOLEAN DEFAULT false,
    DRFESCALATIONLEVEL VARCHAR(20),
    DRFRECOMMENDATION TEXT,
    DRFROOTCAUSE TEXT,
    DRFACTIONTAKEN VARCHAR(50),
    DRFPROCESSINSTANCEID VARCHAR(100),
    DRFSTATUS VARCHAR(20) NOT NULL DEFAULT 'DETECTED',
    DRFCREATEDAT TIMESTAMP NOT NULL DEFAULT NOW(),
    DRFCREATEDBY VARCHAR(100),
    DRFUPDATEDAT TIMESTAMP,
    DRFUPDATEDBY VARCHAR(100)
);

CREATE INDEX idx_drift_model ON DRFDRIFTDETECTIONS(IDXMODEL);
CREATE INDEX idx_drift_detected ON DRFDRIFTDETECTIONS(DRFDETECTED);
CREATE INDEX idx_drift_severity ON DRFDRIFTDETECTIONS(DRFSEVERITY);
CREATE INDEX idx_drift_status ON DRFDRIFTDETECTIONS(DRFSTATUS);
CREATE INDEX idx_drift_created ON DRFDRIFTDETECTIONS(DRFCREATEDAT DESC);

COMMENT ON TABLE DRFDRIFTDETECTIONS IS 'Tracking de drift detection de modelos ML';

-- ============================================================================
-- Tabla: ETHETHICSREVIEWS
-- Proceso BPMN: Ethics Review Process (#12)
-- ============================================================================
CREATE TABLE IF NOT EXISTS ETHETHICSREVIEWS (
    iduuid UUID UNIQUE,
    IDXETHICSREVIEW BIGSERIAL PRIMARY KEY,
    ETHENTITYTYPE VARCHAR(50) NOT NULL,
    ETHENTITYID BIGINT NOT NULL,
    ETHENTITYNAME VARCHAR(255),
    ETHREVIEWTYPE VARCHAR(50) NOT NULL,
    ETHREQUESTER VARCHAR(100) NOT NULL,
    ETHREQUESTREASON TEXT,
    ETHIMPACTASSESSMENT JSONB,
    ETHSCORE INTEGER,
    ETHTHRESHOLD INTEGER,
    ETHMEETSTHRESHOLD BOOLEAN,
    ETHCONCERNS JSONB,
    ETHSEVERITY VARCHAR(20),
    ETHREQUIRESCOMMITTEEREVIEW BOOLEAN DEFAULT false,
    ETHCOMMITTEEMEMBERS JSONB,
    ETHCOMMITTEEDECISION VARCHAR(50),
    ETHCOMMITTEENOTES TEXT,
    ETHCOMMITTEEREVIEWEDAT TIMESTAMP,
    ETHMITIGATIONREQUIRED BOOLEAN DEFAULT false,
    ETHMITIGATIONPLAN JSONB,
    ETHMITIGATIONSTATUS VARCHAR(20),
    ETHMITIGATIONCOMPLETEDAT TIMESTAMP,
    ETHEVIDENCEPATH VARCHAR(500),
    ETHEVIDENCEMETADATA JSONB,
    ETHPROCESSINSTANCEID VARCHAR(100),
    ETHSTATUS VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
    ETHCREATEDAT TIMESTAMP NOT NULL DEFAULT NOW(),
    ETHCREATEDBY VARCHAR(100),
    ETHUPDATEDAT TIMESTAMP,
    ETHUPDATEDBY VARCHAR(100),
    ETHAPPROVEDAT TIMESTAMP,
    ETHAPPROVEDBY VARCHAR(100)
);

CREATE INDEX idx_ethics_entity ON ETHETHICSREVIEWS(ETHENTITYTYPE, ETHENTITYID);
CREATE INDEX idx_ethics_status ON ETHETHICSREVIEWS(ETHSTATUS);
CREATE INDEX idx_ethics_severity ON ETHETHICSREVIEWS(ETHSEVERITY);
CREATE INDEX idx_ethics_created ON ETHETHICSREVIEWS(ETHCREATEDAT DESC);

COMMENT ON TABLE ETHETHICSREVIEWS IS 'Revisiones éticas de modelos, agentes y prompts';

-- ============================================================================
-- Tabla: PRFPERFORMANCEMETRICS
-- Proceso BPMN: Performance Degradation Process (#11)
-- ============================================================================
CREATE TABLE IF NOT EXISTS PRFPERFORMANCEMETRICS (
    iduuid UUID UNIQUE,
    IDXPERFORMANCEMETRIC BIGSERIAL PRIMARY KEY,
    PRFENTITYTYPE VARCHAR(50) NOT NULL,
    PRFENTITYID BIGINT NOT NULL,
    PRFENTITYNAME VARCHAR(255),
    PRFDEPLOYMENTNAME VARCHAR(255),
    PRFNAMESPACE VARCHAR(100),
    PRFLATENCYMS DOUBLE PRECISION,
    PRFLATENCYTHRESHOLDMS DOUBLE PRECISION,
    PRFTHROUGHPUT DOUBLE PRECISION,
    PRFTHROUGHPUTTHRESHOLD DOUBLE PRECISION,
    PRFERRORRATE DOUBLE PRECISION,
    PRFERRORRATETHRESHOLD DOUBLE PRECISION,
    PRFCPUUSAGE DOUBLE PRECISION,
    PRFMEMORYUSAGE DOUBLE PRECISION,
    PRFGPUUSAGE DOUBLE PRECISION,
    PRFDEGRADATIONDETECTED BOOLEAN DEFAULT false,
    PRFDEGRADATIONPERCENTAGE DOUBLE PRECISION,
    PRFDEGRADATIONTYPE VARCHAR(50),
    PRFCANAUTOSCALE BOOLEAN DEFAULT false,
    PRFCURRENTREPLICAS INTEGER,
    PRFTARGETREPLICAS INTEGER,
    PRFMAXREPLICAS INTEGER,
    PRFAUTOSCALEREASON VARCHAR(255),
    PRFACTIONTAKEN VARCHAR(50),
    PRFACTIONDETAILS TEXT,
    PRFACTIONTIMESTAMP TIMESTAMP,
    PRFMETRICSSNAPSHOT JSONB,
    PRFPROCESSINSTANCEID VARCHAR(100),
    PRFSTATUS VARCHAR(20) DEFAULT 'NORMAL',
    PRFMEASUREDAT TIMESTAMP NOT NULL DEFAULT NOW(),
    PRFCREATEDAT TIMESTAMP NOT NULL DEFAULT NOW(),
    PRFCREATEDBY VARCHAR(100),
    PRFUPDATEDAT TIMESTAMP,
    PRFUPDATEDBY VARCHAR(100)
);

CREATE INDEX idx_perf_entity ON PRFPERFORMANCEMETRICS(PRFENTITYTYPE, PRFENTITYID);
CREATE INDEX idx_perf_degradation ON PRFPERFORMANCEMETRICS(PRFDEGRADATIONDETECTED);
CREATE INDEX idx_perf_status ON PRFPERFORMANCEMETRICS(PRFSTATUS);
CREATE INDEX idx_perf_measured ON PRFPERFORMANCEMETRICS(PRFMEASUREDAT DESC);

COMMENT ON TABLE PRFPERFORMANCEMETRICS IS 'Métricas de performance y degradación';

-- ============================================================================
-- Tabla: PEXPROCESSEXECUTIONS
-- Tracking de ejecuciones de procesos BPMN
-- ============================================================================
CREATE TABLE IF NOT EXISTS PEXPROCESSEXECUTIONS (
    iduuid UUID UNIQUE,
    IDXPROCESSEXECUTION BIGSERIAL PRIMARY KEY,
    PEXPROCESSDEFINITIONID VARCHAR(100) NOT NULL,
    PEXPROCESSINSTANCEID VARCHAR(100) NOT NULL UNIQUE,
    PEXPROCESSNAME VARCHAR(255),
    PEXBUSINESSKEY VARCHAR(255),
    PEXENTITYTYPE VARCHAR(50),
    PEXENTITYID BIGINT,
    PEXSTATUS VARCHAR(20) NOT NULL DEFAULT 'RUNNING',
    PEXOUTCOME VARCHAR(50),
    PEXSTARTEDAT TIMESTAMP NOT NULL DEFAULT NOW(),
    PEXCOMPLETEDAT TIMESTAMP,
    PEXDURATIONMS BIGINT,
    PEXTASKSTOTAL INTEGER DEFAULT 0,
    PEXTASKSCOMPLETED INTEGER DEFAULT 0,
    PEXTASKSFAILED INTEGER DEFAULT 0,
    PEXUSERTASKS INTEGER DEFAULT 0,
    PEXSERVICETASKS INTEGER DEFAULT 0,
    PEXVARIABLES JSONB,
    PEXERRORMESSAGE TEXT,
    PEXERRORTASKID VARCHAR(100),
    PEXERRORSTACKTRACE TEXT,
    PEXAUTOMATIONPERCENTAGE DOUBLE PRECISION,
    PEXHITLINTERVENTIONS INTEGER DEFAULT 0,
    PEXCREATEDAT TIMESTAMP NOT NULL DEFAULT NOW(),
    PEXCREATEDBY VARCHAR(100),
    PEXUPDATEDAT TIMESTAMP,
    PEXUPDATEDBY VARCHAR(100)
);

CREATE INDEX idx_proc_instance ON PEXPROCESSEXECUTIONS(PEXPROCESSINSTANCEID);
CREATE INDEX idx_proc_definition ON PEXPROCESSEXECUTIONS(PEXPROCESSDEFINITIONID);
CREATE INDEX idx_proc_status ON PEXPROCESSEXECUTIONS(PEXSTATUS);
CREATE INDEX idx_proc_entity ON PEXPROCESSEXECUTIONS(PEXENTITYTYPE, PEXENTITYID);
CREATE INDEX idx_proc_started ON PEXPROCESSEXECUTIONS(PEXSTARTEDAT DESC);

COMMENT ON TABLE PEXPROCESSEXECUTIONS IS 'Tracking de ejecuciones de procesos BPMN';

-- ============================================================================
-- FIN DEL SCRIPT
-- ============================================================================
