-- ============================================================================
-- ISO 42001 Competence & Awareness Tables
-- ============================================================================
CREATE TABLE IF NOT EXISTS AICCOMPETENCE (
    IDXAICCOMPETENCE          BIGSERIAL PRIMARY KEY,
    AICPERSONNAME             VARCHAR(100) NOT NULL,
    AICPERSONEMAIL            VARCHAR(100) NOT NULL,
    AICROLE                   VARCHAR(50)  NOT NULL,
    AICREQUIREDCOMPETENCIES   TEXT,
    AICCURRENTCOMPETENCIES    TEXT,
    AICGAPANALYSIS            TEXT,
    AICTRAININGPLAN           TEXT,
    AICLASTAWARENESSTRAINED   TIMESTAMP,
    AICAWARENESSLEVEL         VARCHAR(20),
    AICCERTIFICATIONS         TEXT,
    AICCREATEDAT              TIMESTAMP NOT NULL DEFAULT NOW(),
    AICUPDATEDAT              TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS IDX_AIC_EMAIL ON AICCOMPETENCE(AICPERSONEMAIL);
CREATE INDEX IF NOT EXISTS IDX_AIC_ROLE ON AICCOMPETENCE(AICROLE);
CREATE INDEX IF NOT EXISTS IDX_AIC_AWARENESS ON AICCOMPETENCE(AICAWARENESSLEVEL);

CREATE TABLE IF NOT EXISTS AITTRAININGRECORD (
    IDXAITTRAINING        BIGSERIAL PRIMARY KEY,
    AITPERSONID           BIGINT NOT NULL REFERENCES AICCOMPETENCE(IDXAICCOMPETENCE) ON DELETE CASCADE,
    AITTRAININGTYPE       VARCHAR(50) NOT NULL,
    AITTRAININGTITLE      VARCHAR(200) NOT NULL,
    AITTRAININGDATE       TIMESTAMP NOT NULL,
    AITDURATION           INTEGER,
    AITPROVIDER           VARCHAR(100),
    AITCERTIFICATEOBTAINED BOOLEAN,
    AITCERTIFICATEURL     TEXT,
    AITCREATEDAT          TIMESTAMP NOT NULL DEFAULT NOW(),
    AITUPDATEDAT          TIMESTAMP
);

CREATE INDEX IF NOT EXISTS IDX_AIT_PERSON ON AITTRAININGRECORD(AITPERSONID);
CREATE INDEX IF NOT EXISTS IDX_AIT_TYPE ON AITTRAININGRECORD(AITTRAININGTYPE);
CREATE INDEX IF NOT EXISTS IDX_AIT_CERTIFICATE ON AITTRAININGRECORD(AITCERTIFICATEOBTAINED);

-- Seed básico: Awareness inicial para roles críticos (opcional)
INSERT INTO AICCOMPETENCE (
    AICPERSONNAME,
    AICPERSONEMAIL,
    AICROLE,
    AICREQUIREDCOMPETENCIES,
    AICCURRENTCOMPETENCIES,
    AICAWARENESSLEVEL,
    AICCREATEDAT
) VALUES
('Owner por Asignar', 'pending@codeflowx.ai', 'COMPLIANCE', '["ISO 42001","EU AI Act","GDPR"]', '[]', 'NONE', NOW())
ON CONFLICT (AICPERSONEMAIL) DO NOTHING;


