-- ============================================================================
-- VIEWS - GOVERNANCE MODULE
-- ============================================================================

-- Vista para listado de políticas con todas las FKs resueltas y métricas calculadas
DROP VIEW IF EXISTS V_GOVERNANCE_OVERVIEW CASCADE;

CREATE VIEW V_GOVERNANCE_OVERVIEW AS
SELECT
    -- Campos de la política (SOLO LOS QUE EXISTEN EN GOVPOLICIES)
    p.IDXPOLICY,
    p.NAME,
    p.DESCRIPTION,
    p.CATEGORY,
    p.ENFORCEMENTLEVEL,
    p.POLICYTYPE,
    p.STATUS,
    p.VERSION,
    p.CREATEDBY,
    p.CREATEDAT,
    p.UPDATEDAT,
    p.EFFECTIVEDATE,
    p.EXPIRATIONDATE,
    p.METADATA,

    -- Contadores calculados (mejora performance)
    (SELECT COUNT(*) FROM GOVPOLICYRULES pr WHERE pr.IDGOVPOLICIES0 = p.IDXPOLICY) AS TOTAL_RULES,
    (SELECT COUNT(*) FROM GOVPOLICYEVALUATIONS pe WHERE pe.IDGOVPOLICIES0 = p.IDXPOLICY) AS TOTAL_EVALUATIONS,
    (SELECT COUNT(*) FROM GOVPOLICYVIOLATIONS pv WHERE pv.POLICYNAME = p.NAME) AS TOTAL_VIOLATIONS,

    -- Última evaluación
    (SELECT pe.CONFIDENCESCORE
     FROM GOVPOLICYEVALUATIONS pe
     WHERE pe.IDGOVPOLICIES0 = p.IDXPOLICY
     ORDER BY pe.EVALUATEDAT DESC
     LIMIT 1) AS LAST_EVALUATION_SCORE,

    -- Última fecha de evaluación
    (SELECT pe.EVALUATEDAT
     FROM GOVPOLICYEVALUATIONS pe
     WHERE pe.IDGOVPOLICIES0 = p.IDXPOLICY
     ORDER BY pe.EVALUATEDAT DESC
     LIMIT 1) AS LAST_EVALUATION_DATE,

    -- Score promedio de evaluaciones
    (SELECT AVG(pe.CONFIDENCESCORE)
     FROM GOVPOLICYEVALUATIONS pe
     WHERE pe.IDGOVPOLICIES0 = p.IDXPOLICY
       AND pe.CONFIDENCESCORE IS NOT NULL) AS AVERAGE_EVALUATION_SCORE,

    -- Violaciones críticas pendientes
    (SELECT COUNT(*)
     FROM GOVPOLICYVIOLATIONS pv
     WHERE pv.POLICYNAME = p.NAME
       AND pv.SEVERITY = 'CRITICAL'
       AND 'OPEN' = ANY(pv.STATUS)) AS CRITICAL_VIOLATIONS_PENDING

FROM GOVPOLICIES p;

-- Comentario en la vista
COMMENT ON VIEW V_GOVERNANCE_OVERVIEW IS 'Vista optimizada para listado de políticas con métricas calculadas';


-- ============================================================================
-- Vista para métricas globales del módulo Governance
-- ============================================================================

DROP VIEW IF EXISTS V_GOVERNANCE_METRICS_SUMMARY CASCADE;

CREATE VIEW V_GOVERNANCE_METRICS_SUMMARY AS
SELECT
    -- Contadores totales
    COUNT(*) AS TOTAL_POLICIES,
    COUNT(*) FILTER (WHERE 'ACTIVE' = ANY(STATUS)) AS ACTIVE_POLICIES,
    COUNT(*) FILTER (WHERE 'DRAFT' = ANY(STATUS)) AS DRAFT_POLICIES,
    COUNT(*) FILTER (WHERE 'PENDING_APPROVAL' = ANY(STATUS)) AS PENDING_APPROVAL,
    COUNT(*) FILTER (WHERE EXPIRATIONDATE IS NOT NULL AND EXPIRATIONDATE < NOW()) AS EXPIRED_POLICIES,

    -- Métricas por tipo de política
    COUNT(*) FILTER (WHERE 'COMPLIANCE' = ANY(POLICYTYPE)) AS COMPLIANCE_POLICIES,
    COUNT(*) FILTER (WHERE 'SECURITY' = ANY(POLICYTYPE)) AS SECURITY_POLICIES,
    COUNT(*) FILTER (WHERE 'DATA_PROTECTION' = ANY(POLICYTYPE)) AS DATA_PROTECTION_POLICIES,
    COUNT(*) FILTER (WHERE 'ETHICS' = ANY(POLICYTYPE)) AS ETHICS_POLICIES,

    -- Métricas por nivel de enforcement
    COUNT(*) FILTER (WHERE 'HIGH' = ANY(ENFORCEMENTLEVEL)) AS HIGH_ENFORCEMENT_POLICIES,
    COUNT(*) FILTER (WHERE 'MEDIUM' = ANY(ENFORCEMENTLEVEL)) AS MEDIUM_ENFORCEMENT_POLICIES,
    COUNT(*) FILTER (WHERE 'LOW' = ANY(ENFORCEMENTLEVEL)) AS LOW_ENFORCEMENT_POLICIES,

    -- Métricas calculadas
    (SELECT AVG(pe.CONFIDENCESCORE)
     FROM GOVPOLICYEVALUATIONS pe
     WHERE pe.CONFIDENCESCORE IS NOT NULL) AS AVERAGE_COMPLIANCE_SCORE,

    (SELECT COUNT(*)
     FROM GOVPOLICYVIOLATIONS pv
     WHERE 'OPEN' = ANY(pv.STATUS)) AS TOTAL_OPEN_VIOLATIONS,

    (SELECT COUNT(*)
     FROM GOVPOLICYVIOLATIONS pv
     WHERE pv.SEVERITY = 'CRITICAL' AND 'OPEN' = ANY(pv.STATUS)) AS CRITICAL_VIOLATIONS,

    -- Totales de evaluaciones y reglas
    (SELECT COUNT(*) FROM GOVPOLICYEVALUATIONS) AS TOTAL_EVALUATIONS_ALL,
    (SELECT COUNT(*) FROM GOVPOLICYRULES) AS TOTAL_RULES_ALL,

    -- Timestamp de generación
    NOW() AS GENERATED_AT

FROM GOVPOLICIES p;

COMMENT ON VIEW V_GOVERNANCE_METRICS_SUMMARY IS 'Vista para métricas globales del módulo de governance';
