-- ============================================================================
-- VIEWS - INFRASTRUCTURE MODULE
-- ============================================================================

-- Vista para listado de recursos cloud con métricas calculadas
DROP VIEW IF EXISTS V_INFRASTRUCTURE_OVERVIEW CASCADE;

CREATE VIEW V_INFRASTRUCTURE_OVERVIEW AS
SELECT 
    -- Campos del recurso cloud
    r.IDXCLOUDRESOURCE,
    r.INFRESPROVIDERID,
    r.INFRESCLUSTERID,
    r.INFRESNAME,
    r.INFRESDESCRIPTION,
    r.INFRESRESOURCEID,
    r.INFRESRESOURCETYPE,
    r.INFRESREGION,
    r.INFRESAVAILABILITYZONE,
    r.INFRESENDPOINTURL,
    r.INFRESCAPACITYTOTAL,
    r.INFRESCAPACITYUNIT,
    r.INFRESPERFORMANCETIER,
    r.INFRESCONFIGURATION,
    r.INFRESNETWORKCONFIG,
    r.INFRESSECURITYCONFIG,
    r.INFRESBACKUPSCHEDULE,
    r.INFRESLASTBACKUP,
    r.INFRESHOURLYCOST,
    r.INFRESLASTHEALTHCHECK,
    r.INFRESHEALTHSTATUS,
    r.INFRESMETADATA,
    r.INFRESTAGS,
    r.INFRESCREATEDAT,
    r.INFRESUPDATEDAT,
    r.INFRESCREATEDBY,
    r.INFRESUPDATEDBY,
    
    -- Información del proveedor cloud
    p.INFNAME AS PROVIDER_NAME,
    p.INFPROVIDERTYPE AS PROVIDER_TYPE,
    p.INFDEFAULTREGION AS PROVIDER_DEFAULT_REGION,
    
    -- Información del cluster k8s (si aplica)
    k.INFK8SNAME AS CLUSTER_NAME,
    k.INFK8SVERSION AS CLUSTER_VERSION,
    
    -- Contadores y métricas calculadas
    (SELECT COUNT(*) FROM INFMETRICS m 
     WHERE m.INFMETRICRESOURCEID = r.IDXCLOUDRESOURCE) AS TOTAL_METRICS,
    
    (SELECT COUNT(*) FROM INFAUDITS a 
     WHERE a.INFAUDITRESOURCEID = r.IDXCLOUDRESOURCE) AS TOTAL_AUDITS,
    
    -- Última métrica registrada
    (SELECT MAX(m.INFMETRICTIMESTAMP) FROM INFMETRICS m 
     WHERE m.INFMETRICRESOURCEID = r.IDXCLOUDRESOURCE) AS LAST_METRIC_AT

FROM INFCLOUDRESOURCES r
LEFT JOIN INFCLOUDPROVIDERS p ON r.INFRESPROVIDERID = p.IDXCLOUDPROVIDER
LEFT JOIN INFKUBERNETESCLUSTERS k ON r.INFRESCLUSTERID = k.IDXKUBERNETESCLUSTER;

COMMENT ON VIEW V_INFRASTRUCTURE_OVERVIEW IS 'Vista optimizada para listado de recursos cloud con métricas calculadas';


-- ============================================================================
-- Vista para métricas globales del módulo INFRASTRUCTURE
-- ============================================================================

DROP VIEW IF EXISTS V_INFRASTRUCTURE_METRICS_SUMMARY CASCADE;

CREATE VIEW V_INFRASTRUCTURE_METRICS_SUMMARY AS
SELECT 
    -- Contadores totales de recursos
    COUNT(*) AS TOTAL_RESOURCES,
    COUNT(*) FILTER (WHERE 'COMPUTE' = ANY(INFRESRESOURCETYPE)) AS COMPUTE_RESOURCES,
    COUNT(*) FILTER (WHERE 'STORAGE' = ANY(INFRESRESOURCETYPE)) AS STORAGE_RESOURCES,
    COUNT(*) FILTER (WHERE 'NETWORK' = ANY(INFRESRESOURCETYPE)) AS NETWORK_RESOURCES,
    COUNT(*) FILTER (WHERE 'DATABASE' = ANY(INFRESRESOURCETYPE)) AS DATABASE_RESOURCES,
    COUNT(*) FILTER (WHERE 'GPU' = ANY(INFRESRESOURCETYPE)) AS GPU_RESOURCES,
    COUNT(*) FILTER (WHERE 'KUBERNETES' = ANY(INFRESRESOURCETYPE)) AS KUBERNETES_RESOURCES,
    COUNT(*) FILTER (WHERE 'CONTAINER' = ANY(INFRESRESOURCETYPE)) AS CONTAINER_RESOURCES,
    
    -- Salud de recursos
    COUNT(*) FILTER (WHERE 'HEALTHY' = ANY(INFRESHEALTHSTATUS)) AS HEALTHY_RESOURCES,
    COUNT(*) FILTER (WHERE 'DEGRADED' = ANY(INFRESHEALTHSTATUS)) AS DEGRADED_RESOURCES,
    COUNT(*) FILTER (WHERE 'UNHEALTHY' = ANY(INFRESHEALTHSTATUS)) AS UNHEALTHY_RESOURCES,
    COUNT(*) FILTER (WHERE 'UNKNOWN' = ANY(INFRESHEALTHSTATUS)) AS UNKNOWN_HEALTH_RESOURCES,
    
    -- Métricas de costos
    COALESCE(SUM(INFRESHOURLYCOST), 0) AS TOTAL_HOURLY_COST,
    COALESCE(AVG(INFRESHOURLYCOST), 0) AS AVG_HOURLY_COST,
    
    -- Métricas de capacidad
    COALESCE(SUM(INFRESCAPACITYTOTAL), 0) AS TOTAL_CAPACITY,
    COALESCE(AVG(INFRESCAPACITYTOTAL), 0) AS AVG_CAPACITY,
    
    -- Contadores por tier de performance
    COUNT(*) FILTER (WHERE INFRESPERFORMANCETIER = 'HIGH') AS HIGH_PERFORMANCE_RESOURCES,
    COUNT(*) FILTER (WHERE INFRESPERFORMANCETIER = 'MEDIUM') AS MEDIUM_PERFORMANCE_RESOURCES,
    COUNT(*) FILTER (WHERE INFRESPERFORMANCETIER = 'LOW') AS LOW_PERFORMANCE_RESOURCES,
    
    -- Contadores de proveedores y clusters
    (SELECT COUNT(DISTINCT INFRESPROVIDERID) FROM INFCLOUDRESOURCES WHERE INFRESPROVIDERID IS NOT NULL) AS TOTAL_PROVIDERS_USED,
    (SELECT COUNT(*) FROM INFCLOUDPROVIDERS) AS TOTAL_PROVIDERS,
    (SELECT COUNT(*) FROM INFKUBERNETESCLUSTERS) AS TOTAL_CLUSTERS,
    
    -- Totales de otros componentes
    (SELECT COUNT(*) FROM INFMETRICS) AS TOTAL_METRICS_ALL,
    (SELECT COUNT(*) FROM INFAUDITS) AS TOTAL_AUDITS_ALL,
    (SELECT COUNT(*) FROM INFCOSTS) AS TOTAL_COST_RECORDS,
    
    -- Timestamp de generación
    NOW() AS GENERATED_AT

FROM INFCLOUDRESOURCES r;

COMMENT ON VIEW V_INFRASTRUCTURE_METRICS_SUMMARY IS 'Vista para métricas globales del módulo de infraestructura cloud';

