-- ============================================================================
-- VIEWS - PROMPTS MODULE
-- ============================================================================

-- Vista para listado de prompts con todas las métricas calculadas
DROP VIEW IF EXISTS V_PROMPTS_OVERVIEW CASCADE;

CREATE VIEW V_PROMPTS_OVERVIEW AS
SELECT 
    -- Campos del prompt (SOLO LOS QUE EXISTEN EN PRMPROMPTS)
    p.IDXPROMPT,
    p.PRMNAME,
    p.PRMDESCRIPTION,
    p.PRMTYPE,
    p.PRMCATEGORY,
    p.PRMVERSION,
    p.PRMSTATUS,
    p.PRMCONTENT,
    p.PRMPARAMETERS,
    p.PRMMETADATA,
    p.PRMAPPROVALSTATUS,
    p.PRMAPPROVEDBY,
    p.PRMAPPROVEDAT,
    p.PRMCREATEDBY,
    p.PRMUPDATEDBY,
    p.PRMCREATEDAT,
    p.PRMUPDATEDAT,
    
    -- Contadores calculados (mejora performance)
    (SELECT COUNT(*) FROM PRMPROMPTVERSIONS pv WHERE pv.IDPRMPROMPTS0 = p.IDXPROMPT) AS TOTAL_VERSIONS,
    (SELECT COUNT(*) FROM PRMPROMPTVALIDATIONS pvl WHERE pvl.IDPRMPROMPTS0 = p.IDXPROMPT) AS TOTAL_VALIDATIONS,
    
    -- Última validación
    (SELECT pvl.PRMVALIDATIONSCORE 
     FROM PRMPROMPTVALIDATIONS pvl 
     WHERE pvl.IDPRMPROMPTS0 = p.IDXPROMPT 
     ORDER BY pvl.PRMVALIDATEDAT DESC 
     LIMIT 1) AS LAST_VALIDATION_SCORE,
     
    -- Última fecha de validación
    (SELECT pvl.PRMVALIDATEDAT 
     FROM PRMPROMPTVALIDATIONS pvl 
     WHERE pvl.IDPRMPROMPTS0 = p.IDXPROMPT 
     ORDER BY pvl.PRMVALIDATEDAT DESC 
     LIMIT 1) AS LAST_VALIDATION_DATE,
     
    -- Score promedio de validaciones
    (SELECT AVG(pvl.PRMVALIDATIONSCORE) 
     FROM PRMPROMPTVALIDATIONS pvl 
     WHERE pvl.IDPRMPROMPTS0 = p.IDXPROMPT 
       AND pvl.PRMVALIDATIONSCORE IS NOT NULL) AS AVERAGE_VALIDATION_SCORE,
       
    -- Validaciones fallidas
    (SELECT COUNT(*) 
     FROM PRMPROMPTVALIDATIONS pvl 
     WHERE pvl.IDPRMPROMPTS0 = p.IDXPROMPT 
       AND pvl.PRMVALIDATIONRESULT = 'FAILED') AS FAILED_VALIDATIONS

FROM PRMPROMPTS p;

-- Comentario en la vista
COMMENT ON VIEW V_PROMPTS_OVERVIEW IS 'Vista optimizada para listado de prompts con métricas calculadas';


-- ============================================================================
-- Vista para métricas globales del módulo Prompts
-- ============================================================================

DROP VIEW IF EXISTS V_PROMPTS_METRICS_SUMMARY CASCADE;

CREATE VIEW V_PROMPTS_METRICS_SUMMARY AS
SELECT 
    -- Contadores totales
    COUNT(*) AS TOTAL_PROMPTS,
    COUNT(*) FILTER (WHERE 'ACTIVE' = ANY(PRMSTATUS)) AS ACTIVE_PROMPTS,
    COUNT(*) FILTER (WHERE 'DRAFT' = ANY(PRMSTATUS)) AS DRAFT_PROMPTS,
    COUNT(*) FILTER (WHERE 'PENDING' = ANY(PRMAPPROVALSTATUS)) AS PENDING_APPROVAL,
    COUNT(*) FILTER (WHERE 'APPROVED' = ANY(PRMAPPROVALSTATUS)) AS APPROVED_PROMPTS,
    COUNT(*) FILTER (WHERE 'REJECTED' = ANY(PRMAPPROVALSTATUS)) AS REJECTED_PROMPTS,
    
    -- Métricas por tipo
    COUNT(*) FILTER (WHERE 'SYSTEM' = ANY(PRMTYPE)) AS SYSTEM_PROMPTS,
    COUNT(*) FILTER (WHERE 'USER' = ANY(PRMTYPE)) AS USER_PROMPTS,
    COUNT(*) FILTER (WHERE 'ASSISTANT' = ANY(PRMTYPE)) AS ASSISTANT_PROMPTS,
    COUNT(*) FILTER (WHERE 'FUNCTION' = ANY(PRMTYPE)) AS FUNCTION_PROMPTS,
    
    -- Métricas calculadas
    (SELECT AVG(pvl.PRMVALIDATIONSCORE) 
     FROM PRMPROMPTVALIDATIONS pvl 
     WHERE pvl.PRMVALIDATIONSCORE IS NOT NULL) AS AVERAGE_VALIDATION_SCORE,
    
    (SELECT COUNT(*) 
     FROM PRMPROMPTVALIDATIONS pvl 
     WHERE pvl.PRMVALIDATIONRESULT = 'PASSED') AS TOTAL_PASSED_VALIDATIONS,
    
    (SELECT COUNT(*) 
     FROM PRMPROMPTVALIDATIONS pvl 
     WHERE pvl.PRMVALIDATIONRESULT = 'FAILED') AS TOTAL_FAILED_VALIDATIONS,
    
    -- Totales de versiones
    (SELECT COUNT(*) FROM PRMPROMPTVERSIONS) AS TOTAL_VERSIONS_ALL,
    (SELECT COUNT(*) FROM PRMPROMPTVALIDATIONS) AS TOTAL_VALIDATIONS_ALL,
    
    -- Timestamp de generación
    NOW() AS GENERATED_AT

FROM PRMPROMPTS p;

COMMENT ON VIEW V_PROMPTS_METRICS_SUMMARY IS 'Vista para métricas globales del módulo de prompts';

