-- ============================================================================
-- VIEWS - MODEL PROVIDERS MODULE
-- ============================================================================

-- Vista para listado de proveedores de modelos con métricas calculadas
DROP VIEW IF EXISTS V_PROVIDERS_OVERVIEW CASCADE;

CREATE VIEW V_PROVIDERS_OVERVIEW AS
SELECT 
    -- Campos del proveedor (SOLO LOS QUE EXISTEN EN MODPROVIDERS)
    p.IDXMODELPROVIDER,
    p.MODNAME,
    p.MODDISPLAYNAME,
    p.MODDESCRIPTION,
    p.MODPROVIDERTYPE,
    p.MODBASEURL,
    p.MODAPIVERSION,
    p.MODSTATUS,
    p.MODPRICINGMODEL,
    p.MODPRICINGDETAILS,
    p.MODHASFREETIER,
    p.MODAUTHTYPE,
    p.MODAUTHCONFIG,
    p.MODSUPPORTSTEXT,
    p.MODSUPPORTSEMBEDDINGS,
    p.MODSUPPORTSAUDIO,
    p.MODSUPPORTSVISION,
    p.MODSUPPORTSMULTIMODAL,
    p.MODSUPPORTSFUNCTIONCALLING,
    p.MODSUPPORTSSTREAMING,
    p.MODSUPPORTSFINETUNING,
    p.MODRATELIMITREQUESTS,
    p.MODRATELIMITTOKENS,
    p.MODMAXCONTEXTLENGTH,
    p.MODMAXOUTPUTTOKENS,
    p.MODAVAILABLEREGIONS,
    p.MODDATARESIDENCY,
    p.MODSLAUPTIME,
    p.MODAVGRESPONSETIMEMS,
    p.MODHEALTHCHECKURL,
    p.MODDOCUMENTATIONURL,
    p.MODCONTACTEMAIL,
    p.MODSUPPORTURL,
    p.MODCREATEDBY,
    p.MODUPDATEDBY,
    p.MODCREATEDAT,
    p.MODUPDATEDAT,
    
    -- Contadores calculados (mejora performance)
    (SELECT COUNT(*) FROM MODCATALOG mc WHERE mc.IDMODPROVIDERS0 = p.IDXMODELPROVIDER) AS TOTAL_MODELS,
    (SELECT COUNT(*) FROM MODCATALOG mc WHERE mc.IDMODPROVIDERS0 = p.IDXMODELPROVIDER AND 'AVAILABLE' = ANY(mc.MODSTATUS)) AS ACTIVE_MODELS,
    (SELECT COUNT(*) FROM MODPROVIDERCREDENTIALS cred WHERE cred.IDMODPROVIDERS0 = p.IDXMODELPROVIDER) AS TOTAL_CREDENTIALS,
    (SELECT COUNT(*) FROM MODPROVIDERCREDENTIALS cred WHERE cred.IDMODPROVIDERS0 = p.IDXMODELPROVIDER AND 'ACTIVE' = ANY(cred.MODSTATUS)) AS ACTIVE_CREDENTIALS,
    
    -- Última credencial usada
    (SELECT MAX(cred.MODLASTUSEDAT) FROM MODPROVIDERCREDENTIALS cred WHERE cred.IDMODPROVIDERS0 = p.IDXMODELPROVIDER) AS LAST_CREDENTIAL_USE,
    
    -- Total de uso de credenciales
    (SELECT COALESCE(SUM(cred.MODUSAGECOUNT), 0) FROM MODPROVIDERCREDENTIALS cred WHERE cred.IDMODPROVIDERS0 = p.IDXMODELPROVIDER) AS TOTAL_CREDENTIAL_USAGE

FROM MODPROVIDERS p;

-- Comentario en la vista
COMMENT ON VIEW V_PROVIDERS_OVERVIEW IS 'Vista optimizada para listado de proveedores de modelos con métricas calculadas';


-- ============================================================================
-- Vista para métricas globales del módulo MODEL PROVIDERS
-- ============================================================================

DROP VIEW IF EXISTS V_PROVIDERS_METRICS_SUMMARY CASCADE;

CREATE VIEW V_PROVIDERS_METRICS_SUMMARY AS
SELECT 
    -- Contadores totales de proveedores
    COUNT(*) AS TOTAL_PROVIDERS,
    COUNT(*) FILTER (WHERE 'ACTIVE' = ANY(MODSTATUS)) AS ACTIVE_PROVIDERS,
    COUNT(*) FILTER (WHERE 'INACTIVE' = ANY(MODSTATUS)) AS INACTIVE_PROVIDERS,
    COUNT(*) FILTER (WHERE 'DEPRECATED' = ANY(MODSTATUS)) AS DEPRECATED_PROVIDERS,
    
    -- Métricas por tipo de proveedor
    COUNT(*) FILTER (WHERE 'OPENAI' = ANY(MODPROVIDERTYPE)) AS OPENAI_PROVIDERS,
    COUNT(*) FILTER (WHERE 'ANTHROPIC' = ANY(MODPROVIDERTYPE)) AS ANTHROPIC_PROVIDERS,
    COUNT(*) FILTER (WHERE 'HUGGINGFACE' = ANY(MODPROVIDERTYPE)) AS HUGGINGFACE_PROVIDERS,
    COUNT(*) FILTER (WHERE 'AZURE' = ANY(MODPROVIDERTYPE)) AS AZURE_PROVIDERS,
    COUNT(*) FILTER (WHERE 'AWS' = ANY(MODPROVIDERTYPE)) AS AWS_PROVIDERS,
    COUNT(*) FILTER (WHERE 'GOOGLE' = ANY(MODPROVIDERTYPE)) AS GOOGLE_PROVIDERS,
    COUNT(*) FILTER (WHERE 'CUSTOM' = ANY(MODPROVIDERTYPE)) AS CUSTOM_PROVIDERS,
    
    -- Capacidades
    COUNT(*) FILTER (WHERE MODSUPPORTSTEXT = true) AS SUPPORTS_TEXT,
    COUNT(*) FILTER (WHERE MODSUPPORTSEMBEDDINGS = true) AS SUPPORTS_EMBEDDINGS,
    COUNT(*) FILTER (WHERE MODSUPPORTSVISION = true) AS SUPPORTS_VISION,
    COUNT(*) FILTER (WHERE MODSUPPORTSMULTIMODAL = true) AS SUPPORTS_MULTIMODAL,
    COUNT(*) FILTER (WHERE MODSUPPORTSFUNCTIONCALLING = true) AS SUPPORTS_FUNCTION_CALLING,
    COUNT(*) FILTER (WHERE MODSUPPORTSFINETUNING = true) AS SUPPORTS_FINETUNING,
    
    -- Proveedores con free tier
    COUNT(*) FILTER (WHERE MODHASFREETIER = true) AS PROVIDERS_WITH_FREE_TIER,
    
    -- Totales de modelos y credenciales
    (SELECT COUNT(*) FROM MODCATALOG) AS TOTAL_MODELS_ALL,
    (SELECT COUNT(*) FROM MODPROVIDERCREDENTIALS) AS TOTAL_CREDENTIALS_ALL,
    (SELECT COUNT(*) FROM MODPROVIDERCREDENTIALS WHERE 'ACTIVE' = ANY(MODSTATUS)) AS ACTIVE_CREDENTIALS_ALL,
    
    -- Métricas de rendimiento promedio
    AVG(MODSLAUPTIME) AS AVG_SLA_UPTIME,
    AVG(MODAVGRESPONSETIMEMS) AS AVG_RESPONSE_TIME_MS,
    
    -- Timestamp de generación
    NOW() AS GENERATED_AT

FROM MODPROVIDERS p;

COMMENT ON VIEW V_PROVIDERS_METRICS_SUMMARY IS 'Vista para métricas globales del módulo de proveedores de modelos';

