"use client";

import { useTranslation } from "@/app/config/i18n";
import { Button } from "@/components/ui/button";
import { Card, CardBody, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";
import { ArrowLeft, Package, Save } from "lucide-react";
import { useState } from "react";

interface AgentFormData {
  name: string;
  description: string;
  domain: string;
  version: string;
  status: string;
}

export default function AgentCreatePage() {
  const { t, mounted } = useTranslation();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formData, setFormData] = useState<AgentFormData>({
    name: "",
    description: "",
    domain: "",
    version: "1.0.0",
    status: "DRAFT",
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const response = await fetch("/api/governance/agents/registry", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify(formData),
      });

      if (response.ok) {
        const data = await response.json();
        // Redirigir al detalle del agente creado
        if (data.id) {
          window.location.href = `/agents/registry/${data.id}`;
        } else {
          window.location.href = "/agents/registry";
        }
      } else {
        const error = await response.json();
        alert(t("agents.registry.create.error", "Error al crear el agente: ") + (error.message || "Error desconocido"));
      }
    } catch (error) {
      console.error("Error al crear agente:", error);
      alert(t("agents.registry.create.error", "Error al crear el agente"));
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleCancel = () => {
    window.location.href = "/agents/registry";
  };

  if (!mounted) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="text-center">
          <Package className="w-8 h-8 animate-spin mx-auto mb-2 text-muted-foreground" />
          <p className="text-muted-foreground">{t("common.loading", "Cargando...")}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <Button
            variant="ghost"
            size="sm"
            className="h-8 w-8 p-0"
            onClick={handleCancel}
            title={t("common.back", "Volver")}
          >
            <ArrowLeft className="h-4 w-4" />
          </Button>
          <div className="space-y-1">
            <div className="flex items-center gap-3">
              <Package className="w-6 h-6 text-primary" />
              <h1 className="text-2xl font-bold text-foreground">
                {t("agents.registry.create.title", "Registrar Nuevo Agente")}
              </h1>
            </div>
            <p className="text-sm text-muted-foreground ml-9">
              {t("agents.registry.create.subtitle", "Complete el formulario para registrar un nuevo agente")}
            </p>
          </div>
        </div>
        <div className="flex items-center gap-2">
          <Button
            type="button"
            variant="outline"
            onClick={handleCancel}
            disabled={isSubmitting}
          >
            {t("common.cancel", "Cancelar")}
          </Button>
          <Button
            type="submit"
            form="agent-form"
            className="bg-primary hover:bg-primary/90"
            disabled={isSubmitting}
          >
            <Save className="h-4 w-4 mr-2" />
            {isSubmitting
              ? t("common.saving", "Guardando...")
              : t("agents.registry.create.saveButton", "Guardar Agente")}
          </Button>
        </div>
      </div>

      {/* Formulario */}
      <form id="agent-form" onSubmit={handleSubmit}>
        <Card className="backdrop-blur-md bg-background/60 border-border/50">
          <CardHeader>
            <CardTitle>
              {t("agents.registry.create.formTitle", "Información del Agente")}
            </CardTitle>
          </CardHeader>
          <CardBody className="space-y-4">
            {/* UUID - Solo lectura, no editable */}
            <div className="space-y-2">
              <Label htmlFor="uuid">
                {t("agents.registry.create.uuid", "UUID")}
              </Label>
              <Input
                id="uuid"
                value={t("agents.registry.create.uuidAutoGenerated", "Se generará automáticamente")}
                readOnly
                disabled
                className="bg-muted text-muted-foreground font-mono cursor-not-allowed"
              />
              <p className="text-xs text-muted-foreground">
                {t("agents.registry.create.uuidInfo", "El UUID se generará automáticamente al guardar el agente.")}
              </p>
            </div>

            {/* Nombre */}
            <div className="space-y-2">
              <Label htmlFor="name">
                {t("agents.registry.create.name", "Nombre")} *
              </Label>
              <Input
                id="name"
                value={formData.name}
                onChange={(e) => setFormData({ ...formData, name: e.target.value })}
                placeholder={t("agents.registry.create.namePlaceholder", "Ingrese el nombre del agente")}
                required
              />
            </div>

            {/* Descripción */}
            <div className="space-y-2">
              <Label htmlFor="description">
                {t("agents.registry.create.description", "Descripción")} *
              </Label>
              <Textarea
                id="description"
                value={formData.description}
                onChange={(e) => setFormData({ ...formData, description: e.target.value })}
                placeholder={t("agents.registry.create.descriptionPlaceholder", "Ingrese una descripción del agente")}
                rows={4}
                required
              />
            </div>

            {/* Dominio */}
            <div className="space-y-2">
              <Label htmlFor="domain">
                {t("agents.registry.create.domain", "Dominio")} *
              </Label>
              <Input
                id="domain"
                value={formData.domain}
                onChange={(e) => setFormData({ ...formData, domain: e.target.value })}
                placeholder={t("agents.registry.create.domainPlaceholder", "Ingrese el dominio del agente (ej: Finance, Security)")}
                required
              />
            </div>

            {/* Versión */}
            <div className="space-y-2">
              <Label htmlFor="version">
                {t("agents.registry.create.version", "Versión")} *
              </Label>
              <Input
                id="version"
                value={formData.version}
                onChange={(e) => setFormData({ ...formData, version: e.target.value })}
                placeholder={t("agents.registry.create.versionPlaceholder", "Ingrese la versión (ej: 1.0.0)")}
                required
              />
            </div>

            {/* Estado */}
            <div className="space-y-2">
              <Label htmlFor="status">
                {t("agents.registry.create.status", "Estado")} *
              </Label>
              <Select
                value={formData.status}
                onValueChange={(value) => setFormData({ ...formData, status: value })}>
                <SelectTrigger>
                  <SelectValue placeholder={t("agents.registry.create.statusPlaceholder", "Seleccione el estado")} />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="DRAFT">
                    {t("agents.registry.create.statusDraft", "Borrador")}
                  </SelectItem>
                  <SelectItem value="PENDING">
                    {t("agents.registry.create.statusPending", "Pendiente")}
                  </SelectItem>
                  <SelectItem value="ACTIVE">
                    {t("agents.registry.create.statusActive", "Activo")}
                  </SelectItem>
                  <SelectItem value="INACTIVE">
                    {t("agents.registry.create.statusInactive", "Inactivo")}
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>
          </CardBody>
        </Card>
      </form>
    </div>
  );
}
