-- ============================================================================
-- Seed: Proveedores de modelos AI/ML iniciales
-- Descripción: Población de proveedores principales del mercado
-- Fecha: 2025-10-16
-- ============================================================================

-- Limpiar proveedores existentes (solo en desarrollo)
-- TRUNCATE TABLE MODPROVIDERS CASCADE;

-- OpenAI
INSERT INTO MODPROVIDERS (
    MODNAME, MODDISPLAYNAME, MODDESCRIPTION, MODPROVIDERTYPE, MODBASEURL, MODAPIVERSION,
    MODSTATUS, MODPRICINGMODEL, MODHASFREETIER,
    MODSUPPORTSTEXT, MODSUPPORTSEMBEDDINGS, MODSUPPORTSAUDIO, MODSUPPORTSVISION, 
    MODSUPPORTSMULTIMODAL, MODSUPPORTSFUNCTIONCALLING, MODSUPPORTSSTREAMING, MODSUPPORTSFINETUNING,
    MODCREATEDBY, MODCREATEDAT
) VALUES (
    'openai', 'OpenAI', 'Proveedor de modelos GPT (GPT-4, GPT-3.5, etc.)', 
    ARRAY['COMMERCIAL', 'API'], 'https://api.openai.com/v1', 'v1',
    ARRAY['ACTIVE'], 'PAY_PER_USE', false,
    true, true, true, true, true, true, true, true,
    'system', CURRENT_TIMESTAMP
) ON CONFLICT (MODNAME) DO NOTHING;

-- Anthropic
INSERT INTO MODPROVIDERS (
    MODNAME, MODDISPLAYNAME, MODDESCRIPTION, MODPROVIDERTYPE, MODBASEURL, MODAPIVERSION,
    MODSTATUS, MODPRICINGMODEL, MODHASFREETIER,
    MODSUPPORTSTEXT, MODSUPPORTSEMBEDDINGS, MODSUPPORTSAUDIO, MODSUPPORTSVISION, 
    MODSUPPORTSMULTIMODAL, MODSUPPORTSFUNCTIONCALLING, MODSUPPORTSSTREAMING, MODSUPPORTSFINETUNING,
    MODCREATEDBY, MODCREATEDAT
) VALUES (
    'anthropic', 'Anthropic', 'Proveedor de modelos Claude', 
    ARRAY['COMMERCIAL', 'API'], 'https://api.anthropic.com/v1', 'v1',
    ARRAY['ACTIVE'], 'PAY_PER_USE', false,
    true, false, false, true, true, true, true, false,
    'system', CURRENT_TIMESTAMP
) ON CONFLICT (MODNAME) DO NOTHING;

-- Google
INSERT INTO MODPROVIDERS (
    MODNAME, MODDISPLAYNAME, MODDESCRIPTION, MODPROVIDERTYPE, MODBASEURL, MODAPIVERSION,
    MODSTATUS, MODPRICINGMODEL, MODHASFREETIER,
    MODSUPPORTSTEXT, MODSUPPORTSEMBEDDINGS, MODSUPPORTSAUDIO, MODSUPPORTSVISION, 
    MODSUPPORTSMULTIMODAL, MODSUPPORTSFUNCTIONCALLING, MODSUPPORTSSTREAMING, MODSUPPORTSFINETUNING,
    MODCREATEDBY, MODCREATEDAT
) VALUES (
    'google', 'Google AI', 'Proveedor de modelos Gemini', 
    ARRAY['COMMERCIAL', 'API'], 'https://generativelanguage.googleapis.com/v1', 'v1',
    ARRAY['ACTIVE'], 'PAY_PER_USE', true,
    true, true, true, true, true, true, true, false,
    'system', CURRENT_TIMESTAMP
) ON CONFLICT (MODNAME) DO NOTHING;

-- Meta
INSERT INTO MODPROVIDERS (
    MODNAME, MODDISPLAYNAME, MODDESCRIPTION, MODPROVIDERTYPE, MODBASEURL, MODAPIVERSION,
    MODSTATUS, MODPRICINGMODEL, MODHASFREETIER,
    MODSUPPORTSTEXT, MODSUPPORTSEMBEDDINGS, MODSUPPORTSAUDIO, MODSUPPORTSVISION, 
    MODSUPPORTSMULTIMODAL, MODSUPPORTSFUNCTIONCALLING, MODSUPPORTSSTREAMING, MODSUPPORTSFINETUNING,
    MODCREATEDBY, MODCREATEDAT
) VALUES (
    'meta', 'Meta (Facebook)', 'Proveedor de modelos Llama', 
    ARRAY['OPEN_SOURCE', 'SELF_HOSTED'], null, null,
    ARRAY['ACTIVE'], 'FREE', true,
    true, false, false, false, false, false, false, true,
    'system', CURRENT_TIMESTAMP
) ON CONFLICT (MODNAME) DO NOTHING;

-- Mistral AI
INSERT INTO MODPROVIDERS (
    MODNAME, MODDISPLAYNAME, MODDESCRIPTION, MODPROVIDERTYPE, MODBASEURL, MODAPIVERSION,
    MODSTATUS, MODPRICINGMODEL, MODHASFREETIER,
    MODSUPPORTSTEXT, MODSUPPORTSEMBEDDINGS, MODSUPPORTSAUDIO, MODSUPPORTSVISION, 
    MODSUPPORTSMULTIMODAL, MODSUPPORTSFUNCTIONCALLING, MODSUPPORTSSTREAMING, MODSUPPORTSFINETUNING,
    MODCREATEDBY, MODCREATEDAT
) VALUES (
    'mistral', 'Mistral AI', 'Proveedor de modelos Mistral', 
    ARRAY['COMMERCIAL', 'API'], 'https://api.mistral.ai/v1', 'v1',
    ARRAY['ACTIVE'], 'PAY_PER_USE', false,
    true, true, false, false, false, true, true, false,
    'system', CURRENT_TIMESTAMP
) ON CONFLICT (MODNAME) DO NOTHING;

-- Cohere
INSERT INTO MODPROVIDERS (
    MODNAME, MODDISPLAYNAME, MODDESCRIPTION, MODPROVIDERTYPE, MODBASEURL, MODAPIVERSION,
    MODSTATUS, MODPRICINGMODEL, MODHASFREETIER,
    MODSUPPORTSTEXT, MODSUPPORTSEMBEDDINGS, MODSUPPORTSAUDIO, MODSUPPORTSVISION, 
    MODSUPPORTSMULTIMODAL, MODSUPPORTSFUNCTIONCALLING, MODSUPPORTSSTREAMING, MODSUPPORTSFINETUNING,
    MODCREATEDBY, MODCREATEDAT
) VALUES (
    'cohere', 'Cohere', 'Proveedor de modelos especializados en embeddings', 
    ARRAY['COMMERCIAL', 'API'], 'https://api.cohere.ai/v1', 'v1',
    ARRAY['ACTIVE'], 'PAY_PER_USE', true,
    true, true, false, false, false, false, false, false,
    'system', CURRENT_TIMESTAMP
) ON CONFLICT (MODNAME) DO NOTHING;

-- HuggingFace
INSERT INTO MODPROVIDERS (
    MODNAME, MODDISPLAYNAME, MODDESCRIPTION, MODPROVIDERTYPE, MODBASEURL, MODAPIVERSION,
    MODSTATUS, MODPRICINGMODEL, MODHASFREETIER,
    MODSUPPORTSTEXT, MODSUPPORTSEMBEDDINGS, MODSUPPORTSAUDIO, MODSUPPORTSVISION, 
    MODSUPPORTSMULTIMODAL, MODSUPPORTSFUNCTIONCALLING, MODSUPPORTSSTREAMING, MODSUPPORTSFINETUNING,
    MODCREATEDBY, MODCREATEDAT
) VALUES (
    'huggingface', 'HuggingFace', 'Plataforma de modelos open source', 
    ARRAY['OPEN_SOURCE', 'MARKETPLACE'], 'https://api-inference.huggingface.co', 'v1',
    ARRAY['ACTIVE'], 'FREEMIUM', true,
    true, true, true, true, true, false, false, true,
    'system', CURRENT_TIMESTAMP
) ON CONFLICT (MODNAME) DO NOTHING;

-- Verificación
SELECT 
    idxmodelprovider,
    modname,
    moddisplayname,
    modstatus,
    modsupportstext,
    modsupportsvision,
    modsupportsmultimodal
FROM MODPROVIDERS
ORDER BY moddisplayname;

