-- ============================================================================
-- Agregar columnas FK faltantes en las tablas
-- Generado desde validación de JPAs vs SQL
-- Fecha: 2025-10-16
-- ============================================================================

-- Tabla: AGTAGENTALERTS
ALTER TABLE AGTAGENTALERTS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTAPPROVALS
ALTER TABLE AGTAGENTAPPROVALS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTBIASDETECTIONS
ALTER TABLE AGTAGENTBIASDETECTIONS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTCOLLABORATIONS
ALTER TABLE AGTAGENTCOLLABORATIONS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTCOMMUNICATIONS
ALTER TABLE AGTAGENTCOMMUNICATIONS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTCOMPLIANCE
ALTER TABLE AGTAGENTCOMPLIANCE ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTDECISIONS
ALTER TABLE AGTAGENTDECISIONS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTDEPLOYMENTS
ALTER TABLE AGTAGENTDEPLOYMENTS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTETHICSASSESSMENTS
ALTER TABLE AGTAGENTETHICSASSESSMENTS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTEXPERTISE
ALTER TABLE AGTAGENTEXPERTISE ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;
ALTER TABLE AGTAGENTEXPERTISE ADD COLUMN IF NOT EXISTS IDAGTAGENTDOMAINS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTGOVERNANCE
ALTER TABLE AGTAGENTGOVERNANCE ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTHEALTH
ALTER TABLE AGTAGENTHEALTH ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTINTERACTIONS
ALTER TABLE AGTAGENTINTERACTIONS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTMONITORING
ALTER TABLE AGTAGENTMONITORING ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTROLLBACKS
ALTER TABLE AGTAGENTROLLBACKS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;
ALTER TABLE AGTAGENTROLLBACKS ADD COLUMN IF NOT EXISTS IDAGTAGENTDEPLOYMENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTTOOLS
ALTER TABLE AGTAGENTTOOLS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTTRANSPARENCY
ALTER TABLE AGTAGENTTRANSPARENCY ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTAGENTVERSIONS
ALTER TABLE AGTAGENTVERSIONS ADD COLUMN IF NOT EXISTS IDAGTAGENTS0 BIGINT NOT NULL;

-- Tabla: AGTWORKFLOWEXECUTIONS
ALTER TABLE AGTWORKFLOWEXECUTIONS ADD COLUMN IF NOT EXISTS IDAGTAGENTWORKFLOWS0 BIGINT NOT NULL;

-- Tabla: AUDITLOGS
ALTER TABLE AUDITLOGS ADD COLUMN IF NOT EXISTS IDCORUSERS0 BIGINT NULL;

-- Tabla: CATARTIFACTDEPENDENCIES
ALTER TABLE CATARTIFACTDEPENDENCIES ADD COLUMN IF NOT EXISTS IDCATBASEARTIFACTS0 BIGINT NULL;

-- Tabla: CATARTIFACTVERSIONS
ALTER TABLE CATARTIFACTVERSIONS ADD COLUMN IF NOT EXISTS IDCATBASEARTIFACTS0 BIGINT NULL;

-- Tabla: CORUSERS
ALTER TABLE CORUSERS ADD COLUMN IF NOT EXISTS IDCORDEPARTMENTS0 BIGINT NULL;

-- Tabla: CORUSERSESSIONS
ALTER TABLE CORUSERSESSIONS ADD COLUMN IF NOT EXISTS IDCORUSERS0 BIGINT NOT NULL;

-- Tabla: GOVBIASDETECTIONS
ALTER TABLE GOVBIASDETECTIONS ADD COLUMN IF NOT EXISTS IDGOVBIASANALYSIS0 BIGINT NOT NULL;

-- Tabla: GOVBIASRECOMMENDATIONS
ALTER TABLE GOVBIASRECOMMENDATIONS ADD COLUMN IF NOT EXISTS IDGOVBIASANALYSIS0 BIGINT NOT NULL;

-- Tabla: GOVCOMPLIANCEFINDINGS
ALTER TABLE GOVCOMPLIANCEFINDINGS ADD COLUMN IF NOT EXISTS IDGOVCOMPLIANCEASSESSMENTS0 BIGINT NOT NULL;

-- Tabla: GOVCOMPLIANCEREQUIREMENTS
ALTER TABLE GOVCOMPLIANCEREQUIREMENTS ADD COLUMN IF NOT EXISTS IDGOVCOMPLIANCEASSESSMENTS0 BIGINT NOT NULL;

-- Tabla: GOVEVALUATIONMETRICS
ALTER TABLE GOVEVALUATIONMETRICS ADD COLUMN IF NOT EXISTS IDGOVMODELEVALUATIONS0 BIGINT NOT NULL;

-- Tabla: GOVFAIRNESSMETRICS
ALTER TABLE GOVFAIRNESSMETRICS ADD COLUMN IF NOT EXISTS IDGOVBIASANALYSIS0 BIGINT NOT NULL;

-- Tabla: GOVPOLICYAUDITLOGS
ALTER TABLE GOVPOLICYAUDITLOGS ADD COLUMN IF NOT EXISTS IDGOVPOLICIES0 BIGINT NOT NULL;

-- Tabla: GOVPOLICYCHECKLISTITEMS
ALTER TABLE GOVPOLICYCHECKLISTITEMS ADD COLUMN IF NOT EXISTS IDGOVPOLICIES0 BIGINT NOT NULL;

-- Tabla: GOVPOLICYEVALUATIONS
ALTER TABLE GOVPOLICYEVALUATIONS ADD COLUMN IF NOT EXISTS IDGOVPOLICIES0 BIGINT NOT NULL;

-- Tabla: GOVPOLICYRULES
ALTER TABLE GOVPOLICYRULES ADD COLUMN IF NOT EXISTS IDGOVPOLICIES0 BIGINT NOT NULL;

-- Tabla: GOVPROJECTARTIFACTS
ALTER TABLE GOVPROJECTARTIFACTS ADD COLUMN IF NOT EXISTS IDPRJPROJECTS0 BIGINT NOT NULL;

-- Tabla: GOVPROJECTMEMBERS
ALTER TABLE GOVPROJECTMEMBERS ADD COLUMN IF NOT EXISTS IDPRJPROJECTS0 BIGINT NOT NULL;

-- Tabla: MODCAPABILITIES
ALTER TABLE MODCAPABILITIES ADD COLUMN IF NOT EXISTS IDMODCATALOG0 BIGINT NOT NULL;

-- Tabla: MODCATALOG
ALTER TABLE MODCATALOG ADD COLUMN IF NOT EXISTS IDMODPROVIDERS0 BIGINT NOT NULL;

-- Tabla: MODENDPOINTS
ALTER TABLE MODENDPOINTS ADD COLUMN IF NOT EXISTS IDMODCATALOG0 BIGINT NOT NULL;

-- Tabla: MODMODELARTIFACTS
ALTER TABLE MODMODELARTIFACTS ADD COLUMN IF NOT EXISTS IDMODMODELS0 BIGINT NOT NULL;
ALTER TABLE MODMODELARTIFACTS ADD COLUMN IF NOT EXISTS IDMODMODELVERSIONS0 BIGINT NULL;

-- Tabla: MODMODELBIASANALYSES
ALTER TABLE MODMODELBIASANALYSES ADD COLUMN IF NOT EXISTS IDMODMODELS0 BIGINT NOT NULL;

-- Tabla: MODMODELDEPENDENCIES
ALTER TABLE MODMODELDEPENDENCIES ADD COLUMN IF NOT EXISTS IDMODMODELS0 BIGINT NOT NULL;

-- Tabla: MODMODELPERFORMANCES
ALTER TABLE MODMODELPERFORMANCES ADD COLUMN IF NOT EXISTS IDMODMODELS0 BIGINT NOT NULL;

-- Tabla: MODMODELS
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS IDMODPROVIDER BIGINT NULL;

-- Tabla: MODMODELSTAGETRANSITIONS
ALTER TABLE MODMODELSTAGETRANSITIONS ADD COLUMN IF NOT EXISTS IDMODMODELS0 BIGINT NOT NULL;
ALTER TABLE MODMODELSTAGETRANSITIONS ADD COLUMN IF NOT EXISTS IDMODMODELVERSIONS0 BIGINT NOT NULL;

-- Tabla: MODMODELVALIDATIONS
ALTER TABLE MODMODELVALIDATIONS ADD COLUMN IF NOT EXISTS IDMODMODELS0 BIGINT NOT NULL;
ALTER TABLE MODMODELVALIDATIONS ADD COLUMN IF NOT EXISTS IDMODMODELVERSIONS0 BIGINT NOT NULL;

-- Tabla: MODMODELVERSIONS
ALTER TABLE MODMODELVERSIONS ADD COLUMN IF NOT EXISTS IDMODMODELS0 BIGINT NOT NULL;

-- Tabla: MODPROVIDERCREDENTIALS
ALTER TABLE MODPROVIDERCREDENTIALS ADD COLUMN IF NOT EXISTS IDMODPROVIDERS0 BIGINT NOT NULL;

-- Tabla: MODUSAGE
ALTER TABLE MODUSAGE ADD COLUMN IF NOT EXISTS IDMODCATALOG0 BIGINT NOT NULL;

-- Tabla: NTFLOGS
ALTER TABLE NTFLOGS ADD COLUMN IF NOT EXISTS IDNTFNOTIFICATIONS0 BIGINT NOT NULL;
ALTER TABLE NTFLOGS ADD COLUMN IF NOT EXISTS IDNTFCHANNELS0 BIGINT NOT NULL;

-- Tabla: NTFNOTIFICATIONS
ALTER TABLE NTFNOTIFICATIONS ADD COLUMN IF NOT EXISTS IDNTFCHANNELS0 BIGINT NULL;
ALTER TABLE NTFNOTIFICATIONS ADD COLUMN IF NOT EXISTS IDNTFTEMPLATES0 BIGINT NULL;

-- Tabla: PRJBILLINGDETAILS
ALTER TABLE PRJBILLINGDETAILS ADD COLUMN IF NOT EXISTS IDPRJCOSTESTIMATORS0 BIGINT NOT NULL;

-- Tabla: PRJINVOICES
ALTER TABLE PRJINVOICES ADD COLUMN IF NOT EXISTS IDPRJCOSTESTIMATORS0 BIGINT NULL;

-- Tabla: PRJPROJECTTECHNOLOGIES
ALTER TABLE PRJPROJECTTECHNOLOGIES ADD COLUMN IF NOT EXISTS IDPRJPROJECTS0 BIGINT NOT NULL;

-- Tabla: PRMPROMPTVALIDATIONS
ALTER TABLE PRMPROMPTVALIDATIONS ADD COLUMN IF NOT EXISTS IDPRMPROMPTS0 BIGINT NOT NULL;

-- Tabla: PRMPROMPTVERSIONS
ALTER TABLE PRMPROMPTVERSIONS ADD COLUMN IF NOT EXISTS IDPRMPROMPTS0 BIGINT NOT NULL;

-- Tabla: RAGRAGDATASOURCES
ALTER TABLE RAGRAGDATASOURCES ADD COLUMN IF NOT EXISTS IDRAGRAGSYSTEMS0 BIGINT NOT NULL;

-- Tabla: RAGRAGVERSIONS
ALTER TABLE RAGRAGVERSIONS ADD COLUMN IF NOT EXISTS IDRAGRAGSYSTEMS0 BIGINT NOT NULL;

-- Tabla: SRVDEPLOYMENTS
ALTER TABLE SRVDEPLOYMENTS ADD COLUMN IF NOT EXISTS IDMODMODELS0 BIGINT NOT NULL;

-- Tabla: SRVMODELMETRICS
ALTER TABLE SRVMODELMETRICS ADD COLUMN IF NOT EXISTS IDMODMODELS0 BIGINT NULL;
ALTER TABLE SRVMODELMETRICS ADD COLUMN IF NOT EXISTS IDSRVDEPLOYMENTS0 BIGINT NULL;

-- Tabla: SRVMODELVERSIONS
ALTER TABLE SRVMODELVERSIONS ADD COLUMN IF NOT EXISTS IDMODMODELS0 BIGINT NOT NULL;

-- Tabla: SRVPREDICTIONS
ALTER TABLE SRVPREDICTIONS ADD COLUMN IF NOT EXISTS IDSRVDEPLOYMENTS0 BIGINT NOT NULL;

-- Tabla: TRNCHECKPOINTS
ALTER TABLE TRNCHECKPOINTS ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NOT NULL;

-- Tabla: TRNENVIRONMENTS
ALTER TABLE TRNENVIRONMENTS ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NOT NULL;

-- Tabla: TRNEXPERIMENTLINEAGE
ALTER TABLE TRNEXPERIMENTLINEAGE ADD COLUMN IF NOT EXISTS IDTRNEXPERIMENTS0 BIGINT NOT NULL;

-- Tabla: TRNHPOEXPERIMENTS
ALTER TABLE TRNHPOEXPERIMENTS ADD COLUMN IF NOT EXISTS IDTRNEXPERIMENTS0 BIGINT NOT NULL;

-- Tabla: TRNHPOTRIALS
ALTER TABLE TRNHPOTRIALS ADD COLUMN IF NOT EXISTS IDTRNHPOEXPERIMENTS0 BIGINT NOT NULL;
ALTER TABLE TRNHPOTRIALS ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NULL;

-- Tabla: TRNMETRICSERIES
ALTER TABLE TRNMETRICSERIES ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NOT NULL;

-- Tabla: TRNMETRICSTREAMS
ALTER TABLE TRNMETRICSTREAMS ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NOT NULL;

-- Tabla: TRNPARAMS
ALTER TABLE TRNPARAMS ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NOT NULL;

-- Tabla: TRNRUNS
ALTER TABLE TRNRUNS ADD COLUMN IF NOT EXISTS IDTRNEXPERIMENTS0 BIGINT NOT NULL;
ALTER TABLE TRNRUNS ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NULL;

-- Tabla: TRNTAGS
ALTER TABLE TRNTAGS ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NOT NULL;

-- Tabla: TRNTRAININGALERTS
ALTER TABLE TRNTRAININGALERTS ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NOT NULL;

-- Tabla: TRNTRAININGARTIFACTS
ALTER TABLE TRNTRAININGARTIFACTS ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NULL;

-- Tabla: TRNTRAININGLOGS
ALTER TABLE TRNTRAININGLOGS ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NULL;

-- Tabla: TRNTRAININGMETRICS
ALTER TABLE TRNTRAININGMETRICS ADD COLUMN IF NOT EXISTS IDTRNRUNS0 BIGINT NULL;

-- Tabla: UPDATEINSTALLATIONS
ALTER TABLE UPDATEINSTALLATIONS ADD COLUMN IF NOT EXISTS IDPLATFORMNODES0 BIGINT NOT NULL;
ALTER TABLE UPDATEINSTALLATIONS ADD COLUMN IF NOT EXISTS IDPLATFORMUPDATES0 BIGINT NOT NULL;

-- Tabla: UPDATESCHEDULES
ALTER TABLE UPDATESCHEDULES ADD COLUMN IF NOT EXISTS IDPLATFORMUPDATES0 BIGINT NOT NULL;
ALTER TABLE UPDATESCHEDULES ADD COLUMN IF NOT EXISTS IDCORUSERS0 BIGINT NULL;
