-- ========================================
-- PATCH 06: EU AI ACT COMPLIANCE - MODEL EXTENSIONS
-- Art. 6, 11, 15, 51
-- Fecha: 2 nov 2025
-- ========================================

-- Extensión tabla MODMODELS con campos EU AI Act

-- Documentación Técnica (Art. 11, Anexo IV)
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODTECHNICALDOCURL VARCHAR(500);
COMMENT ON COLUMN MODMODELS.MODTECHNICALDOCURL IS 'URL documentación técnica Anexo IV';

ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODTECHNICALDOCVERSION VARCHAR(20);
COMMENT ON COLUMN MODMODELS.MODTECHNICALDOCVERSION IS 'Versión de la documentación técnica';

ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODTECHNICALDOCCOMPLETE BOOLEAN DEFAULT FALSE;
COMMENT ON COLUMN MODMODELS.MODTECHNICALDOCCOMPLETE IS 'Indica si Anexo IV está completo';

ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODTECHNICALDOCSCORE NUMERIC(3,2);
COMMENT ON COLUMN MODMODELS.MODTECHNICALDOCSCORE IS 'Score de completitud documentación (0.00-1.00)';

-- Precisión y Rendimiento (Art. 15)
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODACCURACYLEVEL VARCHAR(50);
COMMENT ON COLUMN MODMODELS.MODACCURACYLEVEL IS 'Nivel de precisión: HIGH, MEDIUM, SPECIFIED';

-- Ya existe MODPERFORMANCEMETRICS en la tabla original, no se añade

-- Clasificación Riesgo (Art. 6)
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODISHIGHRISK BOOLEAN DEFAULT FALSE;
COMMENT ON COLUMN MODMODELS.MODISHIGHRISK IS 'Indica si el modelo es de alto riesgo';

ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODANNEXIIICATEGORY VARCHAR(10);
COMMENT ON COLUMN MODMODELS.MODANNEXIIICATEGORY IS 'Categoría Anexo III: III.1, III.2, ..., III.8';

ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODANNEXIIISUBCATEGORY VARCHAR(10);
COMMENT ON COLUMN MODMODELS.MODANNEXIIISUBCATEGORY IS 'Subcategoría específica: III.4.a, III.5.b, etc.';

ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODRISKCATEGORYJUSTIFICATION TEXT;
COMMENT ON COLUMN MODMODELS.MODRISKCATEGORYJUSTIFICATION IS 'Justificación de la clasificación de riesgo';

-- GPAI (Art. 51)
ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODISGPAI BOOLEAN DEFAULT FALSE;
COMMENT ON COLUMN MODMODELS.MODISGPAI IS 'Indica si es modelo GPAI (General Purpose AI)';

ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODGPAIFLOPSTRAINING NUMERIC(30,0);
COMMENT ON COLUMN MODMODELS.MODGPAIFLOPSTRAINING IS 'FLOPs de entrenamiento (operaciones coma flotante)';

ALTER TABLE MODMODELS ADD COLUMN IF NOT EXISTS MODGPAISYSTEMICRISK BOOLEAN DEFAULT FALSE;
COMMENT ON COLUMN MODMODELS.MODGPAISYSTEMICRISK IS 'Indica riesgo sistémico (>10^25 FLOPs)';

-- Índices para búsquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_modmodels_highrisk ON MODMODELS(MODISHIGHRISK);
CREATE INDEX IF NOT EXISTS idx_modmodels_gpai ON MODMODELS(MODISGPAI);
CREATE INDEX IF NOT EXISTS idx_modmodels_annexiii ON MODMODELS(MODANNEXIIICATEGORY);

-- Validación: Si es alto riesgo, debe tener categoría
-- (Se implementa en lógica de negocio, no constraint DB)

COMMIT;

