-- ========================================
-- PATCH 07: EU AI ACT COMPLIANCE - PROJECT EXTENSIONS
-- Art. 5, 6, 49, Anexos I, II, III
-- Fecha: 2 nov 2025
-- ========================================

-- Extensión tabla PRJPROJECTS con campos EU AI Act

-- Clasificación Alto Riesgo (Art. 6)
ALTER TABLE PRJPROJECTS ADD COLUMN IF NOT EXISTS PRJISHIGHRISK BOOLEAN DEFAULT FALSE;
COMMENT ON COLUMN PRJPROJECTS.PRJISHIGHRISK IS 'Indica si el proyecto es de alto riesgo';

ALTER TABLE PRJPROJECTS ADD COLUMN IF NOT EXISTS PRJANNEXIIICATEGORIES JSONB;
COMMENT ON COLUMN PRJPROJECTS.PRJANNEXIIICATEGORIES IS 'Array de categorías Anexo III aplicables (puede ser múltiple)';

ALTER TABLE PRJPROJECTS ADD COLUMN IF NOT EXISTS PRJCLASSIFICATIONDATE TIMESTAMP;
COMMENT ON COLUMN PRJPROJECTS.PRJCLASSIFICATIONDATE IS 'Fecha de clasificación de riesgo';

ALTER TABLE PRJPROJECTS ADD COLUMN IF NOT EXISTS PRJCLASSIFICATIONAUTHOR VARCHAR(100);
COMMENT ON COLUMN PRJPROJECTS.PRJCLASSIFICATIONAUTHOR IS 'Usuario que realizó la clasificación';

-- Sector Regulado (Anexo I)
ALTER TABLE PRJPROJECTS ADD COLUMN IF NOT EXISTS PRJREGULATEDSECTOR BOOLEAN DEFAULT FALSE;
COMMENT ON COLUMN PRJPROJECTS.PRJREGULATEDSECTOR IS 'Indica si está en sector regulado (Anexo I)';

ALTER TABLE PRJPROJECTS ADD COLUMN IF NOT EXISTS PRJANNEXILEGISLATION JSONB;
COMMENT ON COLUMN PRJPROJECTS.PRJANNEXILEGISLATION IS 'Array legislaciones Anexo I: MDR_2017_745, IVDR_2017_746, etc.';

-- Validación Sistemas Prohibidos (Art. 5, Anexo II)
ALTER TABLE PRJPROJECTS ADD COLUMN IF NOT EXISTS PRJPROHIBITEDUSECHECKED BOOLEAN DEFAULT FALSE;
COMMENT ON COLUMN PRJPROJECTS.PRJPROHIBITEDUSECHECKED IS 'Indica si se validó contra Art. 5 (sistemas prohibidos)';

ALTER TABLE PRJPROJECTS ADD COLUMN IF NOT EXISTS PRJPROHIBITEDUSEJUSTIFICATION TEXT;
COMMENT ON COLUMN PRJPROJECTS.PRJPROHIBITEDUSEJUSTIFICATION IS 'Justificación de validación de sistemas prohibidos';

-- Registro Base Datos UE (Art. 49)
ALTER TABLE PRJPROJECTS ADD COLUMN IF NOT EXISTS PRJEUREGISTRATIONID VARCHAR(100) UNIQUE;
COMMENT ON COLUMN PRJPROJECTS.PRJEUREGISTRATIONID IS 'ID único de registro en base de datos UE';

ALTER TABLE PRJPROJECTS ADD COLUMN IF NOT EXISTS PRJEUREGISTRATIONDATE TIMESTAMP;
COMMENT ON COLUMN PRJPROJECTS.PRJEUREGISTRATIONDATE IS 'Fecha de registro en base de datos UE';

ALTER TABLE PRJPROJECTS ADD COLUMN IF NOT EXISTS PRJEUREGISTRATIONSTATUS VARCHAR(20);
COMMENT ON COLUMN PRJPROJECTS.PRJEUREGISTRATIONSTATUS IS 'Estado registro: PENDING, REGISTERED, REJECTED';

-- Índices para búsquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_prjprojects_highrisk ON PRJPROJECTS(PRJISHIGHRISK);
CREATE INDEX IF NOT EXISTS idx_prjprojects_euregstatus ON PRJPROJECTS(PRJEUREGISTRATIONSTATUS);
CREATE INDEX IF NOT EXISTS idx_prjprojects_regulatedsector ON PRJPROJECTS(PRJREGULATEDSECTOR);
CREATE INDEX IF NOT EXISTS idx_prjprojects_eureg ON PRJPROJECTS(PRJEUREGISTRATIONID) WHERE PRJEUREGISTRATIONID IS NOT NULL;

-- Índices GIN para búsquedas en arrays JSONB
CREATE INDEX IF NOT EXISTS idx_prjprojects_annexiii_gin ON PRJPROJECTS USING GIN(PRJANNEXIIICATEGORIES);
CREATE INDEX IF NOT EXISTS idx_prjprojects_annexi_gin ON PRJPROJECTS USING GIN(PRJANNEXILEGISLATION);

COMMIT;

