-- ========================================
-- PATCH 09: EU AI ACT COMPLIANCE - IMMUTABLE LOGS TABLE
-- Art. 19 - Cryptographic Hash Chain Logs
-- Fecha: 2 nov 2025
-- ========================================

-- Tabla IMLIMMUTABLELOGS (si no existe)
CREATE TABLE IF NOT EXISTS IMLIMMUTABLELOGS (
    -- Primary Key
    IDXIMMUTABLELOG BIGSERIAL PRIMARY KEY,
    
    -- UUID estándar
    iduuid VARCHAR(36) NOT NULL UNIQUE,
    
    -- Hash Chain (blockchain-style)
    IMLPREVIOUSHASH VARCHAR(64) NOT NULL,
    IMLCURRENTHASH VARCHAR(64) NOT NULL UNIQUE,
    
    -- Timestamp
    IMLTIMESTAMP TIMESTAMP NOT NULL,
    IMLTIMESTAMPEPOCH BIGINT NOT NULL,
    
    -- Entity Logging
    IMLENTITYTYPE VARCHAR(50) NOT NULL,
    IMLENTITYID BIGINT NOT NULL,
    
    -- Action
    IMLACTION VARCHAR(100) NOT NULL,
    
    -- User
    IMLUSERID BIGINT NOT NULL,
    IMLUSERNAME VARCHAR(100),
    
    -- Data (snapshot completo)
    IMLDATA TEXT NOT NULL,
    
    -- Integrity Verification
    IMLVERIFIED BOOLEAN DEFAULT FALSE,
    IMLINTEGRITYSTATUS VARCHAR(20),
    IMLLASTVERIFICATIONDATE TIMESTAMP,
    
    -- Optional: External Timestamp (RFC 3161)
    IMLEXTERNALTIMESTAMP TEXT,
    
    -- Metadata
    IMLIPADDRESS VARCHAR(45),
    IMLUSERAGENT VARCHAR(200),
    
    -- Audit
    IMLCREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Comentarios
COMMENT ON TABLE IMLIMMUTABLELOGS IS 'Logs inmutables con hash chains según EU AI Act Art. 19 - APPEND ONLY';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IDXIMMUTABLELOG IS 'Primary key autonumérica';
COMMENT ON COLUMN IMLIMMUTABLELOGS.iduuid IS 'UUID único estándar';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLPREVIOUSHASH IS 'SHA-256 hash del log anterior (blockchain chain)';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLCURRENTHASH IS 'SHA-256 hash de este log';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLTIMESTAMP IS 'Timestamp de creación del log';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLTIMESTAMPEPOCH IS 'Unix epoch timestamp para ordenamiento eficiente';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLENTITYTYPE IS 'Tipo de entidad: PROJECT, MODEL, EVALUATION, AGENT, etc.';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLENTITYID IS 'ID de la entidad loggeada';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLACTION IS 'Acción: CREATE, UPDATE, DELETE, EVALUATE, APPROVE, DEPLOY, etc.';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLUSERID IS 'ID del usuario que ejecutó la acción';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLUSERNAME IS 'Nombre usuario (desnormalizado para inmutabilidad)';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLDATA IS 'Snapshot completo del estado en JSON';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLVERIFIED IS 'Si se verificó la integridad';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLINTEGRITYSTATUS IS 'Estado: VALID, TAMPERED, UNVERIFIED, PENDING';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLLASTVERIFICATIONDATE IS 'Fecha última verificación de integridad';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLEXTERNALTIMESTAMP IS 'Timestamp externo (blockchain/TSA proof)';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLIPADDRESS IS 'IP del cliente';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLUSERAGENT IS 'User agent del navegador';
COMMENT ON COLUMN IMLIMMUTABLELOGS.IMLCREATEDAT IS 'Fecha creación (NO actualizable)';

-- Índices para búsquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_iml_entity ON IMLIMMUTABLELOGS(IMLENTITYTYPE, IMLENTITYID);
CREATE INDEX IF NOT EXISTS idx_iml_timestamp ON IMLIMMUTABLELOGS(IMLTIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_iml_epoch ON IMLIMMUTABLELOGS(IMLTIMESTAMPEPOCH);
CREATE INDEX IF NOT EXISTS idx_iml_hash ON IMLIMMUTABLELOGS(IMLCURRENTHASH);
CREATE INDEX IF NOT EXISTS idx_iml_user ON IMLIMMUTABLELOGS(IMLUSERID);
CREATE INDEX IF NOT EXISTS idx_iml_action ON IMLIMMUTABLELOGS(IMLACTION);
CREATE INDEX IF NOT EXISTS idx_iml_integritystatus ON IMLIMMUTABLELOGS(IMLINTEGRITYSTATUS);

-- Índice para ordenamiento por epoch (más eficiente que timestamp)
CREATE INDEX IF NOT EXISTS idx_iml_epoch_desc ON IMLIMMUTABLELOGS(IMLTIMESTAMPEPOCH DESC);

-- Trigger para PREVENIR actualizaciones (CRÍTICO)
CREATE OR REPLACE FUNCTION prevent_immutable_log_update()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'IMMUTABLE LOGS: UPDATE not allowed on IMLIMMUTABLELOGS table. Art. 19 EU AI Act.';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_prevent_update ON IMLIMMUTABLELOGS;
CREATE TRIGGER trigger_prevent_update
    BEFORE UPDATE ON IMLIMMUTABLELOGS
    FOR EACH ROW
    EXECUTE FUNCTION prevent_immutable_log_update();

-- Trigger para PREVENIR deletes (CRÍTICO)
CREATE OR REPLACE FUNCTION prevent_immutable_log_delete()
RETURNS TRIGGER AS $$
BEGIN
    RAISE EXCEPTION 'IMMUTABLE LOGS: DELETE not allowed on IMLIMMUTABLELOGS table. Art. 19 EU AI Act.';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trigger_prevent_delete ON IMLIMMUTABLELOGS;
CREATE TRIGGER trigger_prevent_delete
    BEFORE DELETE ON IMLIMMUTABLELOGS
    FOR EACH ROW
    EXECUTE FUNCTION prevent_immutable_log_delete();

-- Particionamiento por rango de fechas (opcional, para grandes volúmenes)
-- Se puede implementar particionamiento mensual/anual si el volumen lo requiere

COMMIT;

