-- ========================================
-- PATCH 10: EU AI ACT COMPLIANCE - FRIA ASSESSMENT TABLE
-- Art. 27 - Fundamental Rights Impact Assessment
-- Fecha: 2 nov 2025
-- ========================================

-- Tabla FRIAFUNDAMENTALRIGHTSASSESSMENTS (si no existe)
CREATE TABLE IF NOT EXISTS FRIAFUNDAMENTALRIGHTSASSESSMENTS (
    -- Primary Key
    IDXFRIAASSESSMENT BIGSERIAL PRIMARY KEY,
    
    -- UUID estándar
    iduuid VARCHAR(36) NOT NULL UNIQUE,
    
    -- Foreign Keys
    IDXPROJECT BIGINT NOT NULL,
    IDXUSER BIGINT,
    
    -- Art. 27.1.a - Descripción Procesos
    FRIAPROCESSDESCRIPTION TEXT NOT NULL,
    
    -- Art. 27.1.b - Período y Frecuencia
    FRIAUSAGEPERIOD VARCHAR(200),
    FRIAUSAGEFREQUENCY VARCHAR(200),
    
    -- Art. 27.1.c - Categorías Personas Afectadas
    FRIAAFFECTEDCATEGORIES TEXT,
    FRIAVULNERABLEGROUPSINCLUDED BOOLEAN DEFAULT FALSE,
    
    -- Art. 27.1.d - Riesgos Específicos
    FRIARISKS TEXT NOT NULL,
    
    -- Art. 27.1.e - Supervisión Humana
    FRIAHUMANOVERSIGHT TEXT NOT NULL,
    FRIAHITLENABLED BOOLEAN DEFAULT FALSE,
    
    -- Art. 27.1.f - Medidas Mitigación
    FRIAMITI GATIONMEASURES TEXT NOT NULL,
    
    -- Compliance y Quality
    FRIAART27COMPLIANT BOOLEAN DEFAULT FALSE,
    FRIACOMPLETENESSCORE NUMERIC(5,2),
    FRIAQUALSCORE NUMERIC(5,2),
    
    -- Charter UE Analysis
    FRIACHARTERARTICLES TEXT,
    FRIAIMPACTSEVERITY VARCHAR(20),
    
    -- Notificación Autoridad (Art. 27.3)
    FRIANOTIFIED BOOLEAN DEFAULT FALSE,
    FRIANOTIFICATIONID VARCHAR(100),
    FRIANOTIFICATIONDATE TIMESTAMP,
    
    -- Documentación Generada
    FRIADOCUMENTURL VARCHAR(500),
    FRIADOCUMENTVERSION VARCHAR(20),
    
    -- Integración DPIA (Art. 27.4)
    FRIADPIAINTEGRATED BOOLEAN DEFAULT FALSE,
    FRIADPIAID VARCHAR(100),
    
    -- Aprobación
    FRIAAPPROVED BOOLEAN DEFAULT FALSE,
    FRIAAPPROVEDBY BIGINT,
    FRIAAPPROVALDATE TIMESTAMP,
    
    -- Audit Fields
    FRIACREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FRIAUPDATEDAT TIMESTAMP
);

-- Comentarios
COMMENT ON TABLE FRIAFUNDAMENTALRIGHTSASSESSMENTS IS 'FRIA - Evaluación impacto en derechos fundamentales según Art. 27 EU AI Act';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.IDXFRIAASSESSMENT IS 'Primary key autonumérica';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.iduuid IS 'UUID único estándar';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.IDXPROJECT IS 'FK a proyecto de alto riesgo';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.IDXUSER IS 'FK a usuario responsable del despliegue';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAPROCESSDESCRIPTION IS 'Art. 27.1.a - Descripción procesos donde se usa IA';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAUSAGEPERIOD IS 'Art. 27.1.b - Período de uso del sistema';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAUSAGEFREQUENCY IS 'Art. 27.1.b - Frecuencia de uso';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAAFFECTEDCATEGORIES IS 'Art. 27.1.c - Categorías personas afectadas (JSON array)';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAVULNERABLEGROUPSINCLUDED IS 'Si incluye grupos vulnerables';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIARISKS IS 'Art. 27.1.d - Riesgos específicos (JSON array)';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAHUMANOVERSIGHT IS 'Art. 27.1.e - Descripción supervisión humana';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAHITLENABLED IS 'Si tiene HITL (Human-In-The-Loop) habilitado';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAMITI GATIONMEASURES IS 'Art. 27.1.f - Medidas de mitigación (JSON array)';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAART27COMPLIANT IS 'Si cumple completamente Art. 27';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIACOMPLETENESSCORE IS 'Score de completitud (0-100)';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAQUALSCORE IS 'Score de calidad (0-100)';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIACHARTERARTICLES IS 'Artículos Charter UE afectados (JSON array)';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAIMPACTSEVERITY IS 'Severidad impacto: LOW, MEDIUM, HIGH, CRITICAL';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIANOTIFIED IS 'Si se notificó a autoridad (Art. 27.3)';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIANOTIFICATIONID IS 'ID de notificación a autoridad';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIANOTIFICATIONDATE IS 'Fecha de notificación';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIADOCUMENTURL IS 'URL documento FRIA generado';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIADOCUMENTVERSION IS 'Versión documento';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIADPIAINTEGRATED IS 'Si está integrado con DPIA (Art. 27.4)';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIADPIAID IS 'ID de DPIA asociado';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAAPPROVED IS 'Si está aprobado';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAAPPROVEDBY IS 'FK usuario que aprobó';
COMMENT ON COLUMN FRIAFUNDAMENTALRIGHTSASSESSMENTS.FRIAAPPROVALDATE IS 'Fecha de aprobación';

-- Foreign Keys
ALTER TABLE FRIAFUNDAMENTALRIGHTSASSESSMENTS 
    ADD CONSTRAINT fk_fria_project 
    FOREIGN KEY (IDXPROJECT) REFERENCES PRJPROJECTS(IDXPROJECT) ON DELETE CASCADE;

-- Índices para búsquedas frecuentes
CREATE INDEX IF NOT EXISTS idx_fria_project ON FRIAFUNDAMENTALRIGHTSASSESSMENTS(IDXPROJECT);
CREATE INDEX IF NOT EXISTS idx_fria_deployer ON FRIAFUNDAMENTALRIGHTSASSESSMENTS(IDXUSER);
CREATE INDEX IF NOT EXISTS idx_fria_compliant ON FRIAFUNDAMENTALRIGHTSASSESSMENTS(FRIAART27COMPLIANT);
CREATE INDEX IF NOT EXISTS idx_fria_approved ON FRIAFUNDAMENTALRIGHTSASSESSMENTS(FRIAAPPROVED);
CREATE INDEX IF NOT EXISTS idx_fria_notified ON FRIAFUNDAMENTALRIGHTSASSESSMENTS(FRIANOTIFIED);
CREATE INDEX IF NOT EXISTS idx_fria_severity ON FRIAFUNDAMENTALRIGHTSASSESSMENTS(FRIAIMPACTSEVERITY);
CREATE INDEX IF NOT EXISTS idx_fria_createdat ON FRIAFUNDAMENTALRIGHTSASSESSMENTS(FRIACREATEDAT DESC);

-- Índices GIN para búsquedas en JSONB
CREATE INDEX IF NOT EXISTS idx_fria_affected_gin ON FRIAFUNDAMENTALRIGHTSASSESSMENTS USING GIN(to_tsvector('english', FRIAAFFECTEDCATEGORIES));
CREATE INDEX IF NOT EXISTS idx_fria_risks_gin ON FRIAFUNDAMENTALRIGHTSASSESSMENTS USING GIN(to_tsvector('english', FRIARISKS));

-- Vista para FRIAs pendientes de aprobación
CREATE OR REPLACE VIEW vw_fria_pending_approval AS
SELECT 
    f.IDXFRIAASSESSMENT,
    f.iduuid,
    f.IDXPROJECT,
    p.NAME as project_name,
    f.FRIACOMPLETENESSCORE,
    f.FRIAQUALSCORE,
    f.FRIAIMPACTSEVERITY,
    f.FRIACREATEDAT,
    EXTRACT(DAY FROM (CURRENT_TIMESTAMP - f.FRIACREATEDAT)) as days_pending
FROM FRIAFUNDAMENTALRIGHTSASSESSMENTS f
INNER JOIN PRJPROJECTS p ON f.IDXPROJECT = p.IDXPROJECT
WHERE f.FRIAAPPROVED = FALSE
  AND f.FRIAART27COMPLIANT = TRUE
ORDER BY f.FRIACREATEDAT ASC;

COMMENT ON VIEW vw_fria_pending_approval IS 'FRIAs completas y pendientes de aprobación';

COMMIT;

